// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=srpc -id inputEvent -d Type=inputEvent github.com/platinasystems/go/elib/elog/event.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package srpc

import (
	"github.com/platinasystems/go/elib/elog"
)

var inputEventType = &elog.EventType{
	Name: "srpc.inputEvent",
}

func init() {
	t := inputEventType
	t.Stringer = stringer_inputEvent
	t.Encode = encode_inputEvent
	t.Decode = decode_inputEvent
	elog.RegisterType(inputEventType)
}

func stringer_inputEvent(e *elog.Event) string {
	var x inputEvent
	x.Decode(e.Data[:])
	return x.String()
}

func encode_inputEvent(b []byte, e *elog.Event) int {
	var x inputEvent
	x.Decode(e.Data[:])
	return x.Encode(b)
}

func decode_inputEvent(b []byte, e *elog.Event) int {
	var x inputEvent
	x.Decode(b)
	return x.Encode(e.Data[:])
}

func (x inputEvent) Log() { x.Logb(elog.DefaultBuffer) }

func (x inputEvent) Logb(b *elog.Buffer) {
	e := b.Add(inputEventType)
	x.Encode(e.Data[:])
}
