// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id DataHook -d Package=pg -d DepsType=DataHookVec -d Type=DataHook -d Data=hooks github.com/platinasystems/go/elib/dep/dep.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package pg

import (
	"github.com/platinasystems/go/elib/dep"
)

type DataHookVec struct {
	deps  dep.Deps
	hooks []DataHook
}

func (t *DataHookVec) Len() int {
	return t.deps.Len()
}

func (t *DataHookVec) Get(i int) DataHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *DataHookVec) Add(x DataHook, ds ...*dep.Dep) {
	if len(ds) == 0 {
		t.deps.Add(&dep.Dep{})
	} else {
		t.deps.Add(ds[0])
	}
	t.hooks = append(t.hooks, x)
}
