// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=fe1a -id pipe_counter -d VecType=pipe_counter_vec -d Type=pipe_counter github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package fe1a

import (
	"github.com/platinasystems/go/elib"
)

type pipe_counter_vec []pipe_counter

func (p *pipe_counter_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]pipe_counter, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *pipe_counter_vec) validate(new_len uint, zero *pipe_counter) *pipe_counter {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *pipe_counter_vec) validateSlowPath(zero *pipe_counter,
	c, l, lʹ elib.Index) *pipe_counter {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]pipe_counter, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *pipe_counter_vec) Validate(i uint) *pipe_counter {
	return p.validate(i+1, (*pipe_counter)(nil))
}

func (p *pipe_counter_vec) ValidateInit(i uint, zero pipe_counter) *pipe_counter {
	return p.validate(i+1, &zero)
}

func (p *pipe_counter_vec) ValidateLen(l uint) (v *pipe_counter) {
	if l > 0 {
		v = p.validate(l, (*pipe_counter)(nil))
	}
	return
}

func (p *pipe_counter_vec) ValidateLenInit(l uint, zero pipe_counter) (v *pipe_counter) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p pipe_counter_vec) Len() uint { return uint(len(p)) }
