// Copyright © 2023-2024 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

package vpn

import (
	"bytes"
	"testing"

	"github.com/platinasystems/goes/v2/pkg/xlog"
)

const testCertificates = `
-----BEGIN CERTIFICATE-----
MIIBszCCAWWgAwIBAgIBATAFBgMrZXAwQTEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxETAPBgNVBAMTCHJlZ2lzdHJ5MQowCAYDVQQFEwExMB4XDTI0
MDUxNzE2MTkyOVoXDTM0MDUxNTE2MTkyOVowQTEgMA4GA1UEChMHUGxhdGluYTAO
BgNVBAoTB1N5c3RlbXMxETAPBgNVBAMTCHJlZ2lzdHJ5MQowCAYDVQQFEwExMCow
BQYDK2VwAyEAYU+WgvyJmTN8OJrj6dKekDpvCYEQSDMxBAYq2D5mwsajgYEwfzAO
BgNVHQ8BAf8EBAMCAoQwHQYDVR0OBBYEFMAlIbHqNKlSRvEtF3SnHx2QszBNME4G
A1UdEQRHMEWCJnJlZ2lzdHJ5LnZwbi5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2Fs
gRt0Z3Jlbm5hbkBwbGF0aW5hc3lzdGVtcy5jb20wBQYDK2VwA0EABeFDf1ZYb+CG
9r+qaDkpx44PNvCBqHFmABkUFE5z3sIu15hzy5xjpP2lTDRUN7cwIU2ErJGBhgCl
fhoqrENQCA==
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBtzCCAWmgAwIBAgIBATAFBgMrZXAwQjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxEjAQBgNVBAMTCWV4Y2hhbmdlMDEKMAgGA1UEBRMBMTAeFw0y
NDA1MTcxNjIyNTJaFw0zNDA1MTUxNjIyNTJaMEIxIDAOBgNVBAoTB1BsYXRpbmEw
DgYDVQQKEwdTeXN0ZW1zMRIwEAYDVQQDEwlleGNoYW5nZTAxCjAIBgNVBAUTATEw
KjAFBgMrZXADIQACcPfAPdRFZXCYA9Z8t3jBxHKIngvIF+uadun2GiY/MaOBgzCB
gDAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0OBBYEFMOufzh8QKTwbS9uR2QtzlnrQpvF
ME8GA1UdEQRIMEaCJ2V4Y2hhbmdlMC52cG4uZGVmYXVsdC5zdmMuY2x1c3Rlci5s
b2NhbIEbdGdyZW5uYW5AcGxhdGluYXN5c3RlbXMuY29tMAUGAytlcANBAD4M/p0t
zKAjxq3KFcrmpvbXLu61pUO20garswThTJBorXxkJHrDbujsM16Pq4zdm62yd6N6
OUo0wjIsjNRgaQk=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBtzCCAWmgAwIBAgIBATAFBgMrZXAwQjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxEjAQBgNVBAMTCWV4Y2hhbmdlMTEKMAgGA1UEBRMBMTAeFw0y
NDA1MTcxNjIyNTJaFw0zNDA1MTUxNjIyNTJaMEIxIDAOBgNVBAoTB1BsYXRpbmEw
DgYDVQQKEwdTeXN0ZW1zMRIwEAYDVQQDEwlleGNoYW5nZTExCjAIBgNVBAUTATEw
KjAFBgMrZXADIQAv/ZsFREfzWM6jTLU3R5SnVvy7ss0x2fwmY2VTbfq5SqOBgzCB
gDAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0OBBYEFDwrCiZCO7J9rPm6gvl9QRaLxpuE
ME8GA1UdEQRIMEaCJ2V4Y2hhbmdlMS52cG4uZGVmYXVsdC5zdmMuY2x1c3Rlci5s
b2NhbIEbdGdyZW5uYW5AcGxhdGluYXN5c3RlbXMuY29tMAUGAytlcANBAMbWn+NK
6UAKAYzbwpWrbpVvFwXiLkrxngsAk2fWZovinCJ51zaD78rowR9ZEWAmf0buv8Bv
j3A6NrVUxuppLgM=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBtzCCAWmgAwIBAgIBATAFBgMrZXAwQjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxEjAQBgNVBAMTCWV4Y2hhbmdlMjEKMAgGA1UEBRMBMTAeFw0y
NDA1MTcxNjIyNTJaFw0zNDA1MTUxNjIyNTJaMEIxIDAOBgNVBAoTB1BsYXRpbmEw
DgYDVQQKEwdTeXN0ZW1zMRIwEAYDVQQDEwlleGNoYW5nZTIxCjAIBgNVBAUTATEw
KjAFBgMrZXADIQAFRAKdp2m/hTybO0q3yl/O/Y6brAolSAlyFp4FGdQAXqOBgzCB
gDAOBgNVHQ8BAf8EBAMCAoQwHQYDVR0OBBYEFGghvWKa7UVw7TXLh4RcaxtRegeU
ME8GA1UdEQRIMEaCJ2V4Y2hhbmdlMi52cG4uZGVmYXVsdC5zdmMuY2x1c3Rlci5s
b2NhbIEbdGdyZW5uYW5AcGxhdGluYXN5c3RlbXMuY29tMAUGAytlcANBAIcA5dCo
KzDYkgQDvMoEN+xphLoox5T873BOXBrYK3a2N/T/yvHM9MFBKOY+feQhD9WzBjdt
Pu5SweHkfrUsJg0=
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBqTCCAVugAwIBAgIBATAFBgMrZXAwPjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxDjAMBgNVBAMTBWhvc3RhMQowCAYDVQQFEwExMB4XDTI0MDQx
OTAwNTQzOVoXDTM0MDQxNzAwNTQzOVowPjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxDjAMBgNVBAMTBWhvc3RhMQowCAYDVQQFEwExMCowBQYDK2Vw
AyEAFv3u3iP3Roi0AzJLG34yszrBHXQHHPwKADUVn9eFDfSjfjB8MA4GA1UdDwEB
/wQEAwIChDAdBgNVHQ4EFgQUnYyGd2Ov6LroYI9Vr7FIl+5witcwSwYDVR0RBEQw
QoIjaG9zdGEudnBuLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWyBG3RncmVubmFu
QHBsYXRpbmFzeXN0ZW1zLmNvbTAFBgMrZXADQQA4bWuVCV05BaxwsQGs17mMilEl
rCxXdKWjfZ1/oKbAIfbvCzjuy4kurBp/3i6u2vqCF2aqBiIyAvBYrZl1fkcE
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBqTCCAVugAwIBAgIBATAFBgMrZXAwPjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxDjAMBgNVBAMTBWhvc3RiMQowCAYDVQQFEwExMB4XDTI0MDQx
OTAwNTQyMFoXDTM0MDQxNzAwNTQyMFowPjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxDjAMBgNVBAMTBWhvc3RiMQowCAYDVQQFEwExMCowBQYDK2Vw
AyEAHKvgZm/IpE6CyE256C+wPYgSktPrGB5NuXMWsIx5PBOjfjB8MA4GA1UdDwEB
/wQEAwIChDAdBgNVHQ4EFgQUkLLRf3iwgLiE+vHVcxKBQFUdBqQwSwYDVR0RBEQw
QoIjaG9zdGIudnBuLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWyBG3RncmVubmFu
QHBsYXRpbmFzeXN0ZW1zLmNvbTAFBgMrZXADQQDchnAY9N0MrJxFrrKaAdzeJFB7
U9h1Zjf/4wOeSgP5TVTj1YCs+b3cd76JRWdpkxrFFPJK+hZx1UmNY7EaD/8H
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBqTCCAVugAwIBAgIBATAFBgMrZXAwPjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxDjAMBgNVBAMTBWhvc3RjMQowCAYDVQQFEwExMB4XDTI0MDQx
OTAwNTUwOFoXDTM0MDQxNzAwNTUwOFowPjEgMA4GA1UEChMHUGxhdGluYTAOBgNV
BAoTB1N5c3RlbXMxDjAMBgNVBAMTBWhvc3RjMQowCAYDVQQFEwExMCowBQYDK2Vw
AyEA5DatFIt5LJXRi9E5r9X9Cmhi3+1lV7BfCNm44B0cuAqjfjB8MA4GA1UdDwEB
/wQEAwIChDAdBgNVHQ4EFgQU0i4lsQ6JrZ/1L/YODUZ2lx4GaIAwSwYDVR0RBEQw
QoIjaG9zdGMudnBuLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWyBG3RncmVubmFu
QHBsYXRpbmFzeXN0ZW1zLmNvbTAFBgMrZXADQQB/bTs5UehKafm2/9L0RrJkzIjJ
4XwUPaIdpGqblfcqbsGNshNGZgw8x3rNlAx3vS6AGzYxQiJfY9J7a5jZVbUB
-----END CERTIFICATE-----
`

func TestReadCertificates(t *testing.T) {
	want := []string{
		"registry",
		"exchange0",
		"exchange1",
		"exchange2",
		"hosta",
		"hostb",
		"hostc",
	}
	if testing.Verbose() {
		xlog.UnmuteTrace()
	}
	r := bytes.NewBufferString(testCertificates[1:])
	cs, err := readCertificates(r)
	if err != nil {
		t.Fatal(err)
	}
	if ncs, nwant := len(cs), len(want); ncs != nwant {
		t.Fatal(ncs, "!=", nwant)
	}
	for i, c := range cs {
		if got := c.Subject.CommonName; got != want[i] {
			t.Fatal(got, "!=", want[i])
		}
	}
}
