// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- netif_darwin.go

package netif

const (
	IFNAMSIZ		= 0x10
	AF_SYS_CONTROL		= 0x2
	AF_SYSTEM		= 0x20
	PF_SYSTEM		= 0x20
	SYSPROTO_CONTROL	= 0x2
	CTLIOCGINFO		= 0xc0644e03
)

type Ifreq struct {
	Name	[16]int8
	Ifru	[16]byte
}

const SizeofIfreq = 0x20

type CtlInfo struct {
	Id	uint32
	Name	[96]int8
}

const SizeofCtlInfo = 0x64

type SockaddrCtl struct {
	Sc_len		uint8
	Sc_family	uint8
	Ss_sysaddr	uint16
	Sc_id		uint32
	Sc_unit		uint32
	Sc_reserved	[5]uint32
}

const SizeofSockaddrCtl = 0x20

type In6Ifreq struct {
	Name	[16]int8
	Ifru	[272]byte
}

const SizeofIn6Ifreq = 0x120

const (
	SIOCGIFADDR_IN6		= 0xc1206921
	SIOCSIFADDR_IN6		= 0x8120690c
	SIOCDIFADDR_IN6		= 0x81206919
	SIOCGIFNETMASK_IN6	= 0xc1206925
	SIOCSIFNETMASK_IN6	= 0x81206916
	SIOCGIFDSTADDR_IN6	= 0xc1206922
	SIOCSIFDSTADDR_IN6	= 0x8120690e
	SIOCGIFAFLAG_IN6	= 0xc1206949
	SIOCGIFSTAT_IN6		= 0xc1206953
	SIOCGIFSTAT_ICMP6	= 0xc1206954
	SIOCGSCOPE6		= 0xc1206959
	SIOCSSCOPE6		= 0x81206958
)
