// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- /home/tgrennan/netif/netif_linux.go

package netif

const IFNAMSIZ = 0x10

type Ifreq struct {
	Ifrn	[16]byte
	Ifru	[24]byte
}

const SizeofIfreq = 0x28

type In6Addr struct {
	U [16]byte
}

const SizeofIn6Addr = 0x10

type In6Ifreq struct {
	Addr		In6Addr
	Prefixlen	uint32
	Ifindex		int32
}

const SizeofIn6Ifreq = 0x18
