// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id FibShowUsageHook -d Package=ip4 -d DepsType=fibShowUsageHookVec -d Type=fibShowUsageHook -d Data=hooks github.com/platinasystems/go/elib/dep/dep.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ip4

import (
	"github.com/platinasystems/go/elib/dep"
)

type fibShowUsageHookVec struct {
	deps  dep.Deps
	hooks []fibShowUsageHook
}

func (t *fibShowUsageHookVec) Len() int {
	return t.deps.Len()
}

func (t *fibShowUsageHookVec) Get(i int) fibShowUsageHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *fibShowUsageHookVec) Add(x fibShowUsageHook, ds ...*dep.Dep) {
	if len(ds) == 0 {
		t.deps.Add(&dep.Dep{})
	} else {
		t.deps.Add(ds[0])
	}
	t.hooks = append(t.hooks, x)
}
