// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip4 -id Fib -d VecType=FibVec -d Type=*Fib github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ip4

import (
	"github.com/platinasystems/go/elib"
)

type FibVec []*Fib

func (p *FibVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*Fib, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *FibVec) validate(new_len uint, zero *Fib) **Fib {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *FibVec) validateSlowPath(zero *Fib, c, l, lʹ uint) **Fib {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*Fib, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *FibVec) Validate(i uint) **Fib {
	var zero *Fib
	return p.validate(i+1, zero)
}

func (p *FibVec) ValidateInit(i uint, zero *Fib) **Fib {
	return p.validate(i+1, zero)
}

func (p *FibVec) ValidateLen(l uint) (v **Fib) {
	if l > 0 {
		var zero *Fib
		v = p.validate(l, zero)
	}
	return
}

func (p *FibVec) ValidateLenInit(l uint, zero *Fib) (v **Fib) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *FibVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p FibVec) Len() uint { return uint(len(p)) }
