// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip4 -id Fib -d VecType=FibVec -d Type=*Fib github.com/platinasystems/go/elib/vec.tmpl]

package ip4

import (
	"github.com/platinasystems/go/elib"
)

type FibVec []*Fib

func (p *FibVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*Fib, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *FibVec) validate(new_len uint, zero **Fib) **Fib {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *FibVec) validateSlowPath(zero **Fib,
	c, l, lʹ elib.Index) **Fib {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*Fib, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *FibVec) Validate(i uint) **Fib {
	return p.validate(i+1, (**Fib)(nil))
}

func (p *FibVec) ValidateInit(i uint, zero *Fib) **Fib {
	return p.validate(i+1, &zero)
}

func (p *FibVec) ValidateLen(l uint) (v **Fib) {
	if l > 0 {
		v = p.validate(l, (**Fib)(nil))
	}
	return
}

func (p *FibVec) ValidateLenInit(l uint, zero *Fib) (v **Fib) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p FibVec) Len() uint { return uint(len(p)) }
