// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by "stringer -type=Opcode"; DO NOT EDIT

package sbus

import "fmt"

const _Opcode_name = "ReadMemoryReadMemoryAckWriteMemoryWriteMemoryAckReadRegisterReadRegisterAckWriteRegisterWriteRegisterAck"

var _Opcode_index = [...]uint8{0, 10, 23, 34, 48, 60, 75, 88, 104}

func (i Opcode) String() string {
	i -= 7
	if i >= Opcode(len(_Opcode_index)-1) {
		return fmt.Sprintf("Opcode(%d)", i+7)
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
