// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id randSparse -d VecType=randSparseVec -tags debug -d Type=randSparse vec.tmpl]

//+build debug

package elib

type randSparseVec []randSparse

func (p *randSparseVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]randSparse, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *randSparseVec) Validate(i uint) {
	c := Index(cap(*p))
	l := Index(i) + 1
	if l > c {
		c = NextResizeCap(l)
		q := make([]randSparse, l, c)
		copy(q, *p)
		*p = q
	}
	if l > Index(len(*p)) {
		*p = (*p)[:l]
	}
}

func (p randSparseVec) Len() uint { return uint(len(p)) }
