// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Word -d VecType=WordVec -d Type=Word vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type WordVec []Word

func (p *WordVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = NextResizeCap(l)
		q := make([]Word, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *WordVec) validate(new_len uint, zero Word) *Word {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *WordVec) validateSlowPath(zero Word, c, l, lʹ uint) *Word {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]Word, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *WordVec) Validate(i uint) *Word {
	var zero Word
	return p.validate(i+1, zero)
}

func (p *WordVec) ValidateInit(i uint, zero Word) *Word {
	return p.validate(i+1, zero)
}

func (p *WordVec) ValidateLen(l uint) (v *Word) {
	if l > 0 {
		var zero Word
		v = p.validate(l, zero)
	}
	return
}

func (p *WordVec) ValidateLenInit(l uint, zero Word) (v *Word) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *WordVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p WordVec) Len() uint { return uint(len(p)) }
