// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Bitmap -d PoolType=BitmapPool -d Type=BitmapVec -d Data=bitmaps pool.tmpl]

package elib

type BitmapPool struct {
	Pool
	bitmaps []BitmapVec
}

func (p *BitmapPool) GetIndex() (i uint) {
	l := uint(len(p.bitmaps))
	i = p.Pool.GetIndex(l)
	if i >= l {
		p.Validate(i)
	}
	return i
}

func (p *BitmapPool) PutIndex(i uint) (ok bool) {
	return p.Pool.PutIndex(i)
}

func (p *BitmapPool) IsFree(i uint) (v bool) {
	v = i >= uint(len(p.bitmaps))
	if !v {
		v = p.Pool.IsFree(i)
	}
	return
}

func (p *BitmapPool) Resize(n uint) {
	c := Index(cap(p.bitmaps))
	l := Index(len(p.bitmaps) + int(n))
	if l > c {
		c = NextResizeCap(l)
		q := make([]BitmapVec, l, c)
		copy(q, p.bitmaps)
		p.bitmaps = q
	}
	p.bitmaps = p.bitmaps[:l]
}

func (p *BitmapPool) Validate(i uint) {
	c := Index(cap(p.bitmaps))
	l := Index(i) + 1
	if l > c {
		c = NextResizeCap(l)
		q := make([]BitmapVec, l, c)
		copy(q, p.bitmaps)
		p.bitmaps = q
	}
	if l > Index(len(p.bitmaps)) {
		p.bitmaps = p.bitmaps[:l]
	}
}

func (p *BitmapPool) Elts() uint {
	return uint(len(p.bitmaps)) - p.FreeLen()
}

func (p *BitmapPool) Len() uint {
	return uint(len(p.bitmaps))
}

func (p *BitmapPool) Foreach(f func(x BitmapVec)) {
	for i := range p.bitmaps {
		if !p.Pool.IsFree(uint(i)) {
			f(p.bitmaps[i])
		}
	}
}
