// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Int8 -d VecType=Int8Vec -d Type=int8 vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type Int8Vec []int8

func (p *Int8Vec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]int8, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *Int8Vec) validate(new_len uint, zero int8) *int8 {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *Int8Vec) validateSlowPath(zero int8, old_cap, new_len, old_len uint) *int8 {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]int8, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *Int8Vec) Validate(i uint) *int8 {
	var zero int8
	return p.validate(i+1, zero)
}

func (p *Int8Vec) ValidateInit(i uint, zero int8) *int8 {
	return p.validate(i+1, zero)
}

func (p *Int8Vec) ValidateLen(l uint) (v *int8) {
	if l > 0 {
		var zero int8
		v = p.validate(l, zero)
	}
	return
}

func (p *Int8Vec) ValidateLenInit(l uint, zero int8) (v *int8) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *Int8Vec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p Int8Vec) Len() uint { return uint(len(p)) }
