// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Bitmaps -d VecType=BitmapsVec -d Type=[]Bitmap vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type BitmapsVec [][]Bitmap

func (p *BitmapsVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([][]Bitmap, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *BitmapsVec) validate(new_len uint, zero *[]Bitmap) *[]Bitmap {
	c := Index(cap(*p))
	lʹ := Index(len(*p))
	l := Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *BitmapsVec) validateSlowPath(zero *[]Bitmap,
	c, l, lʹ Index) *[]Bitmap {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([][]Bitmap, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *BitmapsVec) Validate(i uint) *[]Bitmap {
	return p.validate(i+1, (*[]Bitmap)(nil))
}

func (p *BitmapsVec) ValidateInit(i uint, zero []Bitmap) *[]Bitmap {
	return p.validate(i+1, &zero)
}

func (p *BitmapsVec) ValidateLen(l uint) (v *[]Bitmap) {
	if l > 0 {
		v = p.validate(l, (*[]Bitmap)(nil))
	}
	return
}

func (p *BitmapsVec) ValidateLenInit(l uint, zero []Bitmap) (v *[]Bitmap) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p BitmapsVec) Len() uint { return uint(len(p)) }
