// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Uint8 -d VecType=Uint8Vec -d Type=uint8 vec.tmpl]

package elib

type Uint8Vec []uint8

func (p *Uint8Vec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]uint8, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *Uint8Vec) validate(new_len uint, zero *uint8) *uint8 {
	c := Index(cap(*p))
	lʹ := Index(len(*p))
	l := Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *Uint8Vec) validateSlowPath(zero *uint8,
	c, l, lʹ Index) *uint8 {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]uint8, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *Uint8Vec) Validate(i uint) *uint8 {
	return p.validate(i+1, (*uint8)(nil))
}

func (p *Uint8Vec) ValidateInit(i uint, zero uint8) *uint8 {
	return p.validate(i+1, &zero)
}

func (p *Uint8Vec) ValidateLen(l uint) (v *uint8) {
	if l > 0 {
		v = p.validate(l, (*uint8)(nil))
	}
	return
}

func (p *Uint8Vec) ValidateLenInit(l uint, zero uint8) (v *uint8) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p Uint8Vec) Len() uint { return uint(len(p)) }
