// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id freeElts -d VecType=freeEltsVec -d Type=freeEltVec vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type freeEltsVec []freeEltVec

func (p *freeEltsVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = NextResizeCap(l)
		q := make([]freeEltVec, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *freeEltsVec) validate(new_len uint, zero freeEltVec) *freeEltVec {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *freeEltsVec) validateSlowPath(zero freeEltVec, c, l, lʹ uint) *freeEltVec {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]freeEltVec, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *freeEltsVec) Validate(i uint) *freeEltVec {
	var zero freeEltVec
	return p.validate(i+1, zero)
}

func (p *freeEltsVec) ValidateInit(i uint, zero freeEltVec) *freeEltVec {
	return p.validate(i+1, zero)
}

func (p *freeEltsVec) ValidateLen(l uint) (v *freeEltVec) {
	if l > 0 {
		var zero freeEltVec
		v = p.validate(l, zero)
	}
	return
}

func (p *freeEltsVec) ValidateLenInit(l uint, zero freeEltVec) (v *freeEltVec) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *freeEltsVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p freeEltsVec) Len() uint { return uint(len(p)) }
