// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id uiPair -d VecType=uiPairVec -d Type=uiPair vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type uiPairVec []uiPair

func (p *uiPairVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = NextResizeCap(l)
		q := make([]uiPair, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *uiPairVec) validate(new_len uint, zero uiPair) *uiPair {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *uiPairVec) validateSlowPath(zero uiPair, c, l, lʹ uint) *uiPair {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]uiPair, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *uiPairVec) Validate(i uint) *uiPair {
	var zero uiPair
	return p.validate(i+1, zero)
}

func (p *uiPairVec) ValidateInit(i uint, zero uiPair) *uiPair {
	return p.validate(i+1, zero)
}

func (p *uiPairVec) ValidateLen(l uint) (v *uiPair) {
	if l > 0 {
		var zero uiPair
		v = p.validate(l, zero)
	}
	return
}

func (p *uiPairVec) ValidateLenInit(l uint, zero uiPair) (v *uiPair) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *uiPairVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p uiPairVec) Len() uint { return uint(len(p)) }
