// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id randSparse -d VecType=randSparseVec -d Type=randSparse vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type randSparseVec []randSparse

func (p *randSparseVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]randSparse, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *randSparseVec) validate(new_len uint, zero randSparse) *randSparse {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *randSparseVec) validateSlowPath(zero randSparse, old_cap, new_len, old_len uint) *randSparse {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]randSparse, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *randSparseVec) Validate(i uint) *randSparse {
	var zero randSparse
	return p.validate(i+1, zero)
}

func (p *randSparseVec) ValidateInit(i uint, zero randSparse) *randSparse {
	return p.validate(i+1, zero)
}

func (p *randSparseVec) ValidateLen(l uint) (v *randSparse) {
	if l > 0 {
		var zero randSparse
		v = p.validate(l, zero)
	}
	return
}

func (p *randSparseVec) ValidateLenInit(l uint, zero randSparse) (v *randSparse) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *randSparseVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p randSparseVec) Len() uint { return uint(len(p)) }
