// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Uint16 -d VecType=Uint16Vec -d Type=uint16 vec.tmpl]

package elib

type Uint16Vec []uint16

func (p *Uint16Vec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]uint16, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *Uint16Vec) validate(new_len uint, zero *uint16) *uint16 {
	c := Index(cap(*p))
	lʹ := Index(len(*p))
	l := Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *Uint16Vec) validateSlowPath(zero *uint16,
	c, l, lʹ Index) *uint16 {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]uint16, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *Uint16Vec) Validate(i uint) *uint16 {
	return p.validate(i+1, (*uint16)(nil))
}

func (p *Uint16Vec) ValidateInit(i uint, zero uint16) *uint16 {
	return p.validate(i+1, &zero)
}

func (p *Uint16Vec) ValidateLen(l uint) (v *uint16) {
	if l > 0 {
		v = p.validate(l, (*uint16)(nil))
	}
	return
}

func (p *Uint16Vec) ValidateLenInit(l uint, zero uint16) (v *uint16) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p Uint16Vec) Len() uint { return uint(len(p)) }
