// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id String -d VecType=StringVec -d Type=string vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type StringVec []string

func (p *StringVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]string, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *StringVec) validate(new_len uint, zero string) *string {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *StringVec) validateSlowPath(zero string, old_cap, new_len, old_len uint) *string {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]string, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *StringVec) Validate(i uint) *string {
	var zero string
	return p.validate(i+1, zero)
}

func (p *StringVec) ValidateInit(i uint, zero string) *string {
	return p.validate(i+1, zero)
}

func (p *StringVec) ValidateLen(l uint) (v *string) {
	if l > 0 {
		var zero string
		v = p.validate(l, zero)
	}
	return
}

func (p *StringVec) ValidateLenInit(l uint, zero string) (v *string) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *StringVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p StringVec) Len() uint { return uint(len(p)) }
