// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id BitmapVec -d VecType=BitmapsVec -d Type=[]BitmapVec vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type BitmapsVec [][]BitmapVec

func (p *BitmapsVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([][]BitmapVec, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *BitmapsVec) validate(new_len uint, zero []BitmapVec) *[]BitmapVec {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *BitmapsVec) validateSlowPath(zero []BitmapVec, old_cap, new_len, old_len uint) *[]BitmapVec {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([][]BitmapVec, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *BitmapsVec) Validate(i uint) *[]BitmapVec {
	var zero []BitmapVec
	return p.validate(i+1, zero)
}

func (p *BitmapsVec) ValidateInit(i uint, zero []BitmapVec) *[]BitmapVec {
	return p.validate(i+1, zero)
}

func (p *BitmapsVec) ValidateLen(l uint) (v *[]BitmapVec) {
	if l > 0 {
		var zero []BitmapVec
		v = p.validate(l, zero)
	}
	return
}

func (p *BitmapsVec) ValidateLenInit(l uint, zero []BitmapVec) (v *[]BitmapVec) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *BitmapsVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p BitmapsVec) Len() uint { return uint(len(p)) }
