// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id freeElt -d VecType=freeEltVec -d Type=freeElt vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type freeEltVec []freeElt

func (p *freeEltVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]freeElt, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *freeEltVec) validate(new_len uint, zero freeElt) *freeElt {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *freeEltVec) validateSlowPath(zero freeElt, old_cap, new_len, old_len uint) *freeElt {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]freeElt, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *freeEltVec) Validate(i uint) *freeElt {
	var zero freeElt
	return p.validate(i+1, zero)
}

func (p *freeEltVec) ValidateInit(i uint, zero freeElt) *freeElt {
	return p.validate(i+1, zero)
}

func (p *freeEltVec) ValidateLen(l uint) (v *freeElt) {
	if l > 0 {
		var zero freeElt
		v = p.validate(l, zero)
	}
	return
}

func (p *freeEltVec) ValidateLenInit(l uint, zero freeElt) (v *freeElt) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *freeEltVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p freeEltVec) Len() uint { return uint(len(p)) }
