// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id uiPair -d VecType=uiPairVec -d Type=uiPair vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type uiPairVec []uiPair

func (p *uiPairVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]uiPair, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *uiPairVec) validate(new_len uint, zero uiPair) *uiPair {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *uiPairVec) validateSlowPath(zero uiPair, old_cap, new_len, old_len uint) *uiPair {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]uiPair, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *uiPairVec) Validate(i uint) *uiPair {
	var zero uiPair
	return p.validate(i+1, zero)
}

func (p *uiPairVec) ValidateInit(i uint, zero uiPair) *uiPair {
	return p.validate(i+1, zero)
}

func (p *uiPairVec) ValidateLen(l uint) (v *uiPair) {
	if l > 0 {
		var zero uiPair
		v = p.validate(l, zero)
	}
	return
}

func (p *uiPairVec) ValidateLenInit(l uint, zero uiPair) (v *uiPair) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *uiPairVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p uiPairVec) Len() uint { return uint(len(p)) }
