// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id randHeapObj -d VecType=randHeapObjVec -d Type=randHeapObj vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type randHeapObjVec []randHeapObj

func (p *randHeapObjVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = NextResizeCap(l)
		q := make([]randHeapObj, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *randHeapObjVec) validate(new_len uint, zero randHeapObj) *randHeapObj {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *randHeapObjVec) validateSlowPath(zero randHeapObj, c, l, lʹ uint) *randHeapObj {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]randHeapObj, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *randHeapObjVec) Validate(i uint) *randHeapObj {
	var zero randHeapObj
	return p.validate(i+1, zero)
}

func (p *randHeapObjVec) ValidateInit(i uint, zero randHeapObj) *randHeapObj {
	return p.validate(i+1, zero)
}

func (p *randHeapObjVec) ValidateLen(l uint) (v *randHeapObj) {
	if l > 0 {
		var zero randHeapObj
		v = p.validate(l, zero)
	}
	return
}

func (p *randHeapObjVec) ValidateLenInit(l uint, zero randHeapObj) (v *randHeapObj) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *randHeapObjVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p randHeapObjVec) Len() uint { return uint(len(p)) }
