// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Bitmap -d VecType=BitmapVec -d Type=Bitmap vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type BitmapVec []Bitmap

func (p *BitmapVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]Bitmap, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *BitmapVec) validate(new_len uint, zero Bitmap) *Bitmap {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *BitmapVec) validateSlowPath(zero Bitmap, old_cap, new_len, old_len uint) *Bitmap {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]Bitmap, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *BitmapVec) Validate(i uint) *Bitmap {
	var zero Bitmap
	return p.validate(i+1, zero)
}

func (p *BitmapVec) ValidateInit(i uint, zero Bitmap) *Bitmap {
	return p.validate(i+1, zero)
}

func (p *BitmapVec) ValidateLen(l uint) (v *Bitmap) {
	if l > 0 {
		var zero Bitmap
		v = p.validate(l, zero)
	}
	return
}

func (p *BitmapVec) ValidateLenInit(l uint, zero Bitmap) (v *Bitmap) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *BitmapVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p BitmapVec) Len() uint { return uint(len(p)) }
