// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Uint8 -d VecType=Uint8Vec -d Type=uint8 vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type Uint8Vec []uint8

func (p *Uint8Vec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = NextResizeCap(l)
		q := make([]uint8, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *Uint8Vec) validate(new_len uint, zero uint8) *uint8 {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *Uint8Vec) validateSlowPath(zero uint8, c, l, lʹ uint) *uint8 {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]uint8, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *Uint8Vec) Validate(i uint) *uint8 {
	var zero uint8
	return p.validate(i+1, zero)
}

func (p *Uint8Vec) ValidateInit(i uint, zero uint8) *uint8 {
	return p.validate(i+1, zero)
}

func (p *Uint8Vec) ValidateLen(l uint) (v *uint8) {
	if l > 0 {
		var zero uint8
		v = p.validate(l, zero)
	}
	return
}

func (p *Uint8Vec) ValidateLenInit(l uint, zero uint8) (v *uint8) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *Uint8Vec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p Uint8Vec) Len() uint { return uint(len(p)) }
