// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Float32 -d VecType=Float32Vec -d Type=float32 vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type Float32Vec []float32

func (p *Float32Vec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = NextResizeCap(l)
		q := make([]float32, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *Float32Vec) validate(new_len uint, zero float32) *float32 {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *Float32Vec) validateSlowPath(zero float32, c, l, lʹ uint) *float32 {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]float32, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *Float32Vec) Validate(i uint) *float32 {
	var zero float32
	return p.validate(i+1, zero)
}

func (p *Float32Vec) ValidateInit(i uint, zero float32) *float32 {
	return p.validate(i+1, zero)
}

func (p *Float32Vec) ValidateLen(l uint) (v *float32) {
	if l > 0 {
		var zero float32
		v = p.validate(l, zero)
	}
	return
}

func (p *Float32Vec) ValidateLenInit(l uint, zero float32) (v *float32) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *Float32Vec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p Float32Vec) Len() uint { return uint(len(p)) }
