// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id randHeapObj -d VecType=randHeapObjVec -d Type=randHeapObj vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type randHeapObjVec []randHeapObj

func (p *randHeapObjVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]randHeapObj, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *randHeapObjVec) validate(new_len uint, zero randHeapObj) *randHeapObj {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *randHeapObjVec) validateSlowPath(zero randHeapObj, old_cap, new_len, old_len uint) *randHeapObj {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]randHeapObj, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *randHeapObjVec) Validate(i uint) *randHeapObj {
	var zero randHeapObj
	return p.validate(i+1, zero)
}

func (p *randHeapObjVec) ValidateInit(i uint, zero randHeapObj) *randHeapObj {
	return p.validate(i+1, zero)
}

func (p *randHeapObjVec) ValidateLen(l uint) (v *randHeapObj) {
	if l > 0 {
		var zero randHeapObj
		v = p.validate(l, zero)
	}
	return
}

func (p *randHeapObjVec) ValidateLenInit(l uint, zero randHeapObj) (v *randHeapObj) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *randHeapObjVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p randHeapObjVec) Len() uint { return uint(len(p)) }
