// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id String -d VecType=StringVec -d Type=string vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type StringVec []string

func (p *StringVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]string, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *StringVec) validate(new_len uint, zero string) *string {
	c := Index(cap(*p))
	lʹ := Index(len(*p))
	l := Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *StringVec) validateSlowPath(zero string, c, l, lʹ Index) *string {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]string, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *StringVec) Validate(i uint) *string {
	var zero string
	return p.validate(i+1, zero)
}

func (p *StringVec) ValidateInit(i uint, zero string) *string {
	return p.validate(i+1, zero)
}

func (p *StringVec) ValidateLen(l uint) (v *string) {
	if l > 0 {
		var zero string
		v = p.validate(l, zero)
	}
	return
}

func (p *StringVec) ValidateLenInit(l uint, zero string) (v *string) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p StringVec) Len() uint { return uint(len(p)) }
