// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Byte -d VecType=ByteVec -d Type=byte vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type ByteVec []byte

func (p *ByteVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]byte, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *ByteVec) validate(new_len uint, zero byte) *byte {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *ByteVec) validateSlowPath(zero byte, old_cap, new_len, old_len uint) *byte {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]byte, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *ByteVec) Validate(i uint) *byte {
	var zero byte
	return p.validate(i+1, zero)
}

func (p *ByteVec) ValidateInit(i uint, zero byte) *byte {
	return p.validate(i+1, zero)
}

func (p *ByteVec) ValidateLen(l uint) (v *byte) {
	if l > 0 {
		var zero byte
		v = p.validate(l, zero)
	}
	return
}

func (p *ByteVec) ValidateLenInit(l uint, zero byte) (v *byte) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *ByteVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p ByteVec) Len() uint { return uint(len(p)) }
