// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id Float64 -d VecType=Float64Vec -d Type=float64 vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type Float64Vec []float64

func (p *Float64Vec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]float64, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *Float64Vec) validate(new_len uint, zero float64) *float64 {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *Float64Vec) validateSlowPath(zero float64, old_cap, new_len, old_len uint) *float64 {
	if new_len > old_cap {
		new_cap := NextResizeCap(new_len)
		q := make([]float64, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *Float64Vec) Validate(i uint) *float64 {
	var zero float64
	return p.validate(i+1, zero)
}

func (p *Float64Vec) ValidateInit(i uint, zero float64) *float64 {
	return p.validate(i+1, zero)
}

func (p *Float64Vec) ValidateLen(l uint) (v *float64) {
	if l > 0 {
		var zero float64
		v = p.validate(l, zero)
	}
	return
}

func (p *Float64Vec) ValidateLenInit(l uint, zero float64) (v *float64) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *Float64Vec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p Float64Vec) Len() uint { return uint(len(p)) }
