// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elib -id randSparse -d VecType=randSparseVec -d Type=randSparse vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elib

type randSparseVec []randSparse

func (p *randSparseVec) Resize(n uint) {
	c := Index(cap(*p))
	l := Index(len(*p)) + Index(n)
	if l > c {
		c = NextResizeCap(l)
		q := make([]randSparse, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *randSparseVec) validate(new_len uint, zero randSparse) *randSparse {
	c := Index(cap(*p))
	lʹ := Index(len(*p))
	l := Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *randSparseVec) validateSlowPath(zero randSparse, c, l, lʹ Index) *randSparse {
	if l > c {
		cNext := NextResizeCap(l)
		q := make([]randSparse, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *randSparseVec) Validate(i uint) *randSparse {
	var zero randSparse
	return p.validate(i+1, zero)
}

func (p *randSparseVec) ValidateInit(i uint, zero randSparse) *randSparse {
	return p.validate(i+1, zero)
}

func (p *randSparseVec) ValidateLen(l uint) (v *randSparse) {
	if l > 0 {
		var zero randSparse
		v = p.validate(l, zero)
	}
	return
}

func (p *randSparseVec) ValidateLenInit(l uint, zero randSparse) (v *randSparse) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *randSparseVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p randSparseVec) Len() uint { return uint(len(p)) }
