// Code generated by "stringer -output=zicmp6_invalid_parameter_string.go -type=ICMP6InvalidParameterCode -trimprefix=ICMP6InvalidParameterCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMP6InvalidParameterCodeErroneousHeader-0]
	_ = x[ICMP6InvalidParameterCodeUnrecognizedNextHeader-1]
	_ = x[ICMP6InvalidParameterCodeUnrecognizedOption-2]
}

const _ICMP6InvalidParameterCode_name = "ErroneousHeaderUnrecognizedNextHeaderUnrecognizedOption"

var _ICMP6InvalidParameterCode_index = [...]uint8{0, 15, 37, 55}

func (i ICMP6InvalidParameterCode) String() string {
	if i >= ICMP6InvalidParameterCode(len(_ICMP6InvalidParameterCode_index)-1) {
		return "ICMP6InvalidParameterCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMP6InvalidParameterCode_name[_ICMP6InvalidParameterCode_index[i]:_ICMP6InvalidParameterCode_index[i+1]]
}
