// Code generated by "stringer -output=zicmp_extended_echo_reply_string.go -type=ICMPExtendedEchoReplyCode -trimprefix=ICMPExtendedEchoReplyCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMPExtendedEchoReplyCodeNoError-0]
	_ = x[ICMPExtendedEchoReplyCodeMalformedQuery-1]
	_ = x[ICMPExtendedEchoReplyCodeNoSuchInterface-2]
	_ = x[ICMPExtendedEchoReplyCodeNoSuchTableEntry-3]
	_ = x[ICMPExtendedEchoReplyCodeAmbiguousInterface-4]
}

const _ICMPExtendedEchoReplyCode_name = "NoErrorMalformedQueryNoSuchInterfaceNoSuchTableEntryAmbiguousInterface"

var _ICMPExtendedEchoReplyCode_index = [...]uint8{0, 7, 21, 36, 52, 70}

func (i ICMPExtendedEchoReplyCode) String() string {
	if i >= ICMPExtendedEchoReplyCode(len(_ICMPExtendedEchoReplyCode_index)-1) {
		return "ICMPExtendedEchoReplyCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMPExtendedEchoReplyCode_name[_ICMPExtendedEchoReplyCode_index[i]:_ICMPExtendedEchoReplyCode_index[i+1]]
}
