// Code generated by "stringer -output=zicmp6_type_string.go -type=ICMP6Type -trimprefix=ICMP6Type ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMP6TypeDestinationUnreachable-1]
	_ = x[ICMP6TypePacketTooBig-2]
	_ = x[ICMP6TypeTimeExceeded-3]
	_ = x[ICMP6TypeInvalidParameter-4]
	_ = x[ICMP6TypeEchoRequest-128]
	_ = x[ICMP6TypeEchoReply-129]
	_ = x[ICMP6TypeMulticastListenerQuery-130]
	_ = x[ICMP6TypeMulticastListenerReport-131]
	_ = x[ICMP6TypeMulticastListenerDone-132]
	_ = x[ICMP6TypeRouterSolicitation-133]
	_ = x[ICMP6TypeRouterAdvertisement-134]
	_ = x[ICMP6TypeNeighborSolicitation-135]
	_ = x[ICMP6TypeNeighborAdvertisement-136]
	_ = x[ICMP6TypeRedirectMessage-137]
	_ = x[ICMP6TypeRouterRenumbering-138]
	_ = x[ICMP6TypeNodeInformationQuery-139]
	_ = x[ICMP6TypeNodeInformationResponse-140]
	_ = x[ICMP6TypeInverseNeighborDiscoverySolicitation-141]
	_ = x[ICMP6TypeInverseNeighborDiscoveryAdvertisement-142]
	_ = x[ICMP6TypeMulticastListenerDiscovery-143]
	_ = x[ICMP6TypeHomeAgentAddressDiscoveryRequest-144]
	_ = x[ICMP6TypeHomeAgentAddressDiscoveryReply-145]
	_ = x[ICMP6TypeMobilePrefixSolicitation-146]
	_ = x[ICMP6TypeMobilePrefixAdvertisement-147]
	_ = x[ICMP6TypeCertificationPathSolicitation-148]
	_ = x[ICMP6TypeCertificationPathAdvertisement-149]
	_ = x[ICMP6TypeMulticastRouterAdvertisement-151]
	_ = x[ICMP6TypeMulticastRouterSolicitation-152]
	_ = x[ICMP6TypeMulticastRouterTermination-153]
	_ = x[ICMP6TypeRPLControlMessage-155]
}

const (
	_ICMP6Type_name_0 = "DestinationUnreachablePacketTooBigTimeExceededInvalidParameter"
	_ICMP6Type_name_1 = "EchoRequestEchoReplyMulticastListenerQueryMulticastListenerReportMulticastListenerDoneRouterSolicitationRouterAdvertisementNeighborSolicitationNeighborAdvertisementRedirectMessageRouterRenumberingNodeInformationQueryNodeInformationResponseInverseNeighborDiscoverySolicitationInverseNeighborDiscoveryAdvertisementMulticastListenerDiscoveryHomeAgentAddressDiscoveryRequestHomeAgentAddressDiscoveryReplyMobilePrefixSolicitationMobilePrefixAdvertisementCertificationPathSolicitationCertificationPathAdvertisement"
	_ICMP6Type_name_2 = "MulticastRouterAdvertisementMulticastRouterSolicitationMulticastRouterTermination"
	_ICMP6Type_name_3 = "RPLControlMessage"
)

var (
	_ICMP6Type_index_0 = [...]uint8{0, 22, 34, 46, 62}
	_ICMP6Type_index_1 = [...]uint16{0, 11, 20, 42, 65, 86, 104, 123, 143, 164, 179, 196, 216, 239, 275, 312, 338, 370, 400, 424, 449, 478, 508}
	_ICMP6Type_index_2 = [...]uint8{0, 28, 55, 81}
)

func (i ICMP6Type) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _ICMP6Type_name_0[_ICMP6Type_index_0[i]:_ICMP6Type_index_0[i+1]]
	case 128 <= i && i <= 149:
		i -= 128
		return _ICMP6Type_name_1[_ICMP6Type_index_1[i]:_ICMP6Type_index_1[i+1]]
	case 151 <= i && i <= 153:
		i -= 151
		return _ICMP6Type_name_2[_ICMP6Type_index_2[i]:_ICMP6Type_index_2[i+1]]
	case i == 155:
		return _ICMP6Type_name_3
	default:
		return "ICMP6Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
