// Code generated by "stringer -output=zicmp_time_exceeded_string.go -type=ICMPTimeExceededCode -trimprefix=ICMPTimeExceededCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMPTimeExceededCodeTTL-0]
	_ = x[ICMPTimeExceededCodeFragmentReassembly-1]
}

const _ICMPTimeExceededCode_name = "TTLFragmentReassembly"

var _ICMPTimeExceededCode_index = [...]uint8{0, 3, 21}

func (i ICMPTimeExceededCode) String() string {
	if i >= ICMPTimeExceededCode(len(_ICMPTimeExceededCode_index)-1) {
		return "ICMPTimeExceededCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMPTimeExceededCode_name[_ICMPTimeExceededCode_index[i]:_ICMPTimeExceededCode_index[i+1]]
}
