// Code generated by "stringer -output=zicmp6_unreachable_string.go -type=ICMP6UnreachableCode -trimprefix=ICMP6UnreachableCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMP6UnreachableCodeNoRouteToDestination-0]
	_ = x[ICMP6UnreachableCodeCommunicationAdministrativelyProhibited-1]
	_ = x[ICMP6UnreachableCodeBeyondScopeOfSourceAddress-2]
	_ = x[ICMP6UnreachableCodeAddressUnreachable-3]
	_ = x[ICMP6UnreachableCodePortUnreachable-4]
	_ = x[ICMP6UnreachableCodeSourceAddressFailedIngressOrEgressPolicy-5]
	_ = x[ICMP6UnreachableCodeRejectRouteToDestination-6]
	_ = x[ICMP6UnreachableCodeErrorInSourceRoutingHeader-7]
}

const _ICMP6UnreachableCode_name = "NoRouteToDestinationCommunicationAdministrativelyProhibitedBeyondScopeOfSourceAddressAddressUnreachablePortUnreachableSourceAddressFailedIngressOrEgressPolicyRejectRouteToDestinationErrorInSourceRoutingHeader"

var _ICMP6UnreachableCode_index = [...]uint8{0, 20, 59, 85, 103, 118, 158, 182, 208}

func (i ICMP6UnreachableCode) String() string {
	if i >= ICMP6UnreachableCode(len(_ICMP6UnreachableCode_index)-1) {
		return "ICMP6UnreachableCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMP6UnreachableCode_name[_ICMP6UnreachableCode_index[i]:_ICMP6UnreachableCode_index[i+1]]
}
