// Code generated by "stringer -output=zicmp_redirect_string.go -type=ICMPRedirectCode -trimprefix=ICMPRedirectCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMPRedirectCodeNetwork-0]
	_ = x[ICMPRedirectCodeHost-1]
	_ = x[ICMPRedirectCodeTOSNetwork-2]
	_ = x[ICMPRedirectCodeTOSHost-3]
}

const _ICMPRedirectCode_name = "NetworkHostTOSNetworkTOSHost"

var _ICMPRedirectCode_index = [...]uint8{0, 7, 11, 21, 28}

func (i ICMPRedirectCode) String() string {
	if i >= ICMPRedirectCode(len(_ICMPRedirectCode_index)-1) {
		return "ICMPRedirectCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMPRedirectCode_name[_ICMPRedirectCode_index[i]:_ICMPRedirectCode_index[i+1]]
}
