// Code generated by "stringer -output=zicmp_type_string.go -type=ICMPType -trimprefix=ICMPType ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMPTypeEchoReply-0]
	_ = x[ICMPTypeDestinationUnreachable-3]
	_ = x[ICMPTypeSourceQuench-4]
	_ = x[ICMPTypeRedirectMessage-5]
	_ = x[ICMPTypeEchoRequest-8]
	_ = x[ICMPTypeRouterAdvertisement-9]
	_ = x[ICMPTypeRouterSolicitation-10]
	_ = x[ICMPTypeTimeExceeded-11]
	_ = x[ICMPTypeInvalidParamter-12]
	_ = x[ICMPTypeTimestampRequest-13]
	_ = x[ICMPTypeTimestampReply-14]
	_ = x[ICMPTypeInformationRequest-15]
	_ = x[ICMPTypeInformationReply-16]
	_ = x[ICMPTypeAddressMaskRequest-17]
	_ = x[ICMPTypeAddressMaskReeply-18]
	_ = x[ICMPTypeTraceRoute-30]
	_ = x[ICMPTypeExtendedEchoRequest-42]
	_ = x[ICMPTypeExtendedEchoReply-42]
}

const (
	_ICMPType_name_0 = "EchoReply"
	_ICMPType_name_1 = "DestinationUnreachableSourceQuenchRedirectMessage"
	_ICMPType_name_2 = "EchoRequestRouterAdvertisementRouterSolicitationTimeExceededInvalidParamterTimestampRequestTimestampReplyInformationRequestInformationReplyAddressMaskRequestAddressMaskReeply"
	_ICMPType_name_3 = "TraceRoute"
	_ICMPType_name_4 = "ExtendedEchoRequest"
)

var (
	_ICMPType_index_1 = [...]uint8{0, 22, 34, 49}
	_ICMPType_index_2 = [...]uint8{0, 11, 30, 48, 60, 75, 91, 105, 123, 139, 157, 174}
)

func (i ICMPType) String() string {
	switch {
	case i == 0:
		return _ICMPType_name_0
	case 3 <= i && i <= 5:
		i -= 3
		return _ICMPType_name_1[_ICMPType_index_1[i]:_ICMPType_index_1[i+1]]
	case 8 <= i && i <= 18:
		i -= 8
		return _ICMPType_name_2[_ICMPType_index_2[i]:_ICMPType_index_2[i+1]]
	case i == 30:
		return _ICMPType_name_3
	case i == 42:
		return _ICMPType_name_4
	default:
		return "ICMPType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
