// Code generated by "stringer -output=zicmp6_time_exceeded_string.go -type=ICMP6TimeExceededCode -trimprefix=ICMP6TimeExceededCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMP6TimeExceededCodeTransmitHopLimit-0]
	_ = x[ICMP6TimeExceededCodeFragmentReassembly-1]
}

const _ICMP6TimeExceededCode_name = "TransmitHopLimitFragmentReassembly"

var _ICMP6TimeExceededCode_index = [...]uint8{0, 16, 34}

func (i ICMP6TimeExceededCode) String() string {
	if i >= ICMP6TimeExceededCode(len(_ICMP6TimeExceededCode_index)-1) {
		return "ICMP6TimeExceededCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMP6TimeExceededCode_name[_ICMP6TimeExceededCode_index[i]:_ICMP6TimeExceededCode_index[i+1]]
}
