// Code generated by "stringer -output=zicmp_unreachable_string.go -type=ICMPUnreachableCode -trimprefix=ICMPUnreachableCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMPUnreachableCodeNetworkUnreachable-0]
	_ = x[ICMPUnreachableCodeHostUnreachable-1]
	_ = x[ICMPUnreachableCodeProtocolUnreachable-2]
	_ = x[ICMPUnreachableCodePortUnreachable-3]
	_ = x[ICMPUnreachableCodeFragmentationRequired-4]
	_ = x[ICMPUnreachableCodeSourceRouteFailed-5]
	_ = x[ICMPUnreachableCodeNetworkUnknown-6]
	_ = x[ICMPUnreachableCodeHostUnknown-7]
	_ = x[ICMPUnreachableCodeSourceHostIsolated-8]
	_ = x[ICMPUnreachableCodeNetworkAdministrativelyProhibited-9]
	_ = x[ICMPUnreachableCodeHostAdministrativelyProhibited-10]
	_ = x[ICMPUnreachableCodeTPSNetworkUnreachable-11]
	_ = x[ICMPUnreachableCodeTPSHostUnreachable-12]
	_ = x[ICMPUnreachableCodeCommunicationAdministrativelyProhibited-13]
	_ = x[ICMPUnreachableCodeHostPrecedenceViolation-14]
	_ = x[ICMPUnreachableCodePrecedenceCutoff-15]
}

const _ICMPUnreachableCode_name = "NetworkUnreachableHostUnreachableProtocolUnreachablePortUnreachableFragmentationRequiredSourceRouteFailedNetworkUnknownHostUnknownSourceHostIsolatedNetworkAdministrativelyProhibitedHostAdministrativelyProhibitedTPSNetworkUnreachableTPSHostUnreachableCommunicationAdministrativelyProhibitedHostPrecedenceViolationPrecedenceCutoff"

var _ICMPUnreachableCode_index = [...]uint16{0, 18, 33, 52, 67, 88, 105, 119, 130, 148, 181, 211, 232, 250, 289, 312, 328}

func (i ICMPUnreachableCode) String() string {
	if i >= ICMPUnreachableCode(len(_ICMPUnreachableCode_index)-1) {
		return "ICMPUnreachableCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMPUnreachableCode_name[_ICMPUnreachableCode_index[i]:_ICMPUnreachableCode_index[i+1]]
}
