// Code generated by "stringer -output=zicmp6_router_renumbering_string.go -type=ICMP6RouterRenumberingCode -trimprefix=ICMP6RouterRenumberingCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMP6RouterRenumberingCodeCommand-0]
	_ = x[ICMP6RouterRenumberingCodeResult-1]
}

const _ICMP6RouterRenumberingCode_name = "CommandResult"

var _ICMP6RouterRenumberingCode_index = [...]uint8{0, 7, 13}

func (i ICMP6RouterRenumberingCode) String() string {
	if i >= ICMP6RouterRenumberingCode(len(_ICMP6RouterRenumberingCode_index)-1) {
		return "ICMP6RouterRenumberingCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMP6RouterRenumberingCode_name[_ICMP6RouterRenumberingCode_index[i]:_ICMP6RouterRenumberingCode_index[i+1]]
}
