// Code generated by "stringer -output=zicmp_invalid_parameter_string.go -type=ICMPInvalidParameterCode -trimprefix=ICMPInvalidParameterCode ."; DO NOT EDIT.

package frame

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ICMPInvalidParameterCodePointer-0]
	_ = x[ICMPInvalidParameterCodeMissingOption-1]
	_ = x[ICMPInvalidParameterCodeLength-2]
}

const _ICMPInvalidParameterCode_name = "PointerMissingOptionLength"

var _ICMPInvalidParameterCode_index = [...]uint8{0, 7, 20, 26}

func (i ICMPInvalidParameterCode) String() string {
	if i >= ICMPInvalidParameterCode(len(_ICMPInvalidParameterCode_index)-1) {
		return "ICMPInvalidParameterCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ICMPInvalidParameterCode_name[_ICMPInvalidParameterCode_index[i]:_ICMPInvalidParameterCode_index[i+1]]
}
