// Code generated by "stringer -output=zarphrd_string_linux_arm.go -type=ARPHRD -trimprefix=ARPHRD_ ."; DO NOT EDIT.

package netif

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ARPHRD_ADAPT-264]
	_ = x[ARPHRD_APPLETLK-8]
	_ = x[ARPHRD_ARCNET-7]
	_ = x[ARPHRD_ASH-781]
	_ = x[ARPHRD_ATM-19]
	_ = x[ARPHRD_AX25-3]
	_ = x[ARPHRD_BIF-775]
	_ = x[ARPHRD_CHAOS-5]
	_ = x[ARPHRD_CISCO-513]
	_ = x[ARPHRD_CSLIP-257]
	_ = x[ARPHRD_CSLIP6-259]
	_ = x[ARPHRD_DDCMP-517]
	_ = x[ARPHRD_DLCI-15]
	_ = x[ARPHRD_ECONET-782]
	_ = x[ARPHRD_EETHER-2]
	_ = x[ARPHRD_ETHER-1]
	_ = x[ARPHRD_EUI64-27]
	_ = x[ARPHRD_FCAL-785]
	_ = x[ARPHRD_FCFABRIC-787]
	_ = x[ARPHRD_FCPL-786]
	_ = x[ARPHRD_FCPP-784]
	_ = x[ARPHRD_FDDI-774]
	_ = x[ARPHRD_FRAD-770]
	_ = x[ARPHRD_HDLC-513]
	_ = x[ARPHRD_HIPPI-780]
	_ = x[ARPHRD_HWX25-272]
	_ = x[ARPHRD_IEEE1394-24]
	_ = x[ARPHRD_IEEE802-6]
	_ = x[ARPHRD_IEEE80211-801]
	_ = x[ARPHRD_IEEE80211_PRISM-802]
	_ = x[ARPHRD_IEEE80211_RADIOTAP-803]
	_ = x[ARPHRD_IEEE802154-804]
	_ = x[ARPHRD_IEEE802154_PHY-805]
	_ = x[ARPHRD_IEEE802_TR-800]
	_ = x[ARPHRD_INFINIBAND-32]
	_ = x[ARPHRD_IPDDP-777]
	_ = x[ARPHRD_IPGRE-778]
	_ = x[ARPHRD_IRDA-783]
	_ = x[ARPHRD_LAPB-516]
	_ = x[ARPHRD_LOCALTLK-773]
	_ = x[ARPHRD_LOOPBACK-772]
	_ = x[ARPHRD_METRICOM-23]
	_ = x[ARPHRD_NETROM-0]
	_ = x[ARPHRD_NONE-65534]
	_ = x[ARPHRD_PIMREG-779]
	_ = x[ARPHRD_PPP-512]
	_ = x[ARPHRD_PRONET-4]
	_ = x[ARPHRD_RAWHDLC-518]
	_ = x[ARPHRD_ROSE-270]
	_ = x[ARPHRD_RSRVD-260]
	_ = x[ARPHRD_SIT-776]
	_ = x[ARPHRD_SKIP-771]
	_ = x[ARPHRD_SLIP-256]
	_ = x[ARPHRD_SLIP6-258]
	_ = x[ARPHRD_TUNNEL-768]
	_ = x[ARPHRD_TUNNEL6-769]
	_ = x[ARPHRD_VOID-65535]
	_ = x[ARPHRD_X25-271]
}

const _ARPHRD_name = "NETROMETHEREETHERAX25PRONETCHAOSIEEE802ARCNETAPPLETLKDLCIATMMETRICOMIEEE1394EUI64INFINIBANDSLIPCSLIPSLIP6CSLIP6RSRVDADAPTROSEX25HWX25PPPCISCOLAPBDDCMPRAWHDLCTUNNELTUNNEL6FRADSKIPLOOPBACKLOCALTLKFDDIBIFSITIPDDPIPGREPIMREGHIPPIASHECONETIRDAFCPPFCALFCPLFCFABRICIEEE802_TRIEEE80211IEEE80211_PRISMIEEE80211_RADIOTAPIEEE802154IEEE802154_PHYNONEVOID"

var _ARPHRD_map = map[ARPHRD]string{
	0:     _ARPHRD_name[0:6],
	1:     _ARPHRD_name[6:11],
	2:     _ARPHRD_name[11:17],
	3:     _ARPHRD_name[17:21],
	4:     _ARPHRD_name[21:27],
	5:     _ARPHRD_name[27:32],
	6:     _ARPHRD_name[32:39],
	7:     _ARPHRD_name[39:45],
	8:     _ARPHRD_name[45:53],
	15:    _ARPHRD_name[53:57],
	19:    _ARPHRD_name[57:60],
	23:    _ARPHRD_name[60:68],
	24:    _ARPHRD_name[68:76],
	27:    _ARPHRD_name[76:81],
	32:    _ARPHRD_name[81:91],
	256:   _ARPHRD_name[91:95],
	257:   _ARPHRD_name[95:100],
	258:   _ARPHRD_name[100:105],
	259:   _ARPHRD_name[105:111],
	260:   _ARPHRD_name[111:116],
	264:   _ARPHRD_name[116:121],
	270:   _ARPHRD_name[121:125],
	271:   _ARPHRD_name[125:128],
	272:   _ARPHRD_name[128:133],
	512:   _ARPHRD_name[133:136],
	513:   _ARPHRD_name[136:141],
	516:   _ARPHRD_name[141:145],
	517:   _ARPHRD_name[145:150],
	518:   _ARPHRD_name[150:157],
	768:   _ARPHRD_name[157:163],
	769:   _ARPHRD_name[163:170],
	770:   _ARPHRD_name[170:174],
	771:   _ARPHRD_name[174:178],
	772:   _ARPHRD_name[178:186],
	773:   _ARPHRD_name[186:194],
	774:   _ARPHRD_name[194:198],
	775:   _ARPHRD_name[198:201],
	776:   _ARPHRD_name[201:204],
	777:   _ARPHRD_name[204:209],
	778:   _ARPHRD_name[209:214],
	779:   _ARPHRD_name[214:220],
	780:   _ARPHRD_name[220:225],
	781:   _ARPHRD_name[225:228],
	782:   _ARPHRD_name[228:234],
	783:   _ARPHRD_name[234:238],
	784:   _ARPHRD_name[238:242],
	785:   _ARPHRD_name[242:246],
	786:   _ARPHRD_name[246:250],
	787:   _ARPHRD_name[250:258],
	800:   _ARPHRD_name[258:268],
	801:   _ARPHRD_name[268:277],
	802:   _ARPHRD_name[277:292],
	803:   _ARPHRD_name[292:310],
	804:   _ARPHRD_name[310:320],
	805:   _ARPHRD_name[320:334],
	65534: _ARPHRD_name[334:338],
	65535: _ARPHRD_name[338:342],
}

func (i ARPHRD) String() string {
	if str, ok := _ARPHRD_map[i]; ok {
		return str
	}
	return "ARPHRD(" + strconv.FormatInt(int64(i), 10) + ")"
}
