// Code generated by "stringer -output=ziff_string_darwin_amd64.go -type=IFF -trimprefix=IFF_ ."; DO NOT EDIT.

package netif

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IFF_ALLMULTI-512]
	_ = x[IFF_ALTPHYS-16384]
	_ = x[IFF_BROADCAST-2]
	_ = x[IFF_DEBUG-4]
	_ = x[IFF_LINK0-4096]
	_ = x[IFF_LINK1-8192]
	_ = x[IFF_LINK2-16384]
	_ = x[IFF_LOOPBACK-8]
	_ = x[IFF_MULTICAST-32768]
	_ = x[IFF_NOARP-128]
	_ = x[IFF_NOTRAILERS-32]
	_ = x[IFF_OACTIVE-1024]
	_ = x[IFF_POINTOPOINT-16]
	_ = x[IFF_PROMISC-256]
	_ = x[IFF_RUNNING-64]
	_ = x[IFF_SIMPLEX-2048]
	_ = x[IFF_UP-1]
}

const _IFF_name = "UPBROADCASTDEBUGLOOPBACKPOINTOPOINTNOTRAILERSRUNNINGNOARPPROMISCALLMULTIOACTIVESIMPLEXLINK0LINK1ALTPHYSMULTICAST"

var _IFF_map = map[IFF]string{
	1:     _IFF_name[0:2],
	2:     _IFF_name[2:11],
	4:     _IFF_name[11:16],
	8:     _IFF_name[16:24],
	16:    _IFF_name[24:35],
	32:    _IFF_name[35:45],
	64:    _IFF_name[45:52],
	128:   _IFF_name[52:57],
	256:   _IFF_name[57:64],
	512:   _IFF_name[64:72],
	1024:  _IFF_name[72:79],
	2048:  _IFF_name[79:86],
	4096:  _IFF_name[86:91],
	8192:  _IFF_name[91:96],
	16384: _IFF_name[96:103],
	32768: _IFF_name[103:112],
}

func (i IFF) String() string {
	if str, ok := _IFF_map[i]; ok {
		return str
	}
	return "IFF(" + strconv.FormatInt(int64(i), 10) + ")"
}
