// Code generated by "stringer -output=ziff_string_linux_arm64.go -type=IFF -trimprefix=IFF_ ."; DO NOT EDIT.

package netif

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IFF_802_1Q_VLAN-1]
	_ = x[IFF_ALLMULTI-512]
	_ = x[IFF_ATTACH_QUEUE-512]
	_ = x[IFF_AUTOMEDIA-16384]
	_ = x[IFF_BONDING-32]
	_ = x[IFF_BRIDGE_PORT-16384]
	_ = x[IFF_BROADCAST-2]
	_ = x[IFF_DEBUG-4]
	_ = x[IFF_DETACH_QUEUE-1024]
	_ = x[IFF_DISABLE_NETPOLL-4096]
	_ = x[IFF_DONT_BRIDGE-2048]
	_ = x[IFF_DORMANT-131072]
	_ = x[IFF_DYNAMIC-32768]
	_ = x[IFF_EBRIDGE-2]
	_ = x[IFF_ECHO-262144]
	_ = x[IFF_ISATAP-128]
	_ = x[IFF_LIVE_ADDR_CHANGE-1048576]
	_ = x[IFF_LOOPBACK-8]
	_ = x[IFF_LOWER_UP-65536]
	_ = x[IFF_MACVLAN-2097152]
	_ = x[IFF_MACVLAN_PORT-8192]
	_ = x[IFF_MASTER-1024]
	_ = x[IFF_MASTER_8023AD-8]
	_ = x[IFF_MASTER_ALB-16]
	_ = x[IFF_MASTER_ARPMON-256]
	_ = x[IFF_MULTICAST-4096]
	_ = x[IFF_MULTI_QUEUE-256]
	_ = x[IFF_NOARP-128]
	_ = x[IFF_NOFILTER-4096]
	_ = x[IFF_NOTRAILERS-32]
	_ = x[IFF_NO_PI-4096]
	_ = x[IFF_ONE_QUEUE-8192]
	_ = x[IFF_OVS_DATAPATH-32768]
	_ = x[IFF_PERSIST-2048]
	_ = x[IFF_POINTOPOINT-16]
	_ = x[IFF_PORTSEL-8192]
	_ = x[IFF_PROMISC-256]
	_ = x[IFF_RUNNING-64]
	_ = x[IFF_SLAVE-2048]
	_ = x[IFF_SLAVE_INACTIVE-4]
	_ = x[IFF_SLAVE_NEEDARP-64]
	_ = x[IFF_SUPP_NOFCS-524288]
	_ = x[IFF_TAP-2]
	_ = x[IFF_TEAM_PORT-262144]
	_ = x[IFF_TUN-1]
	_ = x[IFF_TUN_EXCL-32768]
	_ = x[IFF_TX_SKB_SHARING-65536]
	_ = x[IFF_UNICAST_FLT-131072]
	_ = x[IFF_UP-1]
	_ = x[IFF_VNET_HDR-16384]
	_ = x[IFF_VOLATILE-461914]
	_ = x[IFF_WAN_HDLC-512]
	_ = x[IFF_XMIT_DST_RELEASE-1024]
}

const _IFF_name = "802_1Q_VLANBROADCASTDEBUGLOOPBACKMASTER_ALBBONDINGRUNNINGISATAPMASTER_ARPMONALLMULTIDETACH_QUEUEDONT_BRIDGEDISABLE_NETPOLLMACVLAN_PORTAUTOMEDIADYNAMICLOWER_UPDORMANTECHOVOLATILESUPP_NOFCSLIVE_ADDR_CHANGEMACVLAN"

var _IFF_map = map[IFF]string{
	1:       _IFF_name[0:11],
	2:       _IFF_name[11:20],
	4:       _IFF_name[20:25],
	8:       _IFF_name[25:33],
	16:      _IFF_name[33:43],
	32:      _IFF_name[43:50],
	64:      _IFF_name[50:57],
	128:     _IFF_name[57:63],
	256:     _IFF_name[63:76],
	512:     _IFF_name[76:84],
	1024:    _IFF_name[84:96],
	2048:    _IFF_name[96:107],
	4096:    _IFF_name[107:122],
	8192:    _IFF_name[122:134],
	16384:   _IFF_name[134:143],
	32768:   _IFF_name[143:150],
	65536:   _IFF_name[150:158],
	131072:  _IFF_name[158:165],
	262144:  _IFF_name[165:169],
	461914:  _IFF_name[169:177],
	524288:  _IFF_name[177:187],
	1048576: _IFF_name[187:203],
	2097152: _IFF_name[203:210],
}

func (i IFF) String() string {
	if str, ok := _IFF_map[i]; ok {
		return str
	}
	return "IFF(" + strconv.FormatInt(int64(i), 10) + ")"
}
