// Code generated by "stringer -output=ziff_string_linux_riscv64.go -type=IFF -trimprefix=IFF_ ."; DO NOT EDIT.

package netif

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IFF_ALLMULTI-512]
	_ = x[IFF_ATTACH_QUEUE-512]
	_ = x[IFF_AUTOMEDIA-16384]
	_ = x[IFF_BROADCAST-2]
	_ = x[IFF_DEBUG-4]
	_ = x[IFF_DETACH_QUEUE-1024]
	_ = x[IFF_DORMANT-131072]
	_ = x[IFF_DYNAMIC-32768]
	_ = x[IFF_ECHO-262144]
	_ = x[IFF_LOOPBACK-8]
	_ = x[IFF_LOWER_UP-65536]
	_ = x[IFF_MASTER-1024]
	_ = x[IFF_MULTICAST-4096]
	_ = x[IFF_MULTI_QUEUE-256]
	_ = x[IFF_NOARP-128]
	_ = x[IFF_NOFILTER-4096]
	_ = x[IFF_NOTRAILERS-32]
	_ = x[IFF_NO_PI-4096]
	_ = x[IFF_ONE_QUEUE-8192]
	_ = x[IFF_PERSIST-2048]
	_ = x[IFF_POINTOPOINT-16]
	_ = x[IFF_PORTSEL-8192]
	_ = x[IFF_PROMISC-256]
	_ = x[IFF_RUNNING-64]
	_ = x[IFF_SLAVE-2048]
	_ = x[IFF_TAP-2]
	_ = x[IFF_TUN-1]
	_ = x[IFF_TUN_EXCL-32768]
	_ = x[IFF_UP-1]
	_ = x[IFF_VNET_HDR-16384]
	_ = x[IFF_VOLATILE-461914]
}

const _IFF_name = "TUNBROADCASTDEBUGLOOPBACKPOINTOPOINTNOTRAILERSRUNNINGNOARPMULTI_QUEUEALLMULTIDETACH_QUEUEPERSISTMULTICASTONE_QUEUEAUTOMEDIADYNAMICLOWER_UPDORMANTECHOVOLATILE"

var _IFF_map = map[IFF]string{
	1:      _IFF_name[0:3],
	2:      _IFF_name[3:12],
	4:      _IFF_name[12:17],
	8:      _IFF_name[17:25],
	16:     _IFF_name[25:36],
	32:     _IFF_name[36:46],
	64:     _IFF_name[46:53],
	128:    _IFF_name[53:58],
	256:    _IFF_name[58:69],
	512:    _IFF_name[69:77],
	1024:   _IFF_name[77:89],
	2048:   _IFF_name[89:96],
	4096:   _IFF_name[96:105],
	8192:   _IFF_name[105:114],
	16384:  _IFF_name[114:123],
	32768:  _IFF_name[123:130],
	65536:  _IFF_name[130:138],
	131072: _IFF_name[138:145],
	262144: _IFF_name[145:149],
	461914: _IFF_name[149:157],
}

func (i IFF) String() string {
	if str, ok := _IFF_map[i]; ok {
		return str
	}
	return "IFF(" + strconv.FormatInt(int64(i), 10) + ")"
}
