// Code generated by "stringer -type=DeviceClass,VendorID"; DO NOT EDIT

package pci

import "fmt"

const _DeviceClass_name = "UndefinedUndefined_VGAStorage_SCSIStorage_IDEStorage_FloppyStorage_IPIStorage_RAIDStorage_SATAStorage_SASStorage_OtherNetwork_EthernetNetwork_Token_RingNetwork_FDDINetwork_ATMNetwork_OtherDisplay_VGADisplay_XGADisplay_3DDisplay_OtherMultimedia_VideoMultimedia_AudioMultimedia_PhoneMultimedia_Audio_DeviceMultimedia_OtherMemory_RAMMemory_FlashMemory_OtherBridge_HostBridge_ISABridge_EISABridge_MCBridge_PCIBridge_PCMCIABridge_NUBUSBridge_CARDBUSBridge_RACEWAYBridge_OtherCommunication_SerialCommunication_ParallelCommunication_Multi_SerialCommunication_ModemCommunication_OtherSystem_PICSystem_DMASystem_TimerSystem_RTCSystem_PCI_HotplugSystem_SDHCISystem_OtherInput_KeyboardInput_PenInput_MouseInput_ScannerInput_GAMEPORTInput_OtherDocking_GENERICDocking_OtherProcessor_386Processor_486Processor_PentiumProcessor_AlphaProcessor_PowerpcProcessor_MIPSProcessor_COSerial_FirewireSerial_AccessSerial_SSASerial_USBSerial_FiberSerial_SMBUSWireless_RF_ControllerIntelligent_I2OSatellite_TVSatellite_AudioSatellite_VoiceSatellite_DataCrypt_NetworkCrypt_entertainmentCrypt_OtherSP_DPIOSP_Other"

var _DeviceClass_map = map[DeviceClass]string{
	0:    _DeviceClass_name[0:9],
	1:    _DeviceClass_name[9:22],
	256:  _DeviceClass_name[22:34],
	257:  _DeviceClass_name[34:45],
	258:  _DeviceClass_name[45:59],
	259:  _DeviceClass_name[59:70],
	260:  _DeviceClass_name[70:82],
	262:  _DeviceClass_name[82:94],
	263:  _DeviceClass_name[94:105],
	384:  _DeviceClass_name[105:118],
	512:  _DeviceClass_name[118:134],
	513:  _DeviceClass_name[134:152],
	514:  _DeviceClass_name[152:164],
	515:  _DeviceClass_name[164:175],
	640:  _DeviceClass_name[175:188],
	768:  _DeviceClass_name[188:199],
	769:  _DeviceClass_name[199:210],
	770:  _DeviceClass_name[210:220],
	896:  _DeviceClass_name[220:233],
	1024: _DeviceClass_name[233:249],
	1025: _DeviceClass_name[249:265],
	1026: _DeviceClass_name[265:281],
	1027: _DeviceClass_name[281:304],
	1152: _DeviceClass_name[304:320],
	1280: _DeviceClass_name[320:330],
	1281: _DeviceClass_name[330:342],
	1408: _DeviceClass_name[342:354],
	1536: _DeviceClass_name[354:365],
	1537: _DeviceClass_name[365:375],
	1538: _DeviceClass_name[375:386],
	1539: _DeviceClass_name[386:395],
	1540: _DeviceClass_name[395:405],
	1541: _DeviceClass_name[405:418],
	1542: _DeviceClass_name[418:430],
	1543: _DeviceClass_name[430:444],
	1544: _DeviceClass_name[444:458],
	1664: _DeviceClass_name[458:470],
	1792: _DeviceClass_name[470:490],
	1793: _DeviceClass_name[490:512],
	1794: _DeviceClass_name[512:538],
	1795: _DeviceClass_name[538:557],
	1920: _DeviceClass_name[557:576],
	2048: _DeviceClass_name[576:586],
	2049: _DeviceClass_name[586:596],
	2050: _DeviceClass_name[596:608],
	2051: _DeviceClass_name[608:618],
	2052: _DeviceClass_name[618:636],
	2053: _DeviceClass_name[636:648],
	2176: _DeviceClass_name[648:660],
	2304: _DeviceClass_name[660:674],
	2305: _DeviceClass_name[674:683],
	2306: _DeviceClass_name[683:694],
	2307: _DeviceClass_name[694:707],
	2308: _DeviceClass_name[707:721],
	2432: _DeviceClass_name[721:732],
	2560: _DeviceClass_name[732:747],
	2688: _DeviceClass_name[747:760],
	2816: _DeviceClass_name[760:773],
	2817: _DeviceClass_name[773:786],
	2818: _DeviceClass_name[786:803],
	2832: _DeviceClass_name[803:818],
	2848: _DeviceClass_name[818:835],
	2864: _DeviceClass_name[835:849],
	2880: _DeviceClass_name[849:861],
	3072: _DeviceClass_name[861:876],
	3073: _DeviceClass_name[876:889],
	3074: _DeviceClass_name[889:899],
	3075: _DeviceClass_name[899:909],
	3076: _DeviceClass_name[909:921],
	3077: _DeviceClass_name[921:933],
	3344: _DeviceClass_name[933:955],
	3584: _DeviceClass_name[955:970],
	3840: _DeviceClass_name[970:982],
	3841: _DeviceClass_name[982:997],
	3843: _DeviceClass_name[997:1012],
	3844: _DeviceClass_name[1012:1026],
	4096: _DeviceClass_name[1026:1039],
	4097: _DeviceClass_name[1039:1058],
	4224: _DeviceClass_name[1058:1069],
	4352: _DeviceClass_name[1069:1076],
	4480: _DeviceClass_name[1076:1084],
}

func (i DeviceClass) String() string {
	if str, ok := _DeviceClass_map[i]; ok {
		return str
	}
	return fmt.Sprintf("DeviceClass(%d)", i)
}

const (
	_VendorID_name_0 = "Broadcom"
	_VendorID_name_1 = "Intel"
)

var (
	_VendorID_index_0 = [...]uint8{0, 8}
	_VendorID_index_1 = [...]uint8{0, 5}
)

func (i VendorID) String() string {
	switch {
	case i == 5348:
		return _VendorID_name_0
	case i == 32902:
		return _VendorID_name_1
	default:
		return fmt.Sprintf("VendorID(%d)", i)
	}
}
