// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=unix -id ifVec -d VecType=interfaceVec -d Type=*tuntap_interface github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unix

import (
	"github.com/platinasystems/go/elib"
)

type interfaceVec []*tuntap_interface

func (p *interfaceVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*tuntap_interface, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *interfaceVec) validate(new_len uint, zero *tuntap_interface) **tuntap_interface {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *interfaceVec) validateSlowPath(zero *tuntap_interface, c, l, lʹ elib.Index) **tuntap_interface {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*tuntap_interface, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *interfaceVec) Validate(i uint) **tuntap_interface {
	var zero *tuntap_interface
	return p.validate(i+1, zero)
}

func (p *interfaceVec) ValidateInit(i uint, zero *tuntap_interface) **tuntap_interface {
	return p.validate(i+1, zero)
}

func (p *interfaceVec) ValidateLen(l uint) (v **tuntap_interface) {
	if l > 0 {
		var zero *tuntap_interface
		v = p.validate(l, zero)
	}
	return
}

func (p *interfaceVec) ValidateLenInit(l uint, zero *tuntap_interface) (v **tuntap_interface) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p interfaceVec) Len() uint { return uint(len(p)) }
