// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=unix -id iovec -d VecType=iovecVec -d Type=iovec github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package unix

import (
	"github.com/platinasystems/go/elib"
)

type iovecVec []iovec

func (p *iovecVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]iovec, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *iovecVec) validate(new_len uint, zero iovec) *iovec {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *iovecVec) validateSlowPath(zero iovec, old_cap, new_len, old_len uint) *iovec {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]iovec, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *iovecVec) Validate(i uint) *iovec {
	var zero iovec
	return p.validate(i+1, zero)
}

func (p *iovecVec) ValidateInit(i uint, zero iovec) *iovec {
	return p.validate(i+1, zero)
}

func (p *iovecVec) ValidateLen(l uint) (v *iovec) {
	if l > 0 {
		var zero iovec
		v = p.validate(l, zero)
	}
	return
}

func (p *iovecVec) ValidateLenInit(l uint, zero iovec) (v *iovec) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *iovecVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p iovecVec) Len() uint { return uint(len(p)) }
