// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=unix -id ifVec -d VecType=interfaceVec -d Type=*Interface github.com/platinasystems/go/elib/vec.tmpl]

package unix

import (
	"github.com/platinasystems/go/elib"
)

type interfaceVec []*Interface

func (p *interfaceVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*Interface, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *interfaceVec) validate(new_len uint, zero **Interface) **Interface {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *interfaceVec) validateSlowPath(zero **Interface,
	c, l, lʹ elib.Index) **Interface {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]*Interface, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *interfaceVec) Validate(i uint) **Interface {
	return p.validate(i+1, (**Interface)(nil))
}

func (p *interfaceVec) ValidateInit(i uint, zero *Interface) **Interface {
	return p.validate(i+1, &zero)
}

func (p *interfaceVec) ValidateLen(l uint) (v **Interface) {
	if l > 0 {
		v = p.validate(l, (**Interface)(nil))
	}
	return
}

func (p *interfaceVec) ValidateLenInit(l uint, zero *Interface) (v **Interface) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p interfaceVec) Len() uint { return uint(len(p)) }
