// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id pollerElogEvent -d Type=pollerElogEvent github.com/platinasystems/go/elib/elog/event.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package loop

import (
	"github.com/platinasystems/go/elib/elog"
)

var pollerElogEventType = &elog.EventType{
	Name: "loop.pollerElogEvent",
}

func init() {
	t := pollerElogEventType
	t.Strings = stringer_pollerElogEvent
	t.Encode = encode_pollerElogEvent
	t.Decode = decode_pollerElogEvent
	elog.RegisterType(pollerElogEventType)
}

func stringer_pollerElogEvent(c *elog.Context, e *elog.Event) []string {
	var x pollerElogEvent
	x.Decode(c, e.Data[:])
	return x.Strings(c)
}

func encode_pollerElogEvent(c *elog.Context, e *elog.Event, b []byte) int {
	var x pollerElogEvent
	x.Decode(c, e.Data[:])
	return x.Encode(c, b)
}

func decode_pollerElogEvent(c *elog.Context, e *elog.Event, b []byte) int {
	var x pollerElogEvent
	x.Decode(c, b)
	return x.Encode(c, e.Data[:])
}

func (x pollerElogEvent) log_pollerElogEvent(b *elog.Buffer, r elog.Caller) {
	e := b.Add(pollerElogEventType, r)
	x.Encode(b.GetContext(), e.Data[:])
}

func (x pollerElogEvent) Log() {
	r := elog.GetCaller(elog.PointerToFirstArg(&x))
	x.log_pollerElogEvent(elog.DefaultBuffer, r)
}

func (x pollerElogEvent) Logc(r elog.Caller) {
	x.log_pollerElogEvent(elog.DefaultBuffer, r)
}

func (x pollerElogEvent) Logb(b *elog.Buffer) {
	r := elog.GetCaller(elog.PointerToFirstArg(&x))
	x.log_pollerElogEvent(b, r)
}

func (x pollerElogEvent) Logbc(b *elog.Buffer, r elog.Caller) {
	x.log_pollerElogEvent(b, r)
}
