// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id activePoller -d PoolType=activePollerPool -d Type=*activePoller -d Data=entries github.com/platinasystems/go/elib/pool.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package loop

import (
	"github.com/platinasystems/go/elib"
)

type activePollerPool struct {
	elib.Pool
	entries []*activePoller
}

func (p *activePollerPool) GetIndex() (i uint) {
	l := uint(len(p.entries))
	i = p.Pool.GetIndex(l)
	if i >= l {
		p.Validate(i)
	}
	return i
}

func (p *activePollerPool) PutIndex(i uint) (ok bool) {
	return p.Pool.PutIndex(i)
}

func (p *activePollerPool) IsFree(i uint) (v bool) {
	v = i >= uint(len(p.entries))
	if !v {
		v = p.Pool.IsFree(i)
	}
	return
}

func (p *activePollerPool) Resize(n uint) {
	c := elib.Index(cap(p.entries))
	l := elib.Index(len(p.entries) + int(n))
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*activePoller, l, c)
		copy(q, p.entries)
		p.entries = q
	}
	p.entries = p.entries[:l]
}

func (p *activePollerPool) Validate(i uint) {
	c := elib.Index(cap(p.entries))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]*activePoller, l, c)
		copy(q, p.entries)
		p.entries = q
	}
	if l > elib.Index(len(p.entries)) {
		p.entries = p.entries[:l]
	}
}

func (p *activePollerPool) Elts() uint {
	return uint(len(p.entries)) - p.FreeLen()
}

func (p *activePollerPool) Len() uint {
	return uint(len(p.entries))
}

func (p *activePollerPool) Foreach(f func(x *activePoller)) {
	for i := range p.entries {
		if !p.Pool.IsFree(uint(i)) {
			f(p.entries[i])
		}
	}
}

func (p *activePollerPool) ForeachIndex(f func(i uint)) {
	for i := range p.entries {
		if !p.Pool.IsFree(uint(i)) {
			f(uint(i))
		}
	}
}

func (p *activePollerPool) Reset() {
	p.Pool.Reset()
	if len(p.entries) > 0 {
		p.entries = p.entries[:0]
	}
}
