// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id looperIn -d VecType=looperInVec -d Type=LooperIn github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package loop

import (
	"github.com/platinasystems/go/elib"
)

type looperInVec []LooperIn

func (p *looperInVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]LooperIn, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *looperInVec) validate(new_len uint, zero LooperIn) *LooperIn {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *looperInVec) validateSlowPath(zero LooperIn, c, l, lʹ elib.Index) *LooperIn {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]LooperIn, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *looperInVec) Validate(i uint) *LooperIn {
	var zero LooperIn
	return p.validate(i+1, zero)
}

func (p *looperInVec) ValidateInit(i uint, zero LooperIn) *LooperIn {
	return p.validate(i+1, zero)
}

func (p *looperInVec) ValidateLen(l uint) (v *LooperIn) {
	if l > 0 {
		var zero LooperIn
		v = p.validate(l, zero)
	}
	return
}

func (p *looperInVec) ValidateLenInit(l uint, zero LooperIn) (v *LooperIn) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *looperInVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p looperInVec) Len() uint { return uint(len(p)) }
