// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=loop -id nextNode -d VecType=nextNodeVec -d Type=nextNode github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package loop

import (
	"github.com/platinasystems/go/elib"
)

type nextNodeVec []nextNode

func (p *nextNodeVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]nextNode, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *nextNodeVec) validate(new_len uint, zero nextNode) *nextNode {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *nextNodeVec) validateSlowPath(zero nextNode, old_cap, new_len, old_len uint) *nextNode {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]nextNode, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *nextNodeVec) Validate(i uint) *nextNode {
	var zero nextNode
	return p.validate(i+1, zero)
}

func (p *nextNodeVec) ValidateInit(i uint, zero nextNode) *nextNode {
	return p.validate(i+1, zero)
}

func (p *nextNodeVec) ValidateLen(l uint) (v *nextNode) {
	if l > 0 {
		var zero nextNode
		v = p.validate(l, zero)
	}
	return
}

func (p *nextNodeVec) ValidateLenInit(l uint, zero nextNode) (v *nextNode) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *nextNodeVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p nextNodeVec) Len() uint { return uint(len(p)) }
