// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=packet -id RxDescriptor -d Type=RxDescriptor -d VecType=RxDescriptorVec github.com/platinasystems/go/elib/hw/dma_mem.tmpl]

package packet

import (
	"github.com/platinasystems/go/elib"
	"github.com/platinasystems/go/elib/hw"

	"reflect"
	"unsafe"
)

type RxDescriptorVec []RxDescriptor

func fromByteSlice_RxDescriptor(b []byte, l, c uint) (x RxDescriptorVec) {
	s := uint(unsafe.Sizeof(x[0]))
	if l == 0 {
		l = uint(len(b)) / s
		c = uint(cap(b))
	}
	return *(*RxDescriptorVec)(unsafe.Pointer(&reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(&b[0])),
		Len:  int(l),
		Cap:  int(c / s),
	}))
}

func (x RxDescriptorVec) toByteSlice() []byte {
	l := uint(len(x))
	l *= uint(unsafe.Sizeof(x[0]))
	return *(*[]byte)(unsafe.Pointer(&reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(&x[0])),
		Len:  int(l),
		Cap:  int(l)}))
}

func RxDescriptorAllocAligned(n, a uint) (x RxDescriptorVec, id elib.Index) {
	var b []byte
	var c uint
	b, id, _, c = hw.DmaAllocAligned(n*uint(unsafe.Sizeof(x[0])), a)
	x = fromByteSlice_RxDescriptor(b, n, c)
	return
}

func RxDescriptorAlloc(n uint) (x RxDescriptorVec, id elib.Index) {
	return RxDescriptorAllocAligned(n, 0)
}

func RxDescriptorNew() (x RxDescriptorVec, id elib.Index) { return RxDescriptorAlloc(1) }

func (x *RxDescriptorVec) Free(id elib.Index) {
	hw.DmaFree(id)
	*x = nil
}

func (x *RxDescriptorVec) Get(id elib.Index) {
	*x = fromByteSlice_RxDescriptor(hw.DmaGetData(id), 0, 0)
}

func (x *RxDescriptor) PhysAddress() uintptr {
	return hw.DmaPhysAddress(uintptr(unsafe.Pointer(x)))
}
