// Copyright © 2023-2024 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the BSD-style license
// described in the golang/LICENSE file.

package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const usage = `
textembedder <pattern>.txt...
Generate source to embed text.

- The generated package name is either the last element of the input path
  or the basename preface up to the first underscore.
- The generated output is written to ${input/.txt/.go}

Options`

var dryrun = flag.Bool("n", false, "Print, don't save generate source.")
var verbose = flag.Bool("v", false, "Print generated file names.")
var tags = flag.String("tags", "",
	"Build contraints added to generated file.")
var name = flag.String("name", "Text", "Emdedded string name.")

var tt = template.Must(template.New("embed text").Parse(`
// Code generated by "textembedder"; DO NOT EDIT.

{{if .Tags}}//go:build {{.Tags}}
{{end}}package {{.Package}}

import _ "embed"

//go:embed {{.File}}
var {{.Name}} string
`[1:]))

func fatal(args ...any) {
	w := flag.CommandLine.Output()
	fmt.Fprint(w, filepath.Base(flag.CommandLine.Name()), ": ")
	fmt.Fprint(w, args...)
	os.Exit(1)
}

func main() {
	clo := flag.CommandLine.Output()
	w := clo
	klose := func() error {
		return nil
	}
	flag.Usage = func() {
		fmt.Fprintf(clo, usage[1:])
		flag.PrintDefaults()
	}
	flag.Parse()
	if flag.NArg() == 0 {
		fatal("no input")
	}
	for _, pattern := range flag.Args() {
		inputs, err := filepath.Glob(pattern)
		if err != nil {
			fatal(err)
		}
		for _, input := range inputs {
			var pkg string
			dir, base := filepath.Dir(input), filepath.Base(input)
			output := strings.Replace(input, ".txt", ".go", 1)
			if dir == "." {
				underscore := strings.Index(base, "_")
				if underscore < 0 {
					fatal("can't derive package from ",
						input)
				}
				pkg = base[:underscore]
			} else {
				pkg = filepath.Base(dir)
			}
			if *dryrun {
				fmt.Fprintln(clo, "---", output)
			} else if f, err := os.Create(output); err != nil {
				fatal(err)
			} else {
				klose = f.Close
				w = f
			}
			err = tt.Execute(w, struct {
				Package, Tags, File, Name string
			}{
				Package: pkg,
				Tags:    *tags,
				File:    base,
				Name:    *name,
			})
			klose()
			if err != nil {
				fatal(err)
			}
			if *verbose {
				fmt.Fprintln(clo, "Generated", output)
			}
		}
	}
}
