// SPDX-License-Identifier: GPL-2.0+ WITH Linux-syscall-note

package ifarp

import "github.com/platinasystems/goes/v2/pkg/encoding/binary/big"

//go:generate stringer -output=zarphrd_string.go -type=ARPHRD -trimprefix=ARPHRD_ .

type ARPHRD uint16

const (
	ARPHRD_NETROM     ARPHRD = 0
	ARPHRD_ETHER      ARPHRD = 1
	ARPHRD_EETHER     ARPHRD = 2
	ARPHRD_AX25       ARPHRD = 3
	ARPHRD_PRONET     ARPHRD = 4
	ARPHRD_CHAOS      ARPHRD = 5
	ARPHRD_IEEE802    ARPHRD = 6
	ARPHRD_ARCNET     ARPHRD = 7
	ARPHRD_APPLETLK   ARPHRD = 8
	ARPHRD_DLCI       ARPHRD = 15
	ARPHRD_ATM        ARPHRD = 19
	ARPHRD_METRICOM   ARPHRD = 23
	ARPHRD_IEEE1394   ARPHRD = 24
	ARPHRD_EUI64      ARPHRD = 27
	ARPHRD_INFINIBAND ARPHRD = 32

	ARPHRD_SLIP    ARPHRD = 256 + iota
	ARPHRD_CSLIP   ARPHRD = 257
	ARPHRD_SLIP6   ARPHRD = 258
	ARPHRD_CSLIP6  ARPHRD = 259
	ARPHRD_RSRVD   ARPHRD = 260
	ARPHRD_ADAPT   ARPHRD = 264
	ARPHRD_ROSE    ARPHRD = 270
	ARPHRD_X25     ARPHRD = 271
	ARPHRD_HWX25   ARPHRD = 272
	ARPHRD_CAN     ARPHRD = 280
	ARPHRD_MCTP    ARPHRD = 290
	ARPHRD_PPP     ARPHRD = 512
	ARPHRD_CISCO   ARPHRD = 513
	ARPHRD_HDLC           = ARPHRD_CISCO
	ARPHRD_LAPB    ARPHRD = 516
	ARPHRD_DDCMP   ARPHRD = 517
	ARPHRD_RAWHDLC ARPHRD = 518
	ARPHRD_RAWIP   ARPHRD = 519

	ARPHRD_TUNNEL   ARPHRD = 768
	ARPHRD_TUNNEL6  ARPHRD = 769
	ARPHRD_FRAD     ARPHRD = 770
	ARPHRD_SKIP     ARPHRD = 771
	ARPHRD_LOOPBACK ARPHRD = 772
	ARPHRD_LOCALTLK ARPHRD = 773
	ARPHRD_FDDI     ARPHRD = 774
	ARPHRD_BIF      ARPHRD = 775
	ARPHRD_SIT      ARPHRD = 776
	ARPHRD_IPDDP    ARPHRD = 777
	ARPHRD_IPGRE    ARPHRD = 778
	ARPHRD_PIMREG   ARPHRD = 779
	ARPHRD_HIPPI    ARPHRD = 780
	ARPHRD_ASH      ARPHRD = 781
	ARPHRD_ECONET   ARPHRD = 782
	ARPHRD_IRDA     ARPHRD = 783

	ARPHRD_FCPP     ARPHRD = 784
	ARPHRD_FCAL     ARPHRD = 785
	ARPHRD_FCPL     ARPHRD = 786
	ARPHRD_FCFABRIC ARPHRD = 787

	ARPHRD_IEEE802_TR         ARPHRD = 800
	ARPHRD_IEEE80211          ARPHRD = 801
	ARPHRD_IEEE80211_PRISM    ARPHRD = 802
	ARPHRD_IEEE80211_RADIOTAP ARPHRD = 803
	ARPHRD_IEEE802154         ARPHRD = 804
	ARPHRD_IEEE802154_MONITOR ARPHRD = 805

	ARPHRD_PHONET      ARPHRD = 820
	ARPHRD_PHONET_PIPE ARPHRD = 821
	ARPHRD_CAIF        ARPHRD = 822
	ARPHRD_IP6GRE      ARPHRD = 823
	ARPHRD_NETLINK     ARPHRD = 824
	ARPHRD_6LOWPAN     ARPHRD = 825
	ARPHRD_VSOCKMON    ARPHRD = 826

	ARPHRD_VOID ARPHRD = 0
	ARPHRD_NONE ARPHRD = 0
)

const (
	ARPOP_REQUEST   = 1
	ARPOP_REPLY     = 2
	ARPOP_RREQUEST  = 3
	ARPOP_RREPLY    = 4
	ARPOP_InREQUEST = 8
	ARPOP_InREPLY   = 9
	ARPOP_NAK       = 10
)

const (
	ATF_COM         = 0x02
	ATF_PERM        = 0x04
	ATF_PUBL        = 0x08
	ATF_USETRAILERS = 0x10
	ATF_NETMASK     = 0x20
	ATF_DONTPUB     = 0x40
)

type ArpHdr struct {
	HRD big.Uint16
	PRO big.Uint16
	HLN uint8
	PLN uint8
	OP  big.Uint16
}
