// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=packet -id TxDescriptor -d Type=TxDescriptor -d VecType=TxDescriptorVec github.com/platinasystems/go/elib/hw/dma_mem.tmpl]

package packet

import (
	"github.com/platinasystems/go/elib"
	"github.com/platinasystems/go/elib/hw"

	"reflect"
	"unsafe"
)

type TxDescriptorVec []TxDescriptor

func fromByteSlice_TxDescriptor(b []byte, l, c uint) (x TxDescriptorVec) {
	s := uint(unsafe.Sizeof(x[0]))
	if l == 0 {
		l = uint(len(b)) / s
		c = uint(cap(b))
	}
	return *(*TxDescriptorVec)(unsafe.Pointer(&reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(&b[0])),
		Len:  int(l),
		Cap:  int(c / s),
	}))
}

func (x TxDescriptorVec) toByteSlice() []byte {
	l := uint(len(x))
	l *= uint(unsafe.Sizeof(x[0]))
	return *(*[]byte)(unsafe.Pointer(&reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(&x[0])),
		Len:  int(l),
		Cap:  int(l)}))
}

func TxDescriptorAllocAligned(n, a uint) (x TxDescriptorVec, id elib.Index) {
	var b []byte
	var c uint
	b, id, _, c = hw.DmaAllocAligned(n*uint(unsafe.Sizeof(x[0])), a)
	x = fromByteSlice_TxDescriptor(b, n, c)
	return
}

func TxDescriptorAlloc(n uint) (x TxDescriptorVec, id elib.Index) {
	return TxDescriptorAllocAligned(n, 0)
}

func TxDescriptorNew() (x TxDescriptorVec, id elib.Index) { return TxDescriptorAlloc(1) }

func (x *TxDescriptorVec) Free(id elib.Index) {
	hw.DmaFree(id)
	*x = nil
}

func (x *TxDescriptorVec) Get(id elib.Index) {
	*x = fromByteSlice_TxDescriptor(hw.DmaGetData(id), 0, 0)
}

func (x *TxDescriptor) PhysAddress() uintptr {
	return hw.DmaPhysAddress(uintptr(unsafe.Pointer(x)))
}
