// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=netlink -id Attr -d VecType=AttrVec -d Type=Attr github.com/platinasystems/go/elib/vec.tmpl]

package netlink

import (
	"github.com/platinasystems/go/elib"
)

type AttrVec []Attr

func (p *AttrVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Attr, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *AttrVec) validate(new_len uint, zero *Attr) *Attr {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *AttrVec) validateSlowPath(zero *Attr,
	c, l, lʹ elib.Index) *Attr {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Attr, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *AttrVec) Validate(i uint) *Attr {
	return p.validate(i+1, (*Attr)(nil))
}

func (p *AttrVec) ValidateInit(i uint, zero Attr) *Attr {
	return p.validate(i+1, &zero)
}

func (p *AttrVec) ValidateLen(l uint) (v *Attr) {
	if l > 0 {
		v = p.validate(l, (*Attr)(nil))
	}
	return
}

func (p *AttrVec) ValidateLenInit(l uint, zero Attr) (v *Attr) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p AttrVec) Len() uint { return uint(len(p)) }
