// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=netlink -id Attr -d VecType=AttrVec -d Type=Attr github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package netlink

import (
	"github.com/platinasystems/go/elib"
)

type AttrVec []Attr

func (p *AttrVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Attr, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *AttrVec) validate(new_len uint, zero Attr) *Attr {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *AttrVec) validateSlowPath(zero Attr, c, l, lʹ uint) *Attr {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Attr, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *AttrVec) Validate(i uint) *Attr {
	var zero Attr
	return p.validate(i+1, zero)
}

func (p *AttrVec) ValidateInit(i uint, zero Attr) *Attr {
	return p.validate(i+1, zero)
}

func (p *AttrVec) ValidateLen(l uint) (v *Attr) {
	if l > 0 {
		var zero Attr
		v = p.validate(l, zero)
	}
	return
}

func (p *AttrVec) ValidateLenInit(l uint, zero Attr) (v *Attr) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *AttrVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p AttrVec) Len() uint { return uint(len(p)) }
