//go:build netlink || linux

/* SPDX-License-Identifier: GPL-2.0+ WITH Linux-syscall-note */

package iflink

const (
	IFNAMSIZ    = 16
	IFALIASZ    = 256
	ALTIFNAMSIZ = 128
)

const (
	IFF_UP = 1 << iota
	IFF_BROADCAST
	IFF_DEBUG
	IFF_LOOPBACK
	IFF_POINTOPOINT
	IFF_NOTRAILERS
	IFF_RUNNING
	IFF_NOARP
	IFF_PROMISC
	IFF_ALLMULTI
	IFF_MASTER
	IFF_SLAVE
	IFF_MULTICAST
	IFF_PORTSEL
	IFF_AUTOMEDIA
	IFF_DYNAMIC
	IFF_LOWER_UP
	IFF_DORMANT
	IFF_ECHO
)

const IFF_VOLATILE = IFF_LOOPBACK |
	IFF_POINTOPOINT |
	IFF_BROADCAST |
	IFF_ECHO |
	IFF_MASTER |
	IFF_SLAVE |
	IFF_RUNNING |
	IFF_LOWER_UP |
	IFF_DORMANT

const (
	IF_GET_IFACE = 1 + iota
	IF_GET_PROTO
)

const IfaceBase = 0x1000
const (
	IF_IFACE_V35 = IfaceBase + iota
	IF_IFACE_V24
	IF_IFACE_X21
	IF_IFACE_T1
	IF_IFACE_E1
	IF_IFACE_SYNC_SERIAL
	IF_IFACE_X21D
)

const IfProtoBase = 0x2000
const (
	IF_PROTO_HDLC = IfProtoBase + iota
	IF_PROTO_PPP
	IF_PROTO_CISCO
	IF_PROTO_FR
	IF_PROTO_FR_ADD_PVC
	IF_PROTO_FR_DEL_PVC
	IF_PROTO_X25
	IF_PROTO_HDLC_ETH
	IF_PROTO_FR_ADD_ETH_PVC
	IF_PROTO_FR_DEL_ETH_PVC
	IF_PROTO_FR_PVC
	IF_PROTO_FR_ETH_PVC
	IF_PROTO_RAW
)

const (
	IF_OPER_UNKNOWN = iota
	IF_OPER_NOTPRESENT
	IF_OPER_DOWN
	IF_OPER_LOWERLAYERDOWN
	IF_OPER_TESTING
	IF_OPER_DORMANT
	IF_OPER_UP
)

const (
	IF_LINK_MODE_DEFAULT = iota
	IF_LINK_MODE_DORMANT
	IF_LINK_MODE_TESTING
)

type IfMap struct {
	MemStart uint64
	MemEnd   uint64
	BaseAddr uint64
	IRQ      uint16
	DMA      uint8
	Port     uint8
}

type IfSettings struct {
	Type uint32
	Size uint32
	Ptr  uintptr
}
