/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */

package iflink

import "github.com/platinasystems/goes/v2/pkg/encoding/binary/big"

type Stats[T uint32 | uint64] struct {
	RxPackets,
	TxPackets,
	RxBytes,
	TxBytes,
	RxErrors,
	TxErrors,
	RxDropped,
	TxDropped,
	Multicast,
	Collisions,
	RxLengthErrors,
	RxOverErrors,
	RxCrcErrors,
	RxFrameErrors,
	RxFifoErrors,
	RxMissedErrors,
	TxAbortedErrors,
	TxCarrierErrors,
	TxFifoErrors,
	TxHeartbeatErrors,
	TxWindowErrors,
	RxCompressed,
	TxCompressed T
}

type HwStats64 struct {
	RxPackets uint64
	TxPackets uint64
	RxBytes   uint64
	TxBytes   uint64
	RxErrors  uint64
	TxErrors  uint64
	RxDropped uint64
	TxDropped uint64
	Multicast uint64
}

type Ifla uint16

const (
	IFLA_UNSPEC Ifla = iota
	IFLA_ADDRESS
	IFLA_BROADCAST
	IFLA_IFNAME
	IFLA_MTU
	IFLA_LINK
	IFLA_QDISC
	IFLA_STATS
	IFLA_COST
	IFLA_PRIORITY
	IFLA_MASTER
	IFLA_WIRELESS
	IFLA_PROTINFO
	IFLA_TXQLEN
	IFLA_MAP
	IFLA_WEIGHT
	IFLA_OPERSTATE
	IFLA_LINKMODE
	IFLA_LINKINFO
	IFLA_NET_NS_PID
	IFLA_IFALIAS
	IFLA_NUM_VF
	IFLA_VFINFO_LIST
	IFLA_STATS64
	IFLA_VF_PORTS
	IFLA_PORT_SELF
	IFLA_AF_SPEC
	IFLA_GROUP
	IFLA_NET_NS_FD
	IFLA_EXT_MASK
	IFLA_PROMISCUITY
	IFLA_NUM_TX_QUEUES
	IFLA_NUM_RX_QUEUES
	IFLA_CARRIER
	IFLA_PHYS_PORT_ID
	IFLA_CARRIER_CHANGES
	IFLA_PHYS_SWITCH_ID
	IFLA_LINK_NETNSID
	IFLA_PHYS_PORT_NAME
	IFLA_PROTO_DOWN
	IFLA_GSO_MAX_SEGS
	IFLA_GSO_MAX_SIZE
	IFLA_PAD
	IFLA_XDP
	IFLA_EVENT
	IFLA_NEW_NETNSID
	IFLA_IF_NETNSID
	IFLA_TARGET_NETNSID = IFLA_IF_NETNSID
	IFLA_CARRIER_UP_COUNT
	IFLA_CARRIER_DOWN_COUNT
	IFLA_NEW_IFINDEX
	IFLA_MIN_MTU
	IFLA_MAX_MTU
	IFLA_PROP_LIST
	IFLA_ALT_IFNAME
	IFLA_PERM_ADDRESS
	IFLA_PROTO_DOWN_REASON
	IFLA_PARENT_DEV_NAME
	IFLA_PARENT_DEV_BUS_NAME
	IFLA_GRO_MAX_SIZE
	IFLA_TSO_MAX_SIZE
	IFLA_TSO_MAX_SEGS
	IFLA_ALLMULTI
	IFLA_DEVLINK_PORT
	IFLA_GSO_IPV4_MAX_SIZE
	IFLA_GRO_IPV4_MAX_SIZE
	IFLA_CNT
)
const IFLA_MAX = IFLA_CNT - 1

const (
	IFLA_PROTO_DOWN_REASON_UNSPEC Ifla = iota
	IFLA_PROTO_DOWN_REASON_MASK
	IFLA_PROTO_DOWN_REASON_VALUE
	IFLA_PROTO_DOWN_REASON_CNT
)
const IFLA_PROTO_DOWN_REASON_MAX = IFLA_PROTO_DOWN_REASON_CNT - 1

const (
	IFLA_INET_UNSPEC Ifla = iota
	IFLA_INET_CONF
	IFLA_INET_CNT
)
const IFLA_INET_MAX = IFLA_INET_CNT - 1

const (
	IFLA_INET6_UNSPEC Ifla = iota
	IFLA_INET6_FLAGS
	IFLA_INET6_CONF
	IFLA_INET6_STATS
	IFLA_INET6_MCAST
	IFLA_INET6_CACHEINFO
	IFLA_INET6_ICMP6STATS
	IFLA_INET6_TOKEN
	IFLA_INET6_ADDR_GEN_MODE
	IFLA_INET6_RA_MTU
	IFLA_INET6_CNT
)
const IFLA_INET6_MAX = IFLA_INET6_CNT - 1

type Attr struct {
	Len  uint16
	Type Ifla
}

type In6AddrGenMode uint8

const (
	IN6_ADDR_GEN_MODE_EUI64 In6AddrGenMode = iota
	IN6_ADDR_GEN_MODE_NONE
	IN6_ADDR_GEN_MODE_STABLE_PRIVACY
	IN6_ADDR_GEN_MODE_RANDOM
)

const (
	IFLA_BR_UNSPEC = iota
	IFLA_BR_FORWARD_DELAY
	IFLA_BR_HELLO_TIME
	IFLA_BR_MAX_AGE
	IFLA_BR_AGEING_TIME
	IFLA_BR_STP_STATE
	IFLA_BR_PRIORITY
	IFLA_BR_VLAN_FILTERING
	IFLA_BR_VLAN_PROTOCOL
	IFLA_BR_GROUP_FWD_MASK
	IFLA_BR_ROOT_ID
	IFLA_BR_BRIDGE_ID
	IFLA_BR_ROOT_PORT
	IFLA_BR_ROOT_PATH_COST
	IFLA_BR_TOPOLOGY_CHANGE
	IFLA_BR_TOPOLOGY_CHANGE_DETECTED
	IFLA_BR_HELLO_TIMER
	IFLA_BR_TCN_TIMER
	IFLA_BR_TOPOLOGY_CHANGE_TIMER
	IFLA_BR_GC_TIMER
	IFLA_BR_GROUP_ADDR
	IFLA_BR_FDB_FLUSH
	IFLA_BR_MCAST_ROUTER
	IFLA_BR_MCAST_SNOOPING
	IFLA_BR_MCAST_QUERY_USE_IFADDR
	IFLA_BR_MCAST_QUERIER
	IFLA_BR_MCAST_HASH_ELASTICITY
	IFLA_BR_MCAST_HASH_MAX
	IFLA_BR_MCAST_LAST_MEMBER_CNT
	IFLA_BR_MCAST_STARTUP_QUERY_CNT
	IFLA_BR_MCAST_LAST_MEMBER_INTVL
	IFLA_BR_MCAST_MEMBERSHIP_INTVL
	IFLA_BR_MCAST_QUERIER_INTVL
	IFLA_BR_MCAST_QUERY_INTVL
	IFLA_BR_MCAST_QUERY_RESPONSE_INTVL
	IFLA_BR_MCAST_STARTUP_QUERY_INTVL
	IFLA_BR_NF_CALL_IPTABLES
	IFLA_BR_NF_CALL_IP6TABLES
	IFLA_BR_NF_CALL_ARPTABLES
	IFLA_BR_VLAN_DEFAULT_PVID
	IFLA_BR_PAD
	IFLA_BR_VLAN_STATS_ENABLED
	IFLA_BR_MCAST_STATS_ENABLED
	IFLA_BR_MCAST_IGMP_VERSION
	IFLA_BR_MCAST_MLD_VERSION
	IFLA_BR_VLAN_STATS_PER_PORT
	IFLA_BR_MULTI_BOOLOPT
	IFLA_BR_MCAST_QUERIER_STATE
	IFLA_BR_CNT
)
const IFLA_BR_MAX = IFLA_BR_CNT - 1

type IflaBridgeId struct {
	Prio [2]uint8
	Addr [6]uint8
}

const (
	BRIDGE_MODE_UNSPEC = iota
	BRIDGE_MODE_HAIRPIN
)

const (
	IFLA_BRPORT_UNSPEC Ifla = iota
	IFLA_BRPORT_STATE
	IFLA_BRPORT_PRIORITY
	IFLA_BRPORT_COST
	IFLA_BRPORT_MODE
	IFLA_BRPORT_GUARD
	IFLA_BRPORT_PROTECT
	IFLA_BRPORT_FAST_LEAVE
	IFLA_BRPORT_LEARNING
	IFLA_BRPORT_UNICAST_FLOOD
	IFLA_BRPORT_PROXYARP
	IFLA_BRPORT_LEARNING_SYNC
	IFLA_BRPORT_PROXYARP_WIFI
	IFLA_BRPORT_ROOT_ID
	IFLA_BRPORT_BRIDGE_ID
	IFLA_BRPORT_DESIGNATED_PORT
	IFLA_BRPORT_DESIGNATED_COST
	IFLA_BRPORT_ID
	IFLA_BRPORT_NO
	IFLA_BRPORT_TOPOLOGY_CHANGE_ACK
	IFLA_BRPORT_CONFIG_PENDING
	IFLA_BRPORT_MESSAGE_AGE_TIMER
	IFLA_BRPORT_FORWARD_DELAY_TIMER
	IFLA_BRPORT_HOLD_TIMER
	IFLA_BRPORT_FLUSH
	IFLA_BRPORT_MULTICAST_ROUTER
	IFLA_BRPORT_PAD
	IFLA_BRPORT_MCAST_FLOOD
	IFLA_BRPORT_MCAST_TO_UCAST
	IFLA_BRPORT_VLAN_TUNNEL
	IFLA_BRPORT_BCAST_FLOOD
	IFLA_BRPORT_GROUP_FWD_MASK
	IFLA_BRPORT_NEIGH_SUPPRESS
	IFLA_BRPORT_ISOLATED
	IFLA_BRPORT_BACKUP_PORT
	IFLA_BRPORT_MRP_RING_OPEN
	IFLA_BRPORT_MRP_IN_OPEN
	IFLA_BRPORT_MCAST_EHT_HOSTS_LIMIT
	IFLA_BRPORT_MCAST_EHT_HOSTS_CNT
	IFLA_BRPORT_LOCKED
	IFLA_BRPORT_MAB
	IFLA_BRPORT_MCAST_N_GROUPS
	IFLA_BRPORT_MCAST_MAX_GROUPS
	IFLA_BRPORT_NEIGH_VLAN_SUPPRESS
	IFLA_BRPORT_BACKUP_NHID
	IFLA_BRPORT_CNT
)
const IFLA_BRPORT_MAX = IFLA_BRPORT_CNT - 1

type IflaCacheInfo struct {
	MaxReasmLen   uint32
	Tstamp        uint32
	ReachableTime uint32
	RetransTime   uint32
}

const (
	IFLA_INFO_UNSPEC Ifla = iota
	IFLA_INFO_KIND
	IFLA_INFO_DATA
	IFLA_INFO_XSTATS
	IFLA_INFO_SLAVE_KIND
	IFLA_INFO_SLAVE_DATA
	IFLA_INFO_CNT
)
const IFLA_INFO_MAX = IFLA_INFO_CNT - 1

const (
	IFLA_VLAN_UNSPEC = iota
	IFLA_VLAN_ID
	IFLA_VLAN_FLAGS
	IFLA_VLAN_EGRESS_QOS
	IFLA_VLAN_INGRESS_QOS
	IFLA_VLAN_PROTOCOL
	IFLA_VLAN_CNT
)
const IFLA_VLAN_MAX = IFLA_VLAN_CNT - 1

type IflaVlanFlags struct {
	Flags uint32
	Mask  uint32
}

const (
	IFLA_VLAN_QOS_UNSPEC = iota
	IFLA_VLAN_QOS_MAPPING
	IFLA_VLAN_QOS_CNT
)
const IFLA_VLAN_QOS_MAX = IFLA_VLAN_QOS_CNT - 1

type IflaVlanQOSMapping struct {
	From uint32
	To   uint32
}

const (
	IFLA_MACVLAN_UNSPEC = iota
	IFLA_MACVLAN_MODE
	IFLA_MACVLAN_FLAGS
	IFLA_MACVLAN_MACADDR_MODE
	IFLA_MACVLAN_MACADDR
	IFLA_MACVLAN_MACADDR_DATA
	IFLA_MACVLAN_MACADDR_COUNT
	IFLA_MACVLAN_BC_QUEUE_LEN
	IFLA_MACVLAN_BC_QUEUE_LEN_USED
	IFLA_MACVLAN_BC_CUTOFF
	IFLA_MACVLAN_CNT
)
const IFLA_MACVLAN_MAX = IFLA_MACVLAN_CNT - 1

type MacVlanMode = uint8

const (
	MACVLAN_MODE_PRIVATE  MacVlanMode = 1
	MACVLAN_MODE_VEPA     MacVlanMode = 2
	MACVLAN_MODE_BRIDGE   MacVlanMode = 4
	MACVLAN_MODE_PASSTHRU MacVlanMode = 8
	MACVLAN_MODE_SOURCE   MacVlanMode = 16
)

type MacVlanMacAddrMode = uint8

const (
	MACVLAN_MACADDR_ADD MacVlanMacAddrMode = iota
	MACVLAN_MACADDR_DEL
	MACVLAN_MACADDR_FLUSH
	MACVLAN_MACADDR_SET
)

const (
	MACVLAN_FLAG_NOPROMISC = 1
	MACVLAN_FLAG_NODST     = 2
)

const (
	IFLA_VRF_UNSPEC = iota
	IFLA_VRF_TABLE
	IFLA_VRF_CNT
)
const IFLA_VRF_MAX = IFLA_VRF_CNT - 1

const (
	IFLA_VRF_PORT_UNSPEC = iota
	IFLA_VRF_PORT_TABLE
	IFLA_VRF_PORT_CNT
)
const IFLA_VRF_PORT_MAX = IFLA_VRF_PORT_CNT - 1

const (
	IFLA_MACSEC_UNSPEC = iota
	IFLA_MACSEC_SCI
	IFLA_MACSEC_PORT
	IFLA_MACSEC_ICV_LEN
	IFLA_MACSEC_CIPHER_SUITE
	IFLA_MACSEC_WINDOW
	IFLA_MACSEC_ENCODING_SA
	IFLA_MACSEC_ENCRYPT
	IFLA_MACSEC_PROTECT
	IFLA_MACSEC_INC_SCI
	IFLA_MACSEC_ES
	IFLA_MACSEC_SCB
	IFLA_MACSEC_REPLAY_PROTECT
	IFLA_MACSEC_VALIDATION
	IFLA_MACSEC_PAD
	IFLA_MACSEC_OFFLOAD
	IFLA_MACSEC_CNT
)
const IFLA_MACSEC_MAX = IFLA_MACSEC_CNT - 1

const (
	IFLA_XFRM_UNSPEC = iota
	IFLA_XFRM_LINK
	IFLA_XFRM_IF_ID
	IFLA_XFRM_COLLECT_METADATA
	IFLA_XFRM_CNT
)
const IFLA_XFRM_MAX = IFLA_XFRM_CNT - 1

type MacSecValidate uint8

const (
	MACSEC_VALIDATE_DISABLED MacSecValidate = iota
	MACSEC_VALIDATE_CHECK
	MACSEC_VALIDATE_STRICT
	MACSEC_VALIDATE_END
)
const MACSEC_VALIDATE_MAX = MACSEC_VALIDATE_END - 1

type MacSecOffload uint8

const (
	MACSEC_OFFLOAD_OFF MacSecOffload = iota
	MACSEC_OFFLOAD_PHY
	MACSEC_OFFLOAD_MAC
	MACSEC_OFFLOAD_END
)
const MACSEC_OFFLOAD_MAX = MACSEC_OFFLOAD_END - 1

const (
	IFLA_IPVLAN_UNSPEC = iota
	IFLA_IPVLAN_MODE
	IFLA_IPVLAN_FLAGS
	IFLA_IPVLAN_CNT
)
const IFLA_IPVLAN_MAX = IFLA_IPVLAN_CNT - 1

type IpVlanMode = uint8

const (
	IPVLAN_MODE_L2 IpVlanMode = 0
	IPVLAN_MODE_L3
	IPVLAN_MODE_L3S
	IPVLAN_MODE_MAX
)

const (
	IPVLAN_F_PRIVATE = 1
	IPVLAN_F_VEPA    = 2
)

type TunnelMsg struct {
	Family  uint8
	Flags   uint8
	_       uint16
	IfIndex uint32
}

const TUNNEL_MSG_FLAG_STATS = 1
const TUNNEL_MSG_VALID_USER_FLAGS = TUNNEL_MSG_FLAG_STATS

const (
	VNIFILTER_ENTRY_STATS_UNSPEC = iota
	VNIFILTER_ENTRY_STATS_RX_BYTES
	VNIFILTER_ENTRY_STATS_RX_PKTS
	VNIFILTER_ENTRY_STATS_RX_DROPS
	VNIFILTER_ENTRY_STATS_RX_ERRORS
	VNIFILTER_ENTRY_STATS_TX_BYTES
	VNIFILTER_ENTRY_STATS_TX_PKTS
	VNIFILTER_ENTRY_STATS_TX_DROPS
	VNIFILTER_ENTRY_STATS_TX_ERRORS
	VNIFILTER_ENTRY_STATS_PAD
	VNIFILTER_ENTRY_STATS_CNT
)
const VNIFILTER_ENTRY_STATS_MAX = VNIFILTER_ENTRY_STATS_CNT - 1

const (
	VXLAN_VNIFILTER_ENTRY_UNSPEC = iota
	VXLAN_VNIFILTER_ENTRY_START
	VXLAN_VNIFILTER_ENTRY_END
	VXLAN_VNIFILTER_ENTRY_GROUP
	VXLAN_VNIFILTER_ENTRY_GROUP6
	VXLAN_VNIFILTER_ENTRY_STATS
	VXLAN_VNIFILTER_ENTRY_CNT
)
const VXLAN_VNIFILTER_ENTRY_MAX = VXLAN_VNIFILTER_ENTRY_CNT - 1

const (
	VXLAN_VNIFILTER_UNSPEC = iota
	VXLAN_VNIFILTER_ENTRY
	VXLAN_VNIFILTER_CNT
)
const VXLAN_VNIFILTER_MAX = VXLAN_VNIFILTER_CNT - 1

const (
	IFLA_VXLAN_UNSPEC = iota
	IFLA_VXLAN_ID
	IFLA_VXLAN_GROUP
	IFLA_VXLAN_LINK
	IFLA_VXLAN_LOCAL
	IFLA_VXLAN_TTL
	IFLA_VXLAN_TOS
	IFLA_VXLAN_LEARNING
	IFLA_VXLAN_AGEING
	IFLA_VXLAN_LIMIT
	IFLA_VXLAN_PORT_RANGE
	IFLA_VXLAN_PROXY
	IFLA_VXLAN_RSC
	IFLA_VXLAN_L2MISS
	IFLA_VXLAN_L3MISS
	IFLA_VXLAN_PORT
	IFLA_VXLAN_GROUP6
	IFLA_VXLAN_LOCAL6
	IFLA_VXLAN_UDP_CSUM
	IFLA_VXLAN_UDP_ZERO_CSUM6_TX
	IFLA_VXLAN_UDP_ZERO_CSUM6_RX
	IFLA_VXLAN_REMCSUM_TX
	IFLA_VXLAN_REMCSUM_RX
	IFLA_VXLAN_GBP
	IFLA_VXLAN_REMCSUM_NOPARTIAL
	IFLA_VXLAN_COLLECT_METADATA
	IFLA_VXLAN_LABEL
	IFLA_VXLAN_GPE
	IFLA_VXLAN_TTL_INHERIT
	IFLA_VXLAN_DF
	IFLA_VXLAN_VNIFILTER
	IFLA_VXLAN_LOCALBYPASS
	IFLA_VXLAN_CNT
)
const IFLA_VXLAN_MAX = IFLA_VXLAN_CNT - 1

type IflaVxlanPortRange struct {
	Low  big.Uint16
	High big.Uint16
}

type IflaVxlanDF = uint8

const (
	VXLAN_DF_UNSET IflaVxlanDF = iota
	VXLAN_DF_SET
	VXLAN_DF_INHERIT
	VXLAN_DF_END
)
const VXLAN_DF_MAX = VXLAN_DF_END - 1

const (
	IFLA_GENEVE_UNSPEC = iota
	IFLA_GENEVE_ID
	IFLA_GENEVE_REMOTE
	IFLA_GENEVE_TTL
	IFLA_GENEVE_TOS
	IFLA_GENEVE_PORT
	IFLA_GENEVE_COLLECT_METADATA
	IFLA_GENEVE_REMOTE6
	IFLA_GENEVE_UDP_CSUM
	IFLA_GENEVE_UDP_ZERO_CSUM6_TX
	IFLA_GENEVE_UDP_ZERO_CSUM6_RX
	IFLA_GENEVE_LABEL
	IFLA_GENEVE_TTL_INHERIT
	IFLA_GENEVE_DF
	IFLA_GENEVE_INNER_PROTO_INHERIT
	IFLA_GENEVE_CNT
)
const IFLA_GENEVE_MAX = IFLA_GENEVE_CNT - 1

type IflaGeneveDF uint8

const (
	GENEVE_DF_UNSET = 0
	GENEVE_DF_SET
	GENEVE_DF_INHERIT
	GENEVE_DF_END
)
const GENEVE_DF_MAX = GENEVE_DF_END - 1

const (
	IFLA_BAREUDP_UNSPEC = iota
	IFLA_BAREUDP_PORT
	IFLA_BAREUDP_ETHERTYPE
	IFLA_BAREUDP_SRCPORT_MIN
	IFLA_BAREUDP_MULTIPROTO_MODE
	IFLA_BAREUDP_CNT
)
const IFLA_BAREUDP_MAX = IFLA_BAREUDP_CNT - 1

const (
	IFLA_PPP_UNSPEC = iota
	IFLA_PPP_DEV_FD
	IFLA_PPP_CNT
)
const IFLA_PPP_MAX = IFLA_PPP_CNT - 1

type IflaGTPRole = uint8

const (
	GTP_ROLE_GGSN IflaGTPRole = iota
	GTP_ROLE_SGSN
)

const (
	IFLA_GTP_UNSPEC = iota
	IFLA_GTP_FD0
	IFLA_GTP_FD1
	IFLA_GTP_PDP_HASHSIZE
	IFLA_GTP_ROLE
	IFLA_GTP_CREATE_SOCKETS
	IFLA_GTP_RESTART_COUNT
	IFLA_GTP_CNT
)
const IFLA_GTP_MAX = IFLA_GTP_CNT - 1

const (
	IFLA_BOND_UNSPEC = iota
	IFLA_BOND_MODE
	IFLA_BOND_ACTIVE_SLAVE
	IFLA_BOND_MIIMON
	IFLA_BOND_UPDELAY
	IFLA_BOND_DOWNDELAY
	IFLA_BOND_USE_CARRIER
	IFLA_BOND_ARP_INTERVAL
	IFLA_BOND_ARP_IP_TARGET
	IFLA_BOND_ARP_VALIDATE
	IFLA_BOND_ARP_ALL_TARGETS
	IFLA_BOND_PRIMARY
	IFLA_BOND_PRIMARY_RESELECT
	IFLA_BOND_FAIL_OVER_MAC
	IFLA_BOND_XMIT_HASH_POLICY
	IFLA_BOND_RESEND_IGMP
	IFLA_BOND_NUM_PEER_NOTIF
	IFLA_BOND_ALL_SLAVES_ACTIVE
	IFLA_BOND_MIN_LINKS
	IFLA_BOND_LP_INTERVAL
	IFLA_BOND_PACKETS_PER_SLAVE
	IFLA_BOND_AD_LACP_RATE
	IFLA_BOND_AD_SELECT
	IFLA_BOND_AD_INFO
	IFLA_BOND_AD_ACTOR_SYS_PRIO
	IFLA_BOND_AD_USER_PORT_KEY
	IFLA_BOND_AD_ACTOR_SYSTEM
	IFLA_BOND_TLB_DYNAMIC_LB
	IFLA_BOND_PEER_NOTIF_DELAY
	IFLA_BOND_AD_LACP_ACTIVE
	IFLA_BOND_MISSED_MAX
	IFLA_BOND_NS_IP6_TARGET
	IFLA_BOND_CNT
)
const IFLA_BOND_MAX = IFLA_BOND_CNT - 1

const (
	IFLA_BOND_AD_INFO_UNSPEC = iota
	IFLA_BOND_AD_INFO_AGGREGATOR
	IFLA_BOND_AD_INFO_NUM_PORTS
	IFLA_BOND_AD_INFO_ACTOR_KEY
	IFLA_BOND_AD_INFO_PARTNER_KEY
	IFLA_BOND_AD_INFO_PARTNER_MAC
	IFLA_BOND_AD_INFO_CNT
)
const IFLA_BOND_AD_INFO_MAX = IFLA_BOND_AD_INFO_CNT - 1

const (
	IFLA_BOND_SLAVE_UNSPEC = iota
	IFLA_BOND_SLAVE_STATE
	IFLA_BOND_SLAVE_MII_STATUS
	IFLA_BOND_SLAVE_LINK_FAILURE_COUNT
	IFLA_BOND_SLAVE_PERM_HWADDR
	IFLA_BOND_SLAVE_QUEUE_ID
	IFLA_BOND_SLAVE_AD_AGGREGATOR_ID
	IFLA_BOND_SLAVE_AD_ACTOR_OPER_PORT_STATE
	IFLA_BOND_SLAVE_AD_PARTNER_OPER_PORT_STATE
	IFLA_BOND_SLAVE_PRIO
	IFLA_BOND_SLAVE_CNT
)
const IFLA_BOND_SLAVE_MAX = IFLA_BOND_SLAVE_CNT - 1

const (
	IFLA_VF_INFO_UNSPEC = iota
	IFLA_VF_INFO
	IFLA_VF_INFO_CNT
)
const IFLA_VF_INFO_MAX = IFLA_VF_INFO_CNT - 1

const (
	IFLA_VF_UNSPEC = iota
	IFLA_VF_MAC
	IFLA_VF_VLAN
	IFLA_VF_TX_RATE
	IFLA_VF_SPOOFCHK
	IFLA_VF_LINK_STATE
	IFLA_VF_RATE
	IFLA_VF_RSS_QUERY_EN
	IFLA_VF_STATS
	IFLA_VF_TRUST
	IFLA_VF_IB_NODE_GUID
	IFLA_VF_IB_PORT_GUID
	IFLA_VF_VLAN_LIST
	IFLA_VF_BROADCAST
	IFLA_VF_CNT
)
const IFLA_VF_MAX = IFLA_VF_CNT - 1

type IflaVfMac struct {
	Vf  uint32
	Mac [32]uint8
}

type IflaVfBroadcast struct {
	Broadcast [32]uint8
}

type IflaVfVlan struct {
	Vf   uint32
	Vlan uint32
	Qos  uint32
}

const (
	IFLA_VF_VLAN_INFO_UNSPEC = iota
	IFLA_VF_VLAN_INFO
	IFLA_VF_VLAN_INFO_CNT
)
const IFLA_VF_VLAN_INFO_MAX = IFLA_VF_VLAN_INFO_CNT - 1
const MAX_VLAN_LIST_LEN = 1

type IflaVfVlanInfo struct {
	Vf        uint32
	Vlan      uint32
	Qos       uint32
	VlanProto big.Uint16
}

type IflaVfTxRate struct {
	Vf   uint32
	Rate uint32
}

type IflaVfRate struct {
	Vf        uint32
	MinTxRate uint32
	MaxTxRate uint32
}

type IflaVfSpoofchk struct {
	Vf      uint32
	Setting uint32
}

type IflaVfGuid struct {
	Vf   uint32
	Guid uint64
}

const (
	IFLA_VF_LINK_STATE_AUTO = iota
	IFLA_VF_LINK_STATE_ENABLE
	IFLA_VF_LINK_STATE_DISABLE
	IFLA_VF_LINK_STATE_CNT
)

type ifla_vf_link_state struct {
	Vf        uint32
	LinkState uint32
}

type ifla_vf_rss_query_en struct {
	Vf      uint32
	Setting uint32
}

const (
	IFLA_VF_STATS_RX_PACKETS = iota
	IFLA_VF_STATS_TX_PACKETS
	IFLA_VF_STATS_RX_BYTES
	IFLA_VF_STATS_TX_BYTES
	IFLA_VF_STATS_BROADCAST
	IFLA_VF_STATS_MULTICAST
	IFLA_VF_STATS_PAD
	IFLA_VF_STATS_RX_DROPPED
	IFLA_VF_STATS_TX_DROPPED
	IFLA_VF_STATS_CNT
)
const IFLA_VF_STATS_MAX = IFLA_VF_STATS_CNT - 1

type IflaVfTrust struct {
	Vf      uint32
	Setting uint32
}

const (
	IFLA_VF_PORT_UNSPEC = iota
	IFLA_VF_PORT
	IFLA_VF_PORT_CNT
)
const IFLA_VF_PORT_MAX = IFLA_VF_PORT_CNT - 1

const (
	IFLA_PORT_UNSPEC = iota
	IFLA_PORT_VF
	IFLA_PORT_PROFILE
	IFLA_PORT_VSI_TYPE
	IFLA_PORT_INSTANCE_UUID
	IFLA_PORT_HOST_UUID
	IFLA_PORT_REQUEST
	IFLA_PORT_RESPONSE
	IFLA_PORT_CNT
)
const IFLA_PORT_MAX = IFLA_PORT_CNT - 1

const (
	PORT_PROFILE_MAX = 40
	PORT_UUID_MAX    = 16
	PORT_SELF_VF     = -1
)

const (
	PORT_REQUEST_PREASSOCIATE = iota
	PORT_REQUEST_PREASSOCIATE_RR
	PORT_REQUEST_ASSOCIATE
	PORT_REQUEST_DISASSOCIATE
)

const (
	PORT_VDP_RESPONSE_SUCCESS = iota
	PORT_VDP_RESPONSE_INVALID_FORMAT
	PORT_VDP_RESPONSE_INSUFFICIENT_RESOURCES
	PORT_VDP_RESPONSE_UNUSED_VTID
	PORT_VDP_RESPONSE_VTID_VIOLATION
	PORT_VDP_RESPONSE_VTID_VERSION_VIOALTION
	PORT_VDP_RESPONSE_OUT_OF_SYNC
)
const (
	PORT_PROFILE_RESPONSE_SUCCESS = 0x100 + iota
	PORT_PROFILE_RESPONSE_INPROGRESS
	PORT_PROFILE_RESPONSE_INVALID
	PORT_PROFILE_RESPONSE_BADSTATE
	PORT_PROFILE_RESPONSE_INSUFFICIENT_RESOURCES
	PORT_PROFILE_RESPONSE_ERROR
)

type IflaPortVsi struct {
	VsiMgrId       uint8
	VsiTypeId      [3]uint8
	VsiTypeVersion uint8
	_              uint8
	_              uint16
}

const (
	IFLA_IPOIB_UNSPEC = iota
	IFLA_IPOIB_PKEY
	IFLA_IPOIB_MODE
	IFLA_IPOIB_UMCAST
	IFLA_IPOIB_CNT
)

const (
	IPOIB_MODE_DATAGRAM = iota
	IPOIB_MODE_CONNECTED
)
const IFLA_IPOIB_MAX = IFLA_IPOIB_CNT - 1

const (
	HSR_PROTOCOL_HSR = iota
	HSR_PROTOCOL_PRP
	HSR_PROTOCOL_MAX
)

const (
	IFLA_HSR_UNSPEC = iota
	IFLA_HSR_SLAVE1
	IFLA_HSR_SLAVE2
	IFLA_HSR_MULTICAST_SPEC
	IFLA_HSR_SUPERVISION_ADDR
	IFLA_HSR_SEQ_NR
	IFLA_HSR_VERSION
	IFLA_HSR_PROTOCOL
	IFLA_HSR_CNT
)
const IFLA_HSR_MAX = IFLA_HSR_CNT - 1

type IfStatsMsg struct {
	Family     uint8
	_          uint8
	_          uint16
	IfIndex    uint32
	FilterMask uint32
}

const (
	IFLA_STATS_UNSPEC = iota
	IFLA_STATS_LINK_64
	IFLA_STATS_LINK_XSTATS
	IFLA_STATS_LINK_XSTATS_SLAVE
	IFLA_STATS_LINK_OFFLOAD_XSTATS
	IFLA_STATS_AF_SPEC
	IFLA_STATS_CNT
)
const IFLA_STATS_MAX = IFLA_STATS_CNT - 1

const (
	IFLA_STATS_GETSET_UNSPEC = iota
	IFLA_STATS_GET_FILTERS
	IFLA_STATS_SET_OFFLOAD_XSTATS_L3_STATS
	IFLA_STATS_GETSET_CNT
)
const IFLA_STATS_GETSET_MAX = IFLA_STATS_GETSET_CNT - 1

const (
	LINK_XSTATS_TYPE_UNSPEC = iota
	LINK_XSTATS_TYPE_BRIDGE
	LINK_XSTATS_TYPE_BOND
	LINK_XSTATS_TYPE_CNT
)
const LINK_XSTATS_TYPE_MAX = LINK_XSTATS_TYPE_CNT - 1

const (
	IFLA_OFFLOAD_XSTATS_UNSPEC = iota
	IFLA_OFFLOAD_XSTATS_CPU_HIT
	IFLA_OFFLOAD_XSTATS_HW_S_INFO
	IFLA_OFFLOAD_XSTATS_L3_STATS
	IFLA_OFFLOAD_XSTATS_CNT
)
const IFLA_OFFLOAD_XSTATS_MAX = IFLA_OFFLOAD_XSTATS_CNT - 1

const (
	IFLA_OFFLOAD_XSTATS_HW_S_INFO_UNSPEC = iota
	IFLA_OFFLOAD_XSTATS_HW_S_INFO_REQUEST
	IFLA_OFFLOAD_XSTATS_HW_S_INFO_USED
	IFLA_OFFLOAD_XSTATS_HW_S_INFO_CNT
)
const IFLA_OFFLOAD_XSTATS_HW_S_INFO_MAX = IFLA_OFFLOAD_XSTATS_HW_S_INFO_CNT - 1

const (
	XDP_FLAGS_UPDATE_IF_NOEXIST = 1 << iota
	XDP_FLAGS_SKB_MODE
	XDP_FLAGS_DRV_MODE
	XDP_FLAGS_HW_MODE
	XDP_FLAGS_REPLACE
)
const XDP_FLAGS_MODES = XDP_FLAGS_SKB_MODE | XDP_FLAGS_DRV_MODE |
	XDP_FLAGS_HW_MODE
const XDP_FLAGS_MASK = XDP_FLAGS_UPDATE_IF_NOEXIST | XDP_FLAGS_MODES |
	XDP_FLAGS_REPLACE

const (
	XDP_ATTACHED_NONE = iota
	XDP_ATTACHED_DRV
	XDP_ATTACHED_SKB
	XDP_ATTACHED_HW
	XDP_ATTACHED_MULTI
)

const (
	IFLA_XDP_UNSPEC = iota
	IFLA_XDP_FD
	IFLA_XDP_ATTACHED
	IFLA_XDP_FLAGS
	IFLA_XDP_PROG_ID
	IFLA_XDP_DRV_PROG_ID
	IFLA_XDP_SKB_PROG_ID
	IFLA_XDP_HW_PROG_ID
	IFLA_XDP_EXPECTED_FD
	IFLA_XDP_CNT
)
const IFLA_XDP_MAX = IFLA_XDP_CNT - 1

const (
	IFLA_EVENT_NONE = iota
	IFLA_EVENT_REBOOT
	IFLA_EVENT_FEATURES
	IFLA_EVENT_BONDING_FAILOVER
	IFLA_EVENT_NOTIFY_PEERS
	IFLA_EVENT_IGMP_RESEND
	IFLA_EVENT_BONDING_OPTIONS
)

const (
	IFLA_TUN_UNSPEC = iota
	IFLA_TUN_OWNER
	IFLA_TUN_GROUP
	IFLA_TUN_TYPE
	IFLA_TUN_PI
	IFLA_TUN_VNET_HDR
	IFLA_TUN_PERSIST
	IFLA_TUN_MULTI_QUEUE
	IFLA_TUN_NUM_QUEUES
	IFLA_TUN_NUM_DISABLED_QUEUES
	IFLA_TUN_CNT
)
const IFLA_TUN_MAX = IFLA_TUN_CNT - 1

const (
	RMNET_FLAGS_INGRESS_DEAGGREGATION = 1 << iota
	RMNET_FLAGS_INGRESS_MAP_COMMANDS
	RMNET_FLAGS_INGRESS_MAP_CKSUMV4
	RMNET_FLAGS_EGRESS_MAP_CKSUMV4
	RMNET_FLAGS_INGRESS_MAP_CKSUMV5
	RMNET_FLAGS_EGRESS_MAP_CKSUMV5
)

const (
	IFLA_RMNET_UNSPEC = iota
	IFLA_RMNET_MUX_ID
	IFLA_RMNET_FLAGS
	IFLA_RMNET_CNT
)
const IFLA_RMNET_MAX = IFLA_RMNET_CNT - 1

type IflaRmNetFlags struct {
	Flags uint32
	Mask  uint32
}

const (
	IFLA_MCTP_UNSPEC = iota
	IFLA_MCTP_NET
	IFLA_MCTP_CNT
)
const IFLA_MCTP_MAX = IFLA_MCTP_CNT - 1

const (
	IFLA_DSA_UNSPEC = iota
	IFLA_DSA_MASTER
	IFLA_DSA_CNT
)
const IFLA_DSA_MAX = IFLA_DSA_CNT - 1
