// Code generated by "stringer -output=zif_proto_string.go -type=IfProto -trimprefix=IF_PROTO_ ."; DO NOT EDIT.

package iflink

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IF_PROTO_HDLC-8192]
	_ = x[IF_PROTO_PPP-8193]
	_ = x[IF_PROTO_CISCO-8194]
	_ = x[IF_PROTO_FR-8195]
	_ = x[IF_PROTO_FR_ADD_PVC-8196]
	_ = x[IF_PROTO_FR_DEL_PVC-8197]
	_ = x[IF_PROTO_X25-8198]
	_ = x[IF_PROTO_HDLC_ETH-8199]
	_ = x[IF_PROTO_FR_ADD_ETH_PVC-8200]
	_ = x[IF_PROTO_FR_DEL_ETH_PVC-8201]
	_ = x[IF_PROTO_FR_PVC-8202]
	_ = x[IF_PROTO_FR_ETH_PVC-8203]
	_ = x[IF_PROTO_RAW-8204]
}

const _IfProto_name = "HDLCPPPCISCOFRFR_ADD_PVCFR_DEL_PVCX25HDLC_ETHFR_ADD_ETH_PVCFR_DEL_ETH_PVCFR_PVCFR_ETH_PVCRAW"

var _IfProto_index = [...]uint8{0, 4, 7, 12, 14, 24, 34, 37, 45, 59, 73, 79, 89, 92}

func (i IfProto) String() string {
	i -= 8192
	if i >= IfProto(len(_IfProto_index)-1) {
		return "IfProto(" + strconv.FormatInt(int64(i+8192), 10) + ")"
	}
	return _IfProto_name[_IfProto_index[i]:_IfProto_index[i+1]]
}
