// Code generated by "stringer -output=zif_oper_string.go -type=IfOper -trimprefix=IF_OPER_ ."; DO NOT EDIT.

package iflink

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IF_OPER_UNKNOWN-0]
	_ = x[IF_OPER_NOTPRESENT-1]
	_ = x[IF_OPER_DOWN-2]
	_ = x[IF_OPER_LOWERLAYERDOWN-3]
	_ = x[IF_OPER_TESTING-4]
	_ = x[IF_OPER_DORMANT-5]
	_ = x[IF_OPER_UP-6]
}

const _IfOper_name = "UNKNOWNNOTPRESENTDOWNLOWERLAYERDOWNTESTINGDORMANTUP"

var _IfOper_index = [...]uint8{0, 7, 17, 21, 35, 42, 49, 51}

func (i IfOper) String() string {
	if i >= IfOper(len(_IfOper_index)-1) {
		return "IfOper(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IfOper_name[_IfOper_index[i]:_IfOper_index[i+1]]
}
