// Code generated by "stringer -output=zif_iface_string.go -type=IfIface -trimprefix=IF_IFACE_ ."; DO NOT EDIT.

package iflink

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IF_IFACE_V35-4096]
	_ = x[IF_IFACE_V24-4097]
	_ = x[IF_IFACE_X21-4098]
	_ = x[IF_IFACE_T1-4099]
	_ = x[IF_IFACE_E1-4100]
	_ = x[IF_IFACE_SYNC_SERIAL-4101]
	_ = x[IF_IFACE_X21D-4102]
}

const _IfIface_name = "V35V24X21T1E1SYNC_SERIALX21D"

var _IfIface_index = [...]uint8{0, 3, 6, 9, 11, 13, 24, 28}

func (i IfIface) String() string {
	i -= 4096
	if i >= IfIface(len(_IfIface_index)-1) {
		return "IfIface(" + strconv.FormatInt(int64(i+4096), 10) + ")"
	}
	return _IfIface_name[_IfIface_index[i]:_IfIface_index[i+1]]
}
