// Code generated by "stringer -output=zif_link_mode_string.go -type=IfLinkMode -trimprefix=IF_LINK_MODE_ ."; DO NOT EDIT.

package iflink

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IF_LINK_MODE_DEFAULT-0]
	_ = x[IF_LINK_MODE_DORMANT-1]
	_ = x[IF_LINK_MODE_TESTING-2]
}

const _IfLinkMode_name = "DEFAULTDORMANTTESTING"

var _IfLinkMode_index = [...]uint8{0, 7, 14, 21}

func (i IfLinkMode) String() string {
	if i >= IfLinkMode(len(_IfLinkMode_index)-1) {
		return "IfLinkMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IfLinkMode_name[_IfLinkMode_index[i]:_IfLinkMode_index[i+1]]
}
