// Code generated by "stringer -output=ziff_string.go -type=NetDeviceFlag -trimprefix=IFF_ ."; DO NOT EDIT.

package iflink

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IFF_UP-1]
	_ = x[IFF_BROADCAST-2]
	_ = x[IFF_DEBUG-4]
	_ = x[IFF_LOOPBACK-8]
	_ = x[IFF_POINTOPOINT-16]
	_ = x[IFF_NOTRAILERS-32]
	_ = x[IFF_RUNNING-64]
	_ = x[IFF_NOARP-128]
	_ = x[IFF_PROMISC-256]
	_ = x[IFF_ALLMULTI-512]
	_ = x[IFF_MASTER-1024]
	_ = x[IFF_SLAVE-2048]
	_ = x[IFF_MULTICAST-4096]
	_ = x[IFF_PORTSEL-8192]
	_ = x[IFF_AUTOMEDIA-16384]
	_ = x[IFF_DYNAMIC-32768]
	_ = x[IFF_LOWER_UP-65536]
	_ = x[IFF_DORMANT-131072]
	_ = x[IFF_ECHO-262144]
}

const _NetDeviceFlag_name = "UPBROADCASTDEBUGLOOPBACKPOINTOPOINTNOTRAILERSRUNNINGNOARPPROMISCALLMULTIMASTERSLAVEMULTICASTPORTSELAUTOMEDIADYNAMICLOWER_UPDORMANTECHO"

var _NetDeviceFlag_map = map[NetDeviceFlag]string{
	1:      _NetDeviceFlag_name[0:2],
	2:      _NetDeviceFlag_name[2:11],
	4:      _NetDeviceFlag_name[11:16],
	8:      _NetDeviceFlag_name[16:24],
	16:     _NetDeviceFlag_name[24:35],
	32:     _NetDeviceFlag_name[35:45],
	64:     _NetDeviceFlag_name[45:52],
	128:    _NetDeviceFlag_name[52:57],
	256:    _NetDeviceFlag_name[57:64],
	512:    _NetDeviceFlag_name[64:72],
	1024:   _NetDeviceFlag_name[72:78],
	2048:   _NetDeviceFlag_name[78:83],
	4096:   _NetDeviceFlag_name[83:92],
	8192:   _NetDeviceFlag_name[92:99],
	16384:  _NetDeviceFlag_name[99:108],
	32768:  _NetDeviceFlag_name[108:115],
	65536:  _NetDeviceFlag_name[115:123],
	131072: _NetDeviceFlag_name[123:130],
	262144: _NetDeviceFlag_name[130:134],
}

func (i NetDeviceFlag) String() string {
	if str, ok := _NetDeviceFlag_map[i]; ok {
		return str
	}
	return "NetDeviceFlag(" + strconv.FormatInt(int64(i), 10) + ")"
}
