// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=cpu.-id irqEvent -d Type=irqEvent github.com/platinasystems/go/elib/elog/event.tmpl]

package cpu

import (
	"github.com/platinasystems/go/elib/elog"
)

var irqEventType = &elog.EventType{
	Name: "cpu.irqEvent",
}

func init() {
	t := irqEventType
	t.Stringer = stringer_irqEvent
	t.Encode = encode_irqEvent
	t.Decode = decode_irqEvent
	elog.RegisterType(irqEventType)
}

func stringer_irqEvent(e *elog.Event) string {
	var x irqEvent
	x.Decode(e.Data[:])
	return x.String()
}

func encode_irqEvent(b []byte, e *elog.Event) int {
	var x irqEvent
	x.Decode(e.Data[:])
	return x.Encode(b)
}

func decode_irqEvent(b []byte, e *elog.Event) int {
	var x irqEvent
	x.Decode(b)
	return x.Encode(e.Data[:])
}

func (x irqEvent) Log() { x.Logb(elog.DefaultBuffer) }

func (x irqEvent) Logb(b *elog.Buffer) {
	e := b.Add(irqEventType)
	x.Encode(e.Data[:])
}
