// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=socket -id event -d Type=event github.com/platinasystems/go/elib/elog/event.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package socket

import (
	"github.com/platinasystems/go/elib/elog"
)

var eventType = &elog.EventType{
	Name: "socket.event",
}

func init() {
	t := eventType
	t.Strings = stringer_event
	t.Encode = encode_event
	t.Decode = decode_event
	elog.RegisterType(eventType)
}

func stringer_event(c *elog.Context, e *elog.Event) []string {
	var x event
	x.Decode(c, e.Data[:])
	return x.Strings(c)
}

func encode_event(c *elog.Context, e *elog.Event, b []byte) int {
	var x event
	x.Decode(c, e.Data[:])
	return x.Encode(c, b)
}

func decode_event(c *elog.Context, e *elog.Event, b []byte) int {
	var x event
	x.Decode(c, b)
	return x.Encode(c, e.Data[:])
}

func (x event) log_event(b *elog.Buffer, r elog.Caller) {
	e := b.Add(eventType, r)
	x.Encode(b.GetContext(), e.Data[:])
}

func (x event) Log() {
	r := elog.GetCaller(elog.PointerToFirstArg(&x))
	x.log_event(elog.DefaultBuffer, r)
}

func (x event) Logc(r elog.Caller) {
	x.log_event(elog.DefaultBuffer, r)
}

func (x event) Logb(b *elog.Buffer) {
	r := elog.GetCaller(elog.PointerToFirstArg(&x))
	x.log_event(b, r)
}

func (x event) Logbc(b *elog.Buffer, r elog.Caller) {
	x.log_event(b, r)
}
