// Code generated by "stringer -type Class -trimprefix Class -linecomment"; DO NOT EDIT.

package xdnsmessage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Class0-0]
	_ = x[ClassINET-1]
	_ = x[ClassCSNET-2]
	_ = x[ClassCHAOS-3]
	_ = x[ClassHESIOD-4]
	_ = x[ClassANY-255]
}

const (
	_Class_name_0 = "class0INCSCHHS"
	_Class_name_1 = "ANY"
)

var (
	_Class_index_0 = [...]uint8{0, 6, 8, 10, 12, 14}
)

func (i Class) String() string {
	switch {
	case i <= 4:
		return _Class_name_0[_Class_index_0[i]:_Class_index_0[i+1]]
	case i == 255:
		return _Class_name_1
	default:
		return "Class(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
