// Code generated by "stringer -type HFB -trimprefix HFB -linecomment"; DO NOT EDIT.

package xdnsmessage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HFBResponse-0]
	_ = x[HFBAuthoritative-1]
	_ = x[HFBTruncated-2]
	_ = x[HFBRecursionDesired-3]
	_ = x[HFBRecursionAvailable-4]
	_ = x[HFBAuthenticData-5]
	_ = x[HFBCheckingDisabled-6]
	_ = x[HFBend-7]
}

const _HFB_name = "qraatrrdraadcdend"

var _HFB_index = [...]uint8{0, 2, 4, 6, 8, 10, 12, 14, 17}

func (i HFB) String() string {
	if i >= HFB(len(_HFB_index)-1) {
		return "HFB(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HFB_name[_HFB_index[i]:_HFB_index[i+1]]
}
