// Code generated by "stringer -type RCode -trimprefix RCode -linecomment"; DO NOT EDIT.

package xdnsmessage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RCodeSuccess-0]
	_ = x[RCodeFormatError-1]
	_ = x[RCodeServerFailure-2]
	_ = x[RCodeNameError-3]
	_ = x[RCodeNotImplemented-4]
	_ = x[RCodeRefused-5]
}

const _RCode_name = "NoErrorFormErrServFailNXDomainNotImpRefused"

var _RCode_index = [...]uint8{0, 7, 14, 22, 30, 36, 43}

func (i RCode) String() string {
	if i >= RCode(len(_RCode_index)-1) {
		return "RCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RCode_name[_RCode_index[i]:_RCode_index[i+1]]
}
