// Code generated by "stringer -type SVCBKey -trimprefix SVCBKey -linecomment"; DO NOT EDIT.

package xdnsmessage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SVCBKeyMandatory-0]
	_ = x[SVCBKeyALPN-1]
	_ = x[SVCBKeyNoDefaultALPN-2]
	_ = x[SVCBKeyPort-3]
	_ = x[SVCBKeyIPV4Hint-4]
	_ = x[SVCBKeyECH-5]
	_ = x[SVCBKeyIPV6Hint-6]
	_ = x[SVCBKeyDOHPath-7]
}

const _SVCBKey_name = "mandatoryalpnno-default-alpnportipv4hintechipv6hintdoh-path"

var _SVCBKey_index = [...]uint8{0, 9, 13, 28, 32, 40, 43, 51, 59}

func (i SVCBKey) String() string {
	if i >= SVCBKey(len(_SVCBKey_index)-1) {
		return "SVCBKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SVCBKey_name[_SVCBKey_index[i]:_SVCBKey_index[i+1]]
}
