// Code generated by "stringer -type Type -trimprefix Type"; DO NOT EDIT.

package xdnsmessage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Type0-0]
	_ = x[TypeA-1]
	_ = x[TypeNS-2]
	_ = x[TypeMD-3]
	_ = x[TypeMF-4]
	_ = x[TypeCNAME-5]
	_ = x[TypeSOA-6]
	_ = x[TypeMB-7]
	_ = x[TypeMG-8]
	_ = x[TypeMR-9]
	_ = x[TypeNULL-10]
	_ = x[TypeWKS-11]
	_ = x[TypePTR-12]
	_ = x[TypeHINFO-13]
	_ = x[TypeMINFO-14]
	_ = x[TypeMX-15]
	_ = x[TypeTXT-16]
	_ = x[TypeRP-17]
	_ = x[TypeAFSDB-18]
	_ = x[TypeX25-19]
	_ = x[TypeISDN-20]
	_ = x[TypeRT-21]
	_ = x[TypeNSAP-22]
	_ = x[TypeNSAPPTR-23]
	_ = x[TypeSIG-24]
	_ = x[TypeKEY-25]
	_ = x[TypePX-26]
	_ = x[TypeGPOS-27]
	_ = x[TypeAAAA-28]
	_ = x[TypeLOC-29]
	_ = x[TypeNXT-30]
	_ = x[TypeEID-31]
	_ = x[TypeNB-32]
	_ = x[TypeSRV-33]
	_ = x[TypeATMA-34]
	_ = x[TypeNAPTR-35]
	_ = x[TypeKX-36]
	_ = x[TypeCERT-37]
	_ = x[TypeA6-38]
	_ = x[TypeDNAME-39]
	_ = x[TypeSINK-40]
	_ = x[TypeOPT-41]
	_ = x[TypeAPL-42]
	_ = x[TypeDS-43]
	_ = x[TypeSSHFP-44]
	_ = x[TypeIPSECKEY-45]
	_ = x[TypeRRSIG-46]
	_ = x[TypeNSEC-47]
	_ = x[TypeDNSKEY-48]
	_ = x[TypeDHCID-49]
	_ = x[TypeNSEC3-50]
	_ = x[TypeNSEC3PARAM-51]
	_ = x[TypeTLSA-52]
	_ = x[TypeSMIMEA-53]
	_ = x[Type54-54]
	_ = x[TypeHIP-55]
	_ = x[TypeNINFO-56]
	_ = x[TypeRKEY-57]
	_ = x[TypeTALINK-58]
	_ = x[TypeCDS-59]
	_ = x[TypeCDNSKEY-60]
	_ = x[TypeOPENPGPKEY-61]
	_ = x[TypeCSYNC-62]
	_ = x[TypeZONEMD-63]
	_ = x[TypeSVCB-64]
	_ = x[TypeHTTPS-65]
	_ = x[TypeEUI48-108]
	_ = x[TypeEUI64-109]
	_ = x[TypeTKEY-249]
	_ = x[TypeTSIG-250]
	_ = x[TypeIXFR-251]
	_ = x[TypeAXFR-252]
	_ = x[TypeMAILB-253]
	_ = x[TypeMAILA-254]
	_ = x[TypeANY-255]
	_ = x[TypeURI-256]
	_ = x[TypeCAA-257]
}

const (
	_Type_name_0 = "0ANSMDMFCNAMESOAMBMGMRNULLWKSPTRHINFOMINFOMXTXTRPAFSDBX25ISDNRTNSAPNSAPPTRSIGKEYPXGPOSAAAALOCNXTEIDNBSRVATMANAPTRKXCERTA6DNAMESINKOPTAPLDSSSHFPIPSECKEYRRSIGNSECDNSKEYDHCIDNSEC3NSEC3PARAMTLSASMIMEA54HIPNINFORKEYTALINKCDSCDNSKEYOPENPGPKEYCSYNCZONEMDSVCBHTTPS"
	_Type_name_1 = "EUI48EUI64"
	_Type_name_2 = "TKEYTSIGIXFRAXFRMAILBMAILAANYURICAA"
)

var (
	_Type_index_0 = [...]uint16{0, 1, 2, 4, 6, 8, 13, 16, 18, 20, 22, 26, 29, 32, 37, 42, 44, 47, 49, 54, 57, 61, 63, 67, 74, 77, 80, 82, 86, 90, 93, 96, 99, 101, 104, 108, 113, 115, 119, 121, 126, 130, 133, 136, 138, 143, 151, 156, 160, 166, 171, 176, 186, 190, 196, 198, 201, 206, 210, 216, 219, 226, 236, 241, 247, 251, 256}
	_Type_index_1 = [...]uint8{0, 5, 10}
	_Type_index_2 = [...]uint8{0, 4, 8, 12, 16, 21, 26, 29, 32, 35}
)

func (i Type) String() string {
	switch {
	case i <= 65:
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case 108 <= i && i <= 109:
		i -= 108
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	case 249 <= i && i <= 257:
		i -= 249
		return _Type_name_2[_Type_index_2[i]:_Type_index_2[i+1]]
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
