// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ixge -id rx_dma_queue -d VecType=rx_dma_queue_vec -d Type=rx_dma_queue github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ixge

import (
	"github.com/platinasystems/go/elib"
)

type rx_dma_queue_vec []rx_dma_queue

func (p *rx_dma_queue_vec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]rx_dma_queue, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *rx_dma_queue_vec) validate(new_len uint, zero rx_dma_queue) *rx_dma_queue {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *rx_dma_queue_vec) validateSlowPath(zero rx_dma_queue, old_cap, new_len, old_len uint) *rx_dma_queue {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]rx_dma_queue, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *rx_dma_queue_vec) Validate(i uint) *rx_dma_queue {
	var zero rx_dma_queue
	return p.validate(i+1, zero)
}

func (p *rx_dma_queue_vec) ValidateInit(i uint, zero rx_dma_queue) *rx_dma_queue {
	return p.validate(i+1, zero)
}

func (p *rx_dma_queue_vec) ValidateLen(l uint) (v *rx_dma_queue) {
	if l > 0 {
		var zero rx_dma_queue
		v = p.validate(l, zero)
	}
	return
}

func (p *rx_dma_queue_vec) ValidateLenInit(l uint, zero rx_dma_queue) (v *rx_dma_queue) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *rx_dma_queue_vec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p rx_dma_queue_vec) Len() uint { return uint(len(p)) }
