// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ixge -id tx_descriptor -d Type=tx_descriptor -d VecType=tx_descriptor_vec github.com/platinasystems/go/elib/hw/dma_mem.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ixge

import (
	"github.com/platinasystems/go/elib"
	"github.com/platinasystems/go/elib/hw"

	"reflect"
	"unsafe"
)

type tx_descriptor_vec []tx_descriptor

func fromByteSlice_tx_descriptor(b []byte, l, c uint) (x tx_descriptor_vec) {
	s := uint(unsafe.Sizeof(x[0]))
	if l == 0 {
		l = uint(len(b)) / s
		c = uint(cap(b))
	}
	return *(*tx_descriptor_vec)(unsafe.Pointer(&reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(&b[0])),
		Len:  int(l),
		Cap:  int(c / s),
	}))
}

func (x tx_descriptor_vec) toByteSlice() []byte {
	l := uint(len(x))
	l *= uint(unsafe.Sizeof(x[0]))
	return *(*[]byte)(unsafe.Pointer(&reflect.SliceHeader{
		Data: uintptr(unsafe.Pointer(&x[0])),
		Len:  int(l),
		Cap:  int(l)}))
}

func tx_descriptorAllocAligned(n, a uint) (x tx_descriptor_vec, id elib.Index) {
	var b []byte
	var c uint
	b, id, _, c = hw.DmaAllocAligned(n*uint(unsafe.Sizeof(x[0])), a)
	x = fromByteSlice_tx_descriptor(b, n, c)
	return
}

func tx_descriptorAlloc(n uint) (x tx_descriptor_vec, id elib.Index) {
	return tx_descriptorAllocAligned(n, 0)
}

func tx_descriptorNew() (x tx_descriptor_vec, id elib.Index) { return tx_descriptorAlloc(1) }

func (x *tx_descriptor_vec) Free(id elib.Index) {
	hw.DmaFree(id)
	*x = nil
}

func (x *tx_descriptor_vec) Get(id elib.Index) {
	*x = fromByteSlice_tx_descriptor(hw.DmaGetData(id), 0, 0)
}

func (x *tx_descriptor) PhysAddress() uintptr {
	return hw.DmaPhysAddress(uintptr(unsafe.Pointer(x)))
}
