apiVersion: v1
kind: Namespace
metadata:
  name: tuntapper
  labels:
    name: tuntapper
---
apiVersion: v1
kind: Pod
metadata:
  name: tuntapper
  namespace: tuntapper
  labels:
    app: tuntapper
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
    runAsGroup: 0
  containers:
  - name: tuntapper
    imagePullPolicy: IfNotPresent
    image: ko://github.com/platinasystems/goes/v2
    args: ["start", "tuntapper"]
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - NET_ADMIN
        - SYS_ADMIN
      privileged: true
