// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id errorThread -d VecType=errorThreadVec -d Type=*errorThread github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vnet

import (
	"github.com/platinasystems/go/elib"
)

type errorThreadVec []*errorThread

func (p *errorThreadVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]*errorThread, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *errorThreadVec) validate(new_len uint, zero *errorThread) **errorThread {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *errorThreadVec) validateSlowPath(zero *errorThread, old_cap, new_len, old_len uint) **errorThread {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]*errorThread, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *errorThreadVec) Validate(i uint) **errorThread {
	var zero *errorThread
	return p.validate(i+1, zero)
}

func (p *errorThreadVec) ValidateInit(i uint, zero *errorThread) **errorThread {
	return p.validate(i+1, zero)
}

func (p *errorThreadVec) ValidateLen(l uint) (v **errorThread) {
	if l > 0 {
		var zero *errorThread
		v = p.validate(l, zero)
	}
	return
}

func (p *errorThreadVec) ValidateLenInit(l uint, zero *errorThread) (v **errorThread) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *errorThreadVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p errorThreadVec) Len() uint { return uint(len(p)) }
