// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id HwIfProvisionHook -d Package=vnet -d DepsType=HwIfProvisionHookVec -d Type=HwIfProvisionHook -d Data=hooks github.com/platinasystems/go/elib/dep/dep.tmpl]

package vnet

import (
	"github.com/platinasystems/go/elib/dep"
)

type HwIfProvisionHookVec struct {
	deps  dep.Deps
	hooks []HwIfProvisionHook
}

func (t *HwIfProvisionHookVec) Len() int {
	return t.deps.Len()
}

func (t *HwIfProvisionHookVec) Get(i int) HwIfProvisionHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *HwIfProvisionHookVec) Add(x HwIfProvisionHook, ds ...*dep.Dep) {
	if len(ds) == 0 {
		t.deps.Add(&dep.Dep{})
	} else {
		t.deps.Add(ds[0])
	}
	t.hooks = append(t.hooks, x)
}
