// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id HwIfLinkUpDownHook -d Package=vnet -d DepsType=HwIfLinkUpDownHookVec -d Type=HwIfLinkUpDownHook -d Data=hooks github.com/platinasystems/go/elib/dep/dep.tmpl]

package vnet

import (
	"github.com/platinasystems/go/elib/dep"
)

type HwIfLinkUpDownHookVec struct {
	deps  dep.Deps
	hooks []HwIfLinkUpDownHook
}

func (t *HwIfLinkUpDownHookVec) Len() int {
	return t.deps.Len()
}

func (t *HwIfLinkUpDownHookVec) Get(i int) HwIfLinkUpDownHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *HwIfLinkUpDownHookVec) Add(x HwIfLinkUpDownHook, ds ...*dep.Dep) {
	if len(ds) == 0 {
		t.deps.Add(&dep.Dep{})
	} else {
		t.deps.Add(ds[0])
	}
	t.hooks = append(t.hooks, x)
}
