// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id SwIfAddDelHook -d Package=vnet -d DepsType=SwIfAddDelHookVec -d Type=SwIfAddDelHook -d Data=hooks github.com/platinasystems/go/elib/dep/dep.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vnet

import (
	"github.com/platinasystems/go/elib/dep"
)

type SwIfAddDelHookVec struct {
	deps  dep.Deps
	hooks []SwIfAddDelHook
}

func (t *SwIfAddDelHookVec) Len() int {
	return t.deps.Len()
}

func (t *SwIfAddDelHookVec) Get(i int) SwIfAddDelHook {
	return t.hooks[t.deps.Index(i)]
}

func (t *SwIfAddDelHookVec) Add(x SwIfAddDelHook, ds ...*dep.Dep) {
	if len(ds) == 0 {
		t.deps.Add(&dep.Dep{})
	} else {
		t.deps.Add(ds[0])
	}
	t.hooks = append(t.hooks, x)
}
