// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id CombinedCounter -d VecType=CombinedCounterVec -d Type=CombinedCounter github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vnet

import (
	"github.com/platinasystems/go/elib"
)

type CombinedCounterVec []CombinedCounter

func (p *CombinedCounterVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]CombinedCounter, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *CombinedCounterVec) validate(new_len uint, zero CombinedCounter) *CombinedCounter {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *CombinedCounterVec) validateSlowPath(zero CombinedCounter, old_cap, new_len, old_len uint) *CombinedCounter {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]CombinedCounter, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *CombinedCounterVec) Validate(i uint) *CombinedCounter {
	var zero CombinedCounter
	return p.validate(i+1, zero)
}

func (p *CombinedCounterVec) ValidateInit(i uint, zero CombinedCounter) *CombinedCounter {
	return p.validate(i+1, zero)
}

func (p *CombinedCounterVec) ValidateLen(l uint) (v *CombinedCounter) {
	if l > 0 {
		var zero CombinedCounter
		v = p.validate(l, zero)
	}
	return
}

func (p *CombinedCounterVec) ValidateLenInit(l uint, zero CombinedCounter) (v *CombinedCounter) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *CombinedCounterVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p CombinedCounterVec) Len() uint { return uint(len(p)) }
