// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id Ref -d VecType=RefVec -d Type=Ref github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vnet

import (
	"github.com/platinasystems/go/elib"
)

type RefVec []Ref

func (p *RefVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]Ref, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *RefVec) validate(new_len uint, zero Ref) *Ref {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *RefVec) validateSlowPath(zero Ref, old_cap, new_len, old_len uint) *Ref {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]Ref, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *RefVec) Validate(i uint) *Ref {
	var zero Ref
	return p.validate(i+1, zero)
}

func (p *RefVec) ValidateInit(i uint, zero Ref) *Ref {
	return p.validate(i+1, zero)
}

func (p *RefVec) ValidateLen(l uint) (v *Ref) {
	if l > 0 {
		var zero Ref
		v = p.validate(l, zero)
	}
	return
}

func (p *RefVec) ValidateLenInit(l uint, zero Ref) (v *Ref) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *RefVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p RefVec) Len() uint { return uint(len(p)) }
