// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id error -d VecType=errVec -d Type=err github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vnet

import (
	"github.com/platinasystems/go/elib"
)

type errVec []err

func (p *errVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]err, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *errVec) validate(new_len uint, zero err) *err {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *errVec) validateSlowPath(zero err, c, l, lʹ elib.Index) *err {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]err, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *errVec) Validate(i uint) *err {
	var zero err
	return p.validate(i+1, zero)
}

func (p *errVec) ValidateInit(i uint, zero err) *err {
	return p.validate(i+1, zero)
}

func (p *errVec) ValidateLen(l uint) (v *err) {
	if l > 0 {
		var zero err
		v = p.validate(l, zero)
	}
	return
}

func (p *errVec) ValidateLenInit(l uint, zero err) (v *err) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p errVec) Len() uint { return uint(len(p)) }
