// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id enqueue -d VecType=enqueue_vec -d Type=*enqueue github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vnet

import (
	"github.com/platinasystems/go/elib"
)

type enqueue_vec []*enqueue

func (p *enqueue_vec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]*enqueue, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *enqueue_vec) validate(new_len uint, zero *enqueue) **enqueue {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *enqueue_vec) validateSlowPath(zero *enqueue, old_cap, new_len, old_len uint) **enqueue {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]*enqueue, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *enqueue_vec) Validate(i uint) **enqueue {
	var zero *enqueue
	return p.validate(i+1, zero)
}

func (p *enqueue_vec) ValidateInit(i uint, zero *enqueue) **enqueue {
	return p.validate(i+1, zero)
}

func (p *enqueue_vec) ValidateLen(l uint) (v **enqueue) {
	if l > 0 {
		var zero *enqueue
		v = p.validate(l, zero)
	}
	return
}

func (p *enqueue_vec) ValidateLenInit(l uint, zero *enqueue) (v **enqueue) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *enqueue_vec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p enqueue_vec) Len() uint { return uint(len(p)) }
