// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id CombinedCounter -d VecType=CombinedCounterVec -d Type=CombinedCounter github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vnet

import (
	"github.com/platinasystems/go/elib"
)

type CombinedCounterVec []CombinedCounter

func (p *CombinedCounterVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]CombinedCounter, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *CombinedCounterVec) validate(new_len uint, zero CombinedCounter) *CombinedCounter {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *CombinedCounterVec) validateSlowPath(zero CombinedCounter, c, l, lʹ elib.Index) *CombinedCounter {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]CombinedCounter, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *CombinedCounterVec) Validate(i uint) *CombinedCounter {
	var zero CombinedCounter
	return p.validate(i+1, zero)
}

func (p *CombinedCounterVec) ValidateInit(i uint, zero CombinedCounter) *CombinedCounter {
	return p.validate(i+1, zero)
}

func (p *CombinedCounterVec) ValidateLen(l uint) (v *CombinedCounter) {
	if l > 0 {
		var zero CombinedCounter
		v = p.validate(l, zero)
	}
	return
}

func (p *CombinedCounterVec) ValidateLenInit(l uint, zero CombinedCounter) (v *CombinedCounter) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *CombinedCounterVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p CombinedCounterVec) Len() uint { return uint(len(p)) }
