// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=vnet -id RefOpaque -d PoolType=RefOpaquePool -d Type=RefOpaque -d Data=Entries github.com/platinasystems/go/elib/pool.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package vnet

import (
	"github.com/platinasystems/go/elib"
)

type RefOpaquePool struct {
	elib.Pool
	Entries []RefOpaque
}

func (p *RefOpaquePool) GetIndex() (i uint) {
	l := uint(len(p.Entries))
	i = p.Pool.GetIndex(l)
	if i >= l {
		p.Validate(i)
	}
	return i
}

func (p *RefOpaquePool) PutIndex(i uint) (ok bool) {
	return p.Pool.PutIndex(i)
}

func (p *RefOpaquePool) IsFree(i uint) (v bool) {
	v = i >= uint(len(p.Entries))
	if !v {
		v = p.Pool.IsFree(i)
	}
	return
}

func (p *RefOpaquePool) Resize(n uint) {
	c := elib.Index(cap(p.Entries))
	l := elib.Index(len(p.Entries) + int(n))
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]RefOpaque, l, c)
		copy(q, p.Entries)
		p.Entries = q
	}
	p.Entries = p.Entries[:l]
}

func (p *RefOpaquePool) Validate(i uint) {
	c := elib.Index(cap(p.Entries))
	l := elib.Index(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]RefOpaque, l, c)
		copy(q, p.Entries)
		p.Entries = q
	}
	if l > elib.Index(len(p.Entries)) {
		p.Entries = p.Entries[:l]
	}
}

func (p *RefOpaquePool) Elts() uint {
	return uint(len(p.Entries)) - p.FreeLen()
}

func (p *RefOpaquePool) Len() uint {
	return uint(len(p.Entries))
}

func (p *RefOpaquePool) Foreach(f func(x RefOpaque)) {
	for i := range p.Entries {
		if !p.Pool.IsFree(uint(i)) {
			f(p.Entries[i])
		}
	}
}

func (p *RefOpaquePool) ForeachIndex(f func(i uint)) {
	for i := range p.Entries {
		if !p.Pool.IsFree(uint(i)) {
			f(uint(i))
		}
	}
}
