// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=mctree -id Pair -d VecType=pair_vec -d Type=Pair github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package mctree

import (
	"github.com/platinasystems/go/elib"
)

type pair_vec []Pair

func (p *pair_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Pair, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *pair_vec) validate(new_len uint, zero Pair) *Pair {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *pair_vec) validateSlowPath(zero Pair, c, l, lʹ elib.Index) *Pair {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Pair, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *pair_vec) Validate(i uint) *Pair {
	var zero Pair
	return p.validate(i+1, zero)
}

func (p *pair_vec) ValidateInit(i uint, zero Pair) *Pair {
	return p.validate(i+1, zero)
}

func (p *pair_vec) ValidateLen(l uint) (v *Pair) {
	if l > 0 {
		var zero Pair
		v = p.validate(l, zero)
	}
	return
}

func (p *pair_vec) ValidateLenInit(l uint, zero Pair) (v *Pair) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *pair_vec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p pair_vec) Len() uint { return uint(len(p)) }
