// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=mctree -id Pair -d VecType=pair_vec -d Type=Pair github.com/platinasystems/go/elib/vec.tmpl]

package mctree

import (
	"github.com/platinasystems/go/elib"
)

type pair_vec []Pair

func (p *pair_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Pair, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *pair_vec) validate(new_len uint, zero *Pair) *Pair {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *pair_vec) validateSlowPath(zero *Pair,
	c, l, lʹ elib.Index) *Pair {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Pair, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *pair_vec) Validate(i uint) *Pair {
	return p.validate(i+1, (*Pair)(nil))
}

func (p *pair_vec) ValidateInit(i uint, zero Pair) *Pair {
	return p.validate(i+1, &zero)
}

func (p *pair_vec) ValidateLen(l uint) (v *Pair) {
	if l > 0 {
		v = p.validate(l, (*Pair)(nil))
	}
	return
}

func (p *pair_vec) ValidateLenInit(l uint, zero Pair) (v *Pair) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p pair_vec) Len() uint { return uint(len(p)) }
