// Copyright © 2015-2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

package rtnl

const (
	LWTUNNEL_ENCAP_NONE uint16 = iota
	LWTUNNEL_ENCAP_MPLS
	LWTUNNEL_ENCAP_IP
	LWTUNNEL_ENCAP_ILA
	LWTUNNEL_ENCAP_IP6
	LWTUNNEL_ENCAP_SEG6
	LWTUNNEL_ENCAP_BPF
	N_LWTUNNEL_ENCAP
)

const LWTUNNEL_ENCAP_MAX = N_LWTUNNEL_ENCAP - 1

const (
	LWTUNNEL_IP_UNSPEC uint16 = iota
	LWTUNNEL_IP_ID
	LWTUNNEL_IP_DST
	LWTUNNEL_IP_SRC
	LWTUNNEL_IP_TTL
	LWTUNNEL_IP_TOS
	LWTUNNEL_IP_FLAGS
	LWTUNNEL_IP_PAD
	N_LWTUNNEL_IP
)

const LWTUNNEL_IP_MAX = N_LWTUNNEL_IP - 1

const (
	LWTUNNEL_IP6_UNSPEC uint16 = iota
	LWTUNNEL_IP6_ID
	LWTUNNEL_IP6_DST
	LWTUNNEL_IP6_SRC
	LWTUNNEL_IP6_HOPLIMIT
	LWTUNNEL_IP6_TC
	LWTUNNEL_IP6_FLAGS
	LWTUNNEL_IP6_PAD
	N_LWTUNNEL_IP6
)

const LWTUNNEL_IP6_MAX = N_LWTUNNEL_IP6 - 1

const (
	LWT_BPF_PROG_UNSPEC uint16 = iota
	LWT_BPF_PROG_FD
	LWT_BPF_PROG_NAME
	N_LWT_BPF_PROG
)

const LWT_BPF_PROG_MAX = N_LWT_BPF_PROG - 1

const (
	LWT_BPF_UNSPEC uint16 = iota
	LWT_BPF_IN
	LWT_BPF_OUT
	LWT_BPF_XMIT
	LWT_BPF_XMIT_HEADROOM
	N_LWT_BPF
)

const LWT_BPF_MAX = N_LWT_BPF - 1

const LWT_BPF_MAX_HEADROOM = 256
