1i\
// Code generated by "go doc syscall.IFT_OTHER | sed -n -f ift.sed | gofmt"\
// DO NOT EDIT.\
\
package netioctl\
\
type IFT uint16\
\
const (
s/^\t\(IFT_[^=]*\)\(= 0x[[:xdigit:]]*\)$/\t\1IFT \2/p
$a\
)
