// Code generated by "stringer -output=zifcap_string_darwin.go -type=IFCAP -trimprefix=IFCAP_ ."; DO NOT EDIT.

package netioctl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IFCAP_RXCSUM-1]
	_ = x[IFCAP_TXCSUM-2]
	_ = x[IFCAP_VLAN_MTU-4]
	_ = x[IFCAP_VLAN_HWTAGGING-8]
	_ = x[IFCAP_JUMBO_MTU-16]
	_ = x[IFCAP_TSO4-32]
	_ = x[IFCAP_TSO6-64]
	_ = x[IFCAP_LRO-128]
	_ = x[IFCAP_AV-256]
	_ = x[IFCAP_TXSTATUS-512]
	_ = x[IFCAP_SKYWALK-1024]
	_ = x[IFCAP_HW_TIMESTAMP-2048]
	_ = x[IFCAP_SW_TIMESTAMP-4096]
	_ = x[IFCAP_CSUM_PARTIAL-8192]
	_ = x[IFCAP_CSUM_ZERO_INVERT-16384]
}

const _IFCAP_name = "RXCSUMTXCSUMVLAN_MTUVLAN_HWTAGGINGJUMBO_MTUTSO4TSO6LROAVTXSTATUSSKYWALKHW_TIMESTAMPSW_TIMESTAMPCSUM_PARTIALCSUM_ZERO_INVERT"

var _IFCAP_map = map[IFCAP]string{
	1:     _IFCAP_name[0:6],
	2:     _IFCAP_name[6:12],
	4:     _IFCAP_name[12:20],
	8:     _IFCAP_name[20:34],
	16:    _IFCAP_name[34:43],
	32:    _IFCAP_name[43:47],
	64:    _IFCAP_name[47:51],
	128:   _IFCAP_name[51:54],
	256:   _IFCAP_name[54:56],
	512:   _IFCAP_name[56:64],
	1024:  _IFCAP_name[64:71],
	2048:  _IFCAP_name[71:83],
	4096:  _IFCAP_name[83:95],
	8192:  _IFCAP_name[95:107],
	16384: _IFCAP_name[107:123],
}

func (i IFCAP) String() string {
	if str, ok := _IFCAP_map[i]; ok {
		return str
	}
	return "IFCAP(" + strconv.FormatInt(int64(i), 10) + ")"
}
