// Code generated by "go doc syscall.IFT_OTHER | sed -n -f ift.sed | gofmt"
// DO NOT EDIT.

package netioctl

type IFT uint16

const (
	IFT_1822          IFT = 0x2
	IFT_AAL5          IFT = 0x31
	IFT_ARCNET        IFT = 0x23
	IFT_ARCNETPLUS    IFT = 0x24
	IFT_ATM           IFT = 0x25
	IFT_BRIDGE        IFT = 0xd1
	IFT_CARP          IFT = 0xf8
	IFT_CELLULAR      IFT = 0xff
	IFT_CEPT          IFT = 0x13
	IFT_DS3           IFT = 0x1e
	IFT_ENC           IFT = 0xf4
	IFT_EON           IFT = 0x19
	IFT_ETHER         IFT = 0x6
	IFT_FAITH         IFT = 0x38
	IFT_FDDI          IFT = 0xf
	IFT_FRELAY        IFT = 0x20
	IFT_FRELAYDCE     IFT = 0x2c
	IFT_GIF           IFT = 0x37
	IFT_HDH1822       IFT = 0x3
	IFT_HIPPI         IFT = 0x2f
	IFT_HSSI          IFT = 0x2e
	IFT_HY            IFT = 0xe
	IFT_IEEE1394      IFT = 0x90
	IFT_IEEE8023ADLAG IFT = 0x88
	IFT_ISDNBASIC     IFT = 0x14
	IFT_ISDNPRIMARY   IFT = 0x15
	IFT_ISO88022LLC   IFT = 0x29
	IFT_ISO88023      IFT = 0x7
	IFT_ISO88024      IFT = 0x8
	IFT_ISO88025      IFT = 0x9
	IFT_ISO88026      IFT = 0xa
	IFT_L2VLAN        IFT = 0x87
	IFT_LAPB          IFT = 0x10
	IFT_LOCALTALK     IFT = 0x2a
	IFT_LOOP          IFT = 0x18
	IFT_MIOX25        IFT = 0x26
	IFT_MODEM         IFT = 0x30
	IFT_NSIP          IFT = 0x1b
	IFT_OTHER         IFT = 0x1
	IFT_P10           IFT = 0xc
	IFT_P80           IFT = 0xd
	IFT_PARA          IFT = 0x22
	IFT_PDP           IFT = 0xff
	IFT_PFLOG         IFT = 0xf5
	IFT_PFSYNC        IFT = 0xf6
	IFT_PPP           IFT = 0x17
	IFT_PROPMUX       IFT = 0x36
	IFT_PROPVIRTUAL   IFT = 0x35
	IFT_PTPSERIAL     IFT = 0x16
	IFT_RS232         IFT = 0x21
	IFT_SDLC          IFT = 0x11
	IFT_SIP           IFT = 0x1f
	IFT_SLIP          IFT = 0x1c
	IFT_SMDSDXI       IFT = 0x2b
	IFT_SMDSICIP      IFT = 0x34
	IFT_SONET         IFT = 0x27
	IFT_SONETPATH     IFT = 0x32
	IFT_SONETVT       IFT = 0x33
	IFT_STARLAN       IFT = 0xb
	IFT_STF           IFT = 0x39
	IFT_T1            IFT = 0x12
	IFT_ULTRA         IFT = 0x1d
	IFT_V35           IFT = 0x2d
	IFT_X25           IFT = 0x5
	IFT_X25DDN        IFT = 0x4
	IFT_X25PLE        IFT = 0x28
	IFT_XETHER        IFT = 0x1a
)
