// Code generated by "stringer -output=zift_string_darwin.go -type=IFT -trimprefix=IFT_ ."; DO NOT EDIT.

package netioctl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IFT_1822-2]
	_ = x[IFT_AAL5-49]
	_ = x[IFT_ARCNET-35]
	_ = x[IFT_ARCNETPLUS-36]
	_ = x[IFT_ATM-37]
	_ = x[IFT_BRIDGE-209]
	_ = x[IFT_CARP-248]
	_ = x[IFT_CELLULAR-255]
	_ = x[IFT_CEPT-19]
	_ = x[IFT_DS3-30]
	_ = x[IFT_ENC-244]
	_ = x[IFT_EON-25]
	_ = x[IFT_ETHER-6]
	_ = x[IFT_FAITH-56]
	_ = x[IFT_FDDI-15]
	_ = x[IFT_FRELAY-32]
	_ = x[IFT_FRELAYDCE-44]
	_ = x[IFT_GIF-55]
	_ = x[IFT_HDH1822-3]
	_ = x[IFT_HIPPI-47]
	_ = x[IFT_HSSI-46]
	_ = x[IFT_HY-14]
	_ = x[IFT_IEEE1394-144]
	_ = x[IFT_IEEE8023ADLAG-136]
	_ = x[IFT_ISDNBASIC-20]
	_ = x[IFT_ISDNPRIMARY-21]
	_ = x[IFT_ISO88022LLC-41]
	_ = x[IFT_ISO88023-7]
	_ = x[IFT_ISO88024-8]
	_ = x[IFT_ISO88025-9]
	_ = x[IFT_ISO88026-10]
	_ = x[IFT_L2VLAN-135]
	_ = x[IFT_LAPB-16]
	_ = x[IFT_LOCALTALK-42]
	_ = x[IFT_LOOP-24]
	_ = x[IFT_MIOX25-38]
	_ = x[IFT_MODEM-48]
	_ = x[IFT_NSIP-27]
	_ = x[IFT_OTHER-1]
	_ = x[IFT_P10-12]
	_ = x[IFT_P80-13]
	_ = x[IFT_PARA-34]
	_ = x[IFT_PDP-255]
	_ = x[IFT_PFLOG-245]
	_ = x[IFT_PFSYNC-246]
	_ = x[IFT_PPP-23]
	_ = x[IFT_PROPMUX-54]
	_ = x[IFT_PROPVIRTUAL-53]
	_ = x[IFT_PTPSERIAL-22]
	_ = x[IFT_RS232-33]
	_ = x[IFT_SDLC-17]
	_ = x[IFT_SIP-31]
	_ = x[IFT_SLIP-28]
	_ = x[IFT_SMDSDXI-43]
	_ = x[IFT_SMDSICIP-52]
	_ = x[IFT_SONET-39]
	_ = x[IFT_SONETPATH-50]
	_ = x[IFT_SONETVT-51]
	_ = x[IFT_STARLAN-11]
	_ = x[IFT_STF-57]
	_ = x[IFT_T1-18]
	_ = x[IFT_ULTRA-29]
	_ = x[IFT_V35-45]
	_ = x[IFT_X25-5]
	_ = x[IFT_X25DDN-4]
	_ = x[IFT_X25PLE-40]
	_ = x[IFT_XETHER-26]
}

const (
	_IFT_name_0 = "OTHER1822HDH1822X25DDNX25ETHERISO88023ISO88024ISO88025ISO88026STARLANP10P80HYFDDILAPBSDLCT1CEPTISDNBASICISDNPRIMARYPTPSERIALPPPLOOPEONXETHERNSIPSLIPULTRADS3SIPFRELAYRS232PARAARCNETARCNETPLUSATMMIOX25SONETX25PLEISO88022LLCLOCALTALKSMDSDXIFRELAYDCEV35HSSIHIPPIMODEMAAL5SONETPATHSONETVTSMDSICIPPROPVIRTUALPROPMUXGIFFAITHSTF"
	_IFT_name_1 = "L2VLANIEEE8023ADLAG"
	_IFT_name_2 = "IEEE1394"
	_IFT_name_3 = "BRIDGE"
	_IFT_name_4 = "ENCPFLOGPFSYNC"
	_IFT_name_5 = "CARP"
	_IFT_name_6 = "CELLULAR"
)

var (
	_IFT_index_0 = [...]uint16{0, 5, 9, 16, 22, 25, 30, 38, 46, 54, 62, 69, 72, 75, 77, 81, 85, 89, 91, 95, 104, 115, 124, 127, 131, 134, 140, 144, 148, 153, 156, 159, 165, 170, 174, 180, 190, 193, 199, 204, 210, 221, 230, 237, 246, 249, 253, 258, 263, 267, 276, 283, 291, 302, 309, 312, 317, 320}
	_IFT_index_1 = [...]uint8{0, 6, 19}
	_IFT_index_4 = [...]uint8{0, 3, 8, 14}
)

func (i IFT) String() string {
	switch {
	case 1 <= i && i <= 57:
		i -= 1
		return _IFT_name_0[_IFT_index_0[i]:_IFT_index_0[i+1]]
	case 135 <= i && i <= 136:
		i -= 135
		return _IFT_name_1[_IFT_index_1[i]:_IFT_index_1[i+1]]
	case i == 144:
		return _IFT_name_2
	case i == 209:
		return _IFT_name_3
	case 244 <= i && i <= 246:
		i -= 244
		return _IFT_name_4[_IFT_index_4[i]:_IFT_index_4[i+1]]
	case i == 248:
		return _IFT_name_5
	case i == 255:
		return _IFT_name_6
	default:
		return "IFT(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
