package sysctl

const (
	KERN_UNUSED = iota
	KERN_OSTYPE
	KERN_OSRELEASE
	KERN_OSREV
	KERN_VERSION
	KERN_MAXVNODES
	KERN_MAXPROC
	KERN_MAXFILES
	KERN_ARGMAX
	KERN_SECURELVL
	KERN_HOSTNAME
	KERN_HOSTID
	KERN_CLOCKRATE
	KERN_VNODE
	KERN_PROC
	KERN_FILE
	KERN_PROF
	KERN_POSIX1
	KERN_NGROUPS
	KERN_JOB_CONTROL
	KERN_SAVED_IDS
	KERN_BOOTTIME
	KERN_NISDOMAINNAME
	KERN_MAXPARTITIONS
	KERN_KDEBUG
	KERN_UPDATEINTERVAL
	KERN_OSRELDATE
	KERN_NTP_PLL
	KERN_BOOTFILE
	KERN_MAXFILESPERPROC
	KERN_MAXPROCPERUID
	KERN_DUMPDEV
	KERN_IPC
	KERN_DUMMY
	KERN_PS_STRINGS
	KERN_USRSTACK32
	KERN_LOGSIGEXIT
	KERN_SYMFILE
	KERN_PROCARGS
	KERN_NETBOOT
	KERN_SYSV
	KERN_AFFINITY
	KERN_TRANSLATE
	KERN_EXEC
	KERN_AIOMAX
	KERN_AIOPROCMAX
	KERN_AIOTHREADS
	KERN_PROCARGS2
	KERN_COREFILE
	KERN_COREDUMP
	KERN_SUGID_COREDUMP
	KERN_PROCDELAYTERM
	KERN_SHREG_PRIVATIZABLE
	KERN_LOW_PRI_WINDOW
	KERN_LOW_PRI_DELAY
	KERN_POSIX
	KERN_USRSTACK64
	KERN_NX_PROTECTION
	KERN_TFP
	KERN_PROCNAME
	KERN_THALTSTACK
	KERN_SPECULATIVE_READS
	KERN_OSVERSION
	KERN_SAFEBOOT
	KERN_RAGEVNODE
	KERN_TTY
	KERN_CHECKOPENEVT
	KERN_THREADNAME
	KERN_MAXID
)

const (
	KERN_DOMAINNAME     = KERN_NISDOMAINNAME
	KERN_CLASSIC        = KERN_TRANSLATE
	KERN_CLASSICHANDLER = KERN_EXEC
)

const (
	KERN_PROC_ALL = iota
	KERN_PROC_PID
	KERN_PROC_PGRP
	KERN_PROC_SESSION
	KERN_PROC_TTY
	KERN_PROC_UID
	KERN_PROC_RUID
	KERN_PROC_LCID
)
