package sysctl

const (
	KERN_UNUSED = iota
	KERN_OSTYPE
	KERN_OSRELEASE
	KERN_OSREV
	KERN_VERSION
	KERN_MAXVNODES
	KERN_MAXPROC
	KERN_MAXFILES
	KERN_ARGMAX
	KERN_SECURELVL
	KERN_HOSTNAME
	KERN_HOSTID
	KERN_CLOCKRATE
	KERN_VNODE
	KERN_PROC
	KERN_FILE
	KERN_PROF
	KERN_POSIX1
	KERN_NGROUPS
	KERN_JOB_CONTROL
	KERN_SAVED_IDS
	KERN_BOOTTIME
	KERN_NISDOMAINNAME
	KERN_UPDATEINTERVAL
	KERN_OSRELDATE
	KERN_NTP_PLL
	KERN_BOOTFILE
	KERN_MAXFILESPERPROC
	KERN_MAXPROCPERUID
	KERN_DUMPDEV
	KERN_IPC
	KERN_DUMMY
	KERN_PS_STRINGS
	KERN_USRSTACK
	KERN_LOGSIGEXIT
	KERN_IOV_MAX
	KERN_HOSTUUID
	KERN_ARND
	KERN_MAXPHYS
	KERN_LOCKF
	KERN_MAXID
)

const (
	KERN_PROC_ALL = iota
	KERN_PROC_PID
	KERN_PROC_PGRP
	KERN_PROC_SESSION
	KERN_PROC_TTY
	KERN_PROC_UID
	KERN_PROC_RUID
	KERN_PROC_ARGS
	KERN_PROC_PROC
	KERN_PROC_SV_NAME
	KERN_PROC_RGID
	KERN_PROC_GID
	KERN_PROC_PATHNAME
	KERN_PROC_OVMMAP
	KERN_PROC_OFILEDESC
	KERN_PROC_KSTACK
	KERN_PROC_INC_THREAD
)

const (
	KERN_PROC_VMMAP = 32 + iota
	KERN_PROC_FILEDESC
	KERN_PROC_GROUPS
	KERN_PROC_ENV
	KERN_PROC_AUXV
	KERN_PROC_RLIMIT
	KERN_PROC_PS_STRINGS
	KERN_PROC_UMASK
	KERN_PROC_OSREL
	KERN_PROC_SIGTRAMP
	KERN_PROC_CWD
	KERN_PROC_NFDS
	KERN_PROC_SIGFASTBLK
	KERN_PROC_VM_LAYOUT
)
