// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=parse -id save -d VecType=saveVec -d Type=save github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package parse

import (
	"github.com/platinasystems/go/elib"
)

type saveVec []save

func (p *saveVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]save, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *saveVec) validate(new_len uint, zero save) *save {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *saveVec) validateSlowPath(zero save, c, l, lʹ uint) *save {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]save, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *saveVec) Validate(i uint) *save {
	var zero save
	return p.validate(i+1, zero)
}

func (p *saveVec) ValidateInit(i uint, zero save) *save {
	return p.validate(i+1, zero)
}

func (p *saveVec) ValidateLen(l uint) (v *save) {
	if l > 0 {
		var zero save
		v = p.validate(l, zero)
	}
	return
}

func (p *saveVec) ValidateLenInit(l uint, zero save) (v *save) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *saveVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p saveVec) Len() uint { return uint(len(p)) }
