// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- /home/tgrennan/tuntap/godefs_linux.go

package tuntap

const (
	IFNAMSIZ	= 0x10
	IFF_TAP		= 0x2
	IFF_TUN		= 0x1
)

type Ifreq struct {
	Ifrn	[16]byte
	Ifru	[24]byte
}
type Sockaddr struct {
	Family	uint16
	Data	[14]int8
}
