// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- godefs_darwin.go

package tuntap

const (
	UTUN_CONTROL_NAME	= "com.apple.net.utun_control"
	UTUN_OPT_IFNAME		= 0x2
	IFNAMSIZ		= 0x10
	AF_SYS_CONTROL		= 0x2
	AF_SYSTEM		= 0x20
	PF_SYSTEM		= 0x20
	SYSPROTO_CONTROL	= 0x2
	CTLIOCGINFO		= 0xc0644e03
)

type CtlInfo struct {
	Id	uint32
	Name	[96]int8
}

const SizeofCtlInfo = 0x64

type SockaddrCtl struct {
	Sc_len		uint8
	Sc_family	uint8
	Ss_sysaddr	uint16
	Sc_id		uint32
	Sc_unit		uint32
	Sc_reserved	[5]uint32
}

const SizeofSockaddrCtl = 0x20
