// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elog -id genEvent -d Type=genEvent github.com/platinasystems/go/elib/elog/event.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elog

import ()

var genEventType = &EventType{
	Name: "elog.genEvent",
}

func init() {
	t := genEventType
	t.Strings = stringer_genEvent
	t.Encode = encode_genEvent
	t.Decode = decode_genEvent
	RegisterType(genEventType)
}

func stringer_genEvent(c *Context, e *Event) []string {
	var x genEvent
	x.Decode(c, e.Data[:])
	return x.Strings(c)
}

func encode_genEvent(c *Context, e *Event, b []byte) int {
	var x genEvent
	x.Decode(c, e.Data[:])
	return x.Encode(c, b)
}

func decode_genEvent(c *Context, e *Event, b []byte) int {
	var x genEvent
	x.Decode(c, b)
	return x.Encode(c, e.Data[:])
}

func (x genEvent) log_genEvent(b *Buffer, r Caller) {
	e := b.Add(genEventType, r)
	x.Encode(b.GetContext(), e.Data[:])
}

func (x genEvent) Log() {
	r := GetCaller(PointerToFirstArg(&x))
	x.log_genEvent(DefaultBuffer, r)
}

func (x genEvent) Logc(r Caller) {
	x.log_genEvent(DefaultBuffer, r)
}

func (x genEvent) Logb(b *Buffer) {
	r := GetCaller(PointerToFirstArg(&x))
	x.log_genEvent(b, r)
}

func (x genEvent) Logbc(b *Buffer, r Caller) {
	x.log_genEvent(b, r)
}
