// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elog -id Event -d VecType=EventVec -d Type=Event github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elog

import (
	"github.com/platinasystems/go/elib"
)

type EventVec []Event

func (p *EventVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]Event, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *EventVec) validate(new_len uint, zero Event) *Event {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *EventVec) validateSlowPath(zero Event, c, l, lʹ elib.Index) *Event {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]Event, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *EventVec) Validate(i uint) *Event {
	var zero Event
	return p.validate(i+1, zero)
}

func (p *EventVec) ValidateInit(i uint, zero Event) *Event {
	return p.validate(i+1, zero)
}

func (p *EventVec) ValidateLen(l uint) (v *Event) {
	if l > 0 {
		var zero Event
		v = p.validate(l, zero)
	}
	return
}

func (p *EventVec) ValidateLenInit(l uint, zero Event) (v *Event) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p EventVec) Len() uint { return uint(len(p)) }
