// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=elog -id Event -d VecType=bufferEventVec -d Type=bufferEvent github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package elog

import (
	"github.com/platinasystems/go/elib"
)

type bufferEventVec []bufferEvent

func (p *bufferEventVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]bufferEvent, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *bufferEventVec) validate(new_len uint, zero bufferEvent) *bufferEvent {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *bufferEventVec) validateSlowPath(zero bufferEvent, c, l, lʹ uint) *bufferEvent {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]bufferEvent, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *bufferEventVec) Validate(i uint) *bufferEvent {
	var zero bufferEvent
	return p.validate(i+1, zero)
}

func (p *bufferEventVec) ValidateInit(i uint, zero bufferEvent) *bufferEvent {
	return p.validate(i+1, zero)
}

func (p *bufferEventVec) ValidateLen(l uint) (v *bufferEvent) {
	if l > 0 {
		var zero bufferEvent
		v = p.validate(l, zero)
	}
	return
}

func (p *bufferEventVec) ValidateLenInit(l uint, zero bufferEvent) (v *bufferEvent) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *bufferEventVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p bufferEventVec) Len() uint { return uint(len(p)) }
