// Copyright © 2023 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

//go:build ignore

package netioctl

/*
#include <netinet6/in6_var.h>
#include <netinet6/nd6.h>
*/
import "C"

const (
	SIOCGIFADDR_IN6    = C.SIOCGIFADDR_IN6
	SIOCSIFADDR_IN6    = C.SIOCSIFADDR_IN6
	SIOCAIFADDR_IN6    = C.SIOCAIFADDR_IN6
	SIOCDIFADDR_IN6    = C.SIOCDIFADDR_IN6
	SIOCGIFNETMASK_IN6 = C.SIOCGIFNETMASK_IN6
	SIOCSIFNETMASK_IN6 = C.SIOCSIFNETMASK_IN6
	SIOCGIFDSTADDR_IN6 = C.SIOCGIFDSTADDR_IN6
	SIOCSIFDSTADDR_IN6 = C.SIOCSIFDSTADDR_IN6
	SIOCGIFAFLAG_IN6   = C.SIOCGIFAFLAG_IN6
	SIOCGIFSTAT_IN6    = C.SIOCGIFSTAT_IN6
	SIOCGIFSTAT_ICMP6  = C.SIOCGIFSTAT_ICMP6
	SIOCGSCOPE6        = C.SIOCGSCOPE6
	SIOCSSCOPE6        = C.SIOCSSCOPE6
)
