#!/bin/sh

set -e

prog=${0##*/}
usage="${prog} [-v]"

goes=`go list -f '{{.Dir}}' github.com/platinasystems/go/goes`
bin=${goes%/*}/bin
scripts=${goes%/*}/scripts
dir=${0%/*}
verbose=:
for arg; do
	case $arg in
	-v | -verbose | --verbose)
		verbose=echo
		;;
	-h | -help | --help)
		echo usage: $usage
		exit 0
		;;
	*)	echo $arg: unknown >/dev/stderr
		echo usage: $usage > /dev/stderr
		exit 1
	esac
done

mkdir -p $bin
eval $verbose version...
go generate github.com/platinasystems/go/version
eval $verbose bin/goes-example...
go build -o $bin/goes-example \
	github.com/platinasystems/go/goes/goes-example
eval $verbose goes-example-amd64.cpio.xz...
$scripts/mkinitrd github.com/platinasystems/go/goes/goes-example
eval $verbose goes-example-arm.cpio.xz...
env GOARCH=arm $scripts/mkinitrd github.com/platinasystems/go/goes/goes-example
eval $verbose bin/goes-platina-mk1...
go build -o $bin/goes-platina-mk1 \
	-tags "uio_pci_dma debug foxy" -gcflags "-N -l" \
	github.com/platinasystems/go/goes/goes-platina-mk1
eval $verbose wip...
go build -o $bin/wip \
	-tags "uio_pci_dma debug foxy" -gcflags "-N -l" \
	github.com/platinasystems/go/wip/y
eval $verbose goes-platina-mk1-bmc-arm.cpio.xz...
env GOARCH=arm $scripts/mkinitrd \
	github.com/platinasystems/go/goes/goes-platina-mk1-bmc
