// autogenerated: do not edit!
// generated from gentemplate [gentemplate -id adjGetCounterHook -d Package=ip -d DepsType=adjGetCounterHookVec -d Type=adjGetCounterHook -d Data=adjGetCounterHooks github.com/platinasystems/go/elib/dep/dep.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ip

import (
	"github.com/platinasystems/go/elib/dep"
)

type adjGetCounterHookVec struct {
	deps               dep.Deps
	adjGetCounterHooks []adjGetCounterHook
}

func (t *adjGetCounterHookVec) Len() int {
	return t.deps.Len()
}

func (t *adjGetCounterHookVec) Get(i int) adjGetCounterHook {
	return t.adjGetCounterHooks[t.deps.Index(i)]
}

func (t *adjGetCounterHookVec) Add(x adjGetCounterHook, ds ...*dep.Dep) {
	if len(ds) == 0 {
		t.deps.Add(&dep.Dep{})
	} else {
		t.deps.Add(ds[0])
	}
	t.adjGetCounterHooks = append(t.adjGetCounterHooks, x)
}
