// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip -id IfAddr -d VecType=IfAddrVec -d Type=IfAddr github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ip

import (
	"github.com/platinasystems/go/elib"
)

type IfAddrVec []IfAddr

func (p *IfAddrVec) Resize(n uint) {
	c := uint(cap(*p))
	l := uint(len(*p)) + n
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]IfAddr, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *IfAddrVec) validate(new_len uint, zero IfAddr) *IfAddr {
	c := uint(cap(*p))
	lʹ := uint(len(*p))
	l := new_len
	if l <= c {
		// Need to reslice to larger length?
		if l > lʹ {
			*p = (*p)[:l]
			for i := lʹ; i < l; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *IfAddrVec) validateSlowPath(zero IfAddr, c, l, lʹ uint) *IfAddr {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]IfAddr, cNext, cNext)
		copy(q, *p)
		for i := c; i < cNext; i++ {
			q[i] = zero
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *IfAddrVec) Validate(i uint) *IfAddr {
	var zero IfAddr
	return p.validate(i+1, zero)
}

func (p *IfAddrVec) ValidateInit(i uint, zero IfAddr) *IfAddr {
	return p.validate(i+1, zero)
}

func (p *IfAddrVec) ValidateLen(l uint) (v *IfAddr) {
	if l > 0 {
		var zero IfAddr
		v = p.validate(l, zero)
	}
	return
}

func (p *IfAddrVec) ValidateLenInit(l uint, zero IfAddr) (v *IfAddr) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *IfAddrVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p IfAddrVec) Len() uint { return uint(len(p)) }
