// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip -id multipathAdjacencyVec -d VecType=multipathAdjacencyVec -d Type=multipathAdjacency github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ip

import (
	"github.com/platinasystems/go/elib"
)

type multipathAdjacencyVec []multipathAdjacency

func (p *multipathAdjacencyVec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]multipathAdjacency, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *multipathAdjacencyVec) validate(new_len uint, zero *multipathAdjacency) *multipathAdjacency {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *multipathAdjacencyVec) validateSlowPath(zero *multipathAdjacency,
	c, l, lʹ elib.Index) *multipathAdjacency {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]multipathAdjacency, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *multipathAdjacencyVec) Validate(i uint) *multipathAdjacency {
	return p.validate(i+1, (*multipathAdjacency)(nil))
}

func (p *multipathAdjacencyVec) ValidateInit(i uint, zero multipathAdjacency) *multipathAdjacency {
	return p.validate(i+1, &zero)
}

func (p *multipathAdjacencyVec) ValidateLen(l uint) (v *multipathAdjacency) {
	if l > 0 {
		v = p.validate(l, (*multipathAdjacency)(nil))
	}
	return
}

func (p *multipathAdjacencyVec) ValidateLenInit(l uint, zero multipathAdjacency) (v *multipathAdjacency) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p multipathAdjacencyVec) Len() uint { return uint(len(p)) }
