// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip -id IfAddr -d VecType=IfAddrVec -d Type=IfAddr github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ip

import (
	"github.com/platinasystems/go/elib"
)

type IfAddrVec []IfAddr

func (p *IfAddrVec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]IfAddr, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *IfAddrVec) validate(new_len uint, zero IfAddr) *IfAddr {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *IfAddrVec) validateSlowPath(zero IfAddr, old_cap, new_len, old_len uint) *IfAddr {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]IfAddr, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *IfAddrVec) Validate(i uint) *IfAddr {
	var zero IfAddr
	return p.validate(i+1, zero)
}

func (p *IfAddrVec) ValidateInit(i uint, zero IfAddr) *IfAddr {
	return p.validate(i+1, zero)
}

func (p *IfAddrVec) ValidateLen(l uint) (v *IfAddr) {
	if l > 0 {
		var zero IfAddr
		v = p.validate(l, zero)
	}
	return
}

func (p *IfAddrVec) ValidateLenInit(l uint, zero IfAddr) (v *IfAddr) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *IfAddrVec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p IfAddrVec) Len() uint { return uint(len(p)) }
