// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ip -id ifaddress -d PoolType=ifAddressPool -d Type=IfAddress -d Data=ifAddrs github.com/platinasystems/go/elib/pool.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ip

import (
	"github.com/platinasystems/go/elib"
)

type ifAddressPool struct {
	elib.Pool
	ifAddrs []IfAddress
}

func (p *ifAddressPool) GetIndex() (i uint) {
	l := uint(len(p.ifAddrs))
	i = p.Pool.GetIndex(l)
	if i >= l {
		p.Validate(i)
	}
	return i
}

func (p *ifAddressPool) PutIndex(i uint) (ok bool) {
	return p.Pool.PutIndex(i)
}

func (p *ifAddressPool) IsFree(i uint) (v bool) {
	v = i >= uint(len(p.ifAddrs))
	if !v {
		v = p.Pool.IsFree(i)
	}
	return
}

func (p *ifAddressPool) Resize(n uint) {
	c := uint(cap(p.ifAddrs))
	l := uint(len(p.ifAddrs) + int(n))
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]IfAddress, l, c)
		copy(q, p.ifAddrs)
		p.ifAddrs = q
	}
	p.ifAddrs = p.ifAddrs[:l]
}

func (p *ifAddressPool) Validate(i uint) {
	c := uint(cap(p.ifAddrs))
	l := uint(i) + 1
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]IfAddress, l, c)
		copy(q, p.ifAddrs)
		p.ifAddrs = q
	}
	if l > uint(len(p.ifAddrs)) {
		p.ifAddrs = p.ifAddrs[:l]
	}
}

func (p *ifAddressPool) Elts() uint {
	return uint(len(p.ifAddrs)) - p.FreeLen()
}

func (p *ifAddressPool) Len() uint {
	return uint(len(p.ifAddrs))
}

func (p *ifAddressPool) Foreach(f func(x IfAddress)) {
	for i := range p.ifAddrs {
		if !p.Pool.IsFree(uint(i)) {
			f(p.ifAddrs[i])
		}
	}
}

func (p *ifAddressPool) ForeachIndex(f func(i uint)) {
	for i := range p.ifAddrs {
		if !p.Pool.IsFree(uint(i)) {
			f(uint(i))
		}
	}
}

func (p *ifAddressPool) Reset() {
	p.Pool.Reset()
	if len(p.ifAddrs) > 0 {
		p.ifAddrs = p.ifAddrs[:0]
	}
}
