// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=tomahawk -id l3_interface -d VecType=l3_interface_vec -d Type=l3_interface github.com/platinasystems/go/elib/vec.tmpl]

package tomahawk

import (
	"github.com/platinasystems/go/elib"
)

type l3_interface_vec []l3_interface

func (p *l3_interface_vec) Resize(n uint) {
	c := elib.Index(cap(*p))
	l := elib.Index(len(*p)) + elib.Index(n)
	if l > c {
		c = elib.NextResizeCap(l)
		q := make([]l3_interface, l, c)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:l]
}

func (p *l3_interface_vec) validate(new_len uint, zero *l3_interface) *l3_interface {
	c := elib.Index(cap(*p))
	lʹ := elib.Index(len(*p))
	l := elib.Index(new_len)
	if l <= c {
		// Need to reslice to larger length?
		if l >= lʹ {
			*p = (*p)[:l]
		}
		return &(*p)[l-1]
	}
	return p.validateSlowPath(zero, c, l, lʹ)
}

func (p *l3_interface_vec) validateSlowPath(zero *l3_interface,
	c, l, lʹ elib.Index) *l3_interface {
	if l > c {
		cNext := elib.NextResizeCap(l)
		q := make([]l3_interface, cNext, cNext)
		copy(q, *p)
		if zero != nil {
			for i := c; i < cNext; i++ {
				q[i] = *zero
			}
		}
		*p = q[:l]
	}
	if l > lʹ {
		*p = (*p)[:l]
	}
	return &(*p)[l-1]
}

func (p *l3_interface_vec) Validate(i uint) *l3_interface {
	return p.validate(i+1, (*l3_interface)(nil))
}

func (p *l3_interface_vec) ValidateInit(i uint, zero l3_interface) *l3_interface {
	return p.validate(i+1, &zero)
}

func (p *l3_interface_vec) ValidateLen(l uint) (v *l3_interface) {
	if l > 0 {
		v = p.validate(l, (*l3_interface)(nil))
	}
	return
}

func (p *l3_interface_vec) ValidateLenInit(l uint, zero l3_interface) (v *l3_interface) {
	if l > 0 {
		v = p.validate(l, &zero)
	}
	return
}

func (p l3_interface_vec) Len() uint { return uint(len(p)) }
