// Copyright © 2015-2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

package mod

const Usage = `
	ip link { add | change | delete | replace | set }
		[ dev DEVICE ]
		[ group GROUP ]
		[ link DEVICE ]
		[ up | down ]
		[ [no-]arp ] [ [no-]carreir ] [ [no-]dynamic ]
		[ [no-]multicast ] [ [no-]allmulticast ]
		[ [no-]promisc ] [ [no-]protodown ] [ [no-]trailers ]
		[ index INDEX ] [ { name | alias } NAME ]
		[ mtu MTU ] [ num[r|t]txqueues QUEUES ] [ txqueuelen PACKETS ]
		[ { address | broadcast } LLADDR ] 
		[ addrgenmode { eui64 | none | stable | random } ]
		[ master IFNAME | no-master ] [ vrf IFNAME | novrf ]
		[ netns { PID | NETNSNAME } ] [ link-netnsid ID ]
		[ vf NUM
			[ [no-]spoofchk ] [ [no-]query-rss ] [ [no-]trust ]
			[ mac LLADDR ]
			[ vlan ID ]
			[ qos PRIORITY ]
			[ rate Mbps | min-tx-rate Mbps max-tx-rate Mbps ]
			[ link-state { auto | enable | disable } ]
			[ {node|port}-guid EUI64 ]
		]
		[ type { bond | dummy | ifb | vcan | veth | ip6tnl | gretap
			| vti | nlmon | ipvlan | lowpan
			| bridge 
				[ [no-]stp-state ]
				[ [no-]vlan-filtering ]
				[ [no-]vlan-stats-enabled]
				[ [no-]mcast-snooping]
				[ [no-]mcast-stats-enabled ]
				[ [no-]nf-call-iptables ]
				[ [no-]nf-call-ip6tables ]
				[ [no-]nf-call-arptables ]
				[ ageing-time SECONDS ]
				[ group-fwd-mask LLADDR ]
				[ group-address LLADDR ]
				[ forward-delay 2 - 30 } ]
				[ hello-time { 1 - 10 } ]
				[ max-age { 6 - 40 } ]
				[ priority UINT16 ]
				[ vlan-protocol { 802.1Q | 802.1ad } ]
				[ vlan-default-pvid PVID ]
				[ mcast-router { disable, auto, permanent } ]
				[ mcast-query-use-ifaddr MCAST-QUERY-USE-IFADDR ]
				[ mcast-querier MULTICAST-QUERIER ]
				[ mcast-querier-interval QUERIER-INTERVAL ]
				[ mcast-hash-elasticity HASH-ELASTICITY ]
				[ mcast-hash-max HASH-MAX ]
				[ mcast-last-member-count COUNT ]
				[ mcast-last-member-interval INTERVAL ]
				[ mcast-startup-query-count COUNT ]
				[ mcast-startup-query-interval INTERVAL ]
				[ mcast-query-interval INTERVAL ]
				[ mcast-query-response-interval INTERVAL ]
				[ mcast-membership-interval INTERVAL ]
				[ mcast-igmp-version VERSION ]
				[ mcast-mld-version VERSION ]
			| geneve 
				[ [no-]external ]
				[ [no-]udpcsum ]
				[ [no-]udp6zerocsumtx ]
				[ [no-]udp6zerocsumrx ]
				[ id VNI ]
				[ remote IPADDR ]
				[ ttl TTL ]
				[ tos TOS ]
				[ flowlabel FLOWLABEL ]
				[ dstport PORT ]
			| { gre | gretap }
				[ remote ADDR ]
				[ local ADDR ]
				[ [no-][i|o]seq ]
				[ [i|o]key KEY ]
				[ no-[i|o]key ]
				[ [no-][i|o]csum ]
				[ [no-]pmtudisc ]
				[ ttl TTL ]
				[ tos TOS ]
				[ fwmark NUMBER ]
				[ dev DEVICE ]
				[ encap { fou | gue | none } ]
				[ encap-dport { PORT | any } ]
				[ encap-sport { PORT | any } ]
				[ [no-]encap-csum ]
				[ [no-]encap-csum6 ]
				[ [no-]encap-remsum ]
			| { ip6gre | ip6gretap } 
				[ remote ADDR ]
				[ local ADDR ]
				[ [no-][i|o]seq ]
				[ [i|o]key KEY ]
				[ no-[i|o]key ]
				[ [no-][i|o]csum ]
				[ hoplimit TTL ]
				[ encaplimit ELIM ]
				[ tclass TCLASS ]
				[ flowlabel FLOWLABEL ]
				[ dscp { inherit } ]
				[ fwmark NUMBER ]
				[ dev DEVICE ]
				[ encap { fou | gue | none } ]
				[ encap-dport { PORT | any } ]
				[ encap-sport { PORT | any } ]
				[ [no-]encap-csum ]
				[ [no-]encap-csum6 ]
				[ [no-]encap-remsum ]
			| { ipip | sit } 
				[ [no-]encap-csum ] [ [no-]encap-remcsum ]
				[ { remote | local } ADDR ]
				[ encap { fou | gue | none } ]
				[ encap-sport { auto | PORT } ]
				[ mode { ip6ip | ipip | mplsip | any } ]
			| hsr	[ { slave1 | slave2 } IFNAME ]
				[ subversion ADDR_BYTE ]
				[ version { 0 | 1 } ]
			| ipoib [ pkey NUMBER ]
				[ mode { datagram | connected } ]
				[ umcast NUMBER ]
			| macsec 
				[ [no-]encrypt ]
				[ [no-]send-sci ]
				[ [no-]end-station ]
				[ [no-]scb ]
				[ [no-]protect ]
				[ [no-]replay ]
				[ address LLADDR ]
				[ port PORT ]
				[ sci SCI ]
				[ cipher SUITE ]
				[ icvlen LENGTH ]
				[ validate { strict | check | disabled } ]
				[ encodingsa AN ]
			| { macvlan | macvtap }
				[ no-promisc ]
				[ mode { private | vepa | bridge | passthru |
					source }
			| vlan [link] DEVICE name NAME id ID
				[ protocol { 802.1q | 802.1ad } ]
				[ [no-]reorder-hdr ] [ [no-]loose-binding ]
				[ [no-]gvrp ] [ [no-]mvrp ]
				[ {ingress|egress}-qos-map FROM:TO ]
			| vxlan [link] DEVICE id VNI
				[ dev DEVICE ]
				[ { group | remote | local } IPADDR ]
				[ ttl TTL ] [ tos TOS ] [ flowlabel FLOWLABEL ]
				[ dstport PORT ] [ srcport MIN:MAX ]
				[ ageing SECONDS ] [ maxaddress NUMBER ]
				[ [no-]learning ] [ [no-]proxy ] [ [no-]rsc ]
				[ [no-]l2miss ] [ [no-]l3miss ]
				[ [no-]udpcsum ]
				[ [no-]udp6zerocsumtx ] [ [no-]udp6zerocsumrx ]
			| vrf table TABLE
		}

	`
