// Copyright © 2023 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

package netlink

const (
	IFLA_UNSPEC uint16 = iota
	IFLA_ADDRESS
	IFLA_BROADCAST
	IFLA_IFNAME
	IFLA_MTU
	IFLA_LINK
	IFLA_QDISC
	IFLA_STATS
	IFLA_COST
	IFLA_PRIORITY
	IFLA_MASTER
	IFLA_WIRELESS
	IFLA_PROTINFO
	IFLA_TXQLEN
	IFLA_MAP
	IFLA_WEIGHT
	IFLA_OPERSTATE
	IFLA_LINKMODE
	IFLA_LINKINFO
	IFLA_NET_NS_PID
	IFLA_IFALIAS
	IFLA_NUM_VF
	IFLA_VFINFO_LIST
	IFLA_STATS64
	IFLA_VF_PORTS
	IFLA_PORT_SELF
	IFLA_AF_SPEC
	IFLA_GROUP
	IFLA_NET_NS_FD
	IFLA_EXT_MASK
	IFLA_PROMISCUITY
	IFLA_NUM_TX_QUEUES
	IFLA_NUM_RX_QUEUES
	IFLA_CARRIER
	IFLA_PHYS_PORT_ID
	IFLA_CARRIER_CHANGES
	IFLA_PHYS_SWITCH_ID
	IFLA_LINK_NETNSID
	IFLA_PHYS_PORT_NAME
	IFLA_PROTO_DOWN
	IFLA_GSO_MAX_SEGS
	IFLA_GSO_MAX_SIZE
	IFLA_PAD
	IFLA_XDP
	IFLA_EVENT
	N_IFLA
)

const IFLA_MAX = N_IFLA - 1

const (
	IFLA_INFO_UNSPEC uint16 = iota
	IFLA_INFO_KIND
	IFLA_INFO_DATA
	IFLA_INFO_XSTATS
	IFLA_INFO_SLAVE_KIND
	IFLA_INFO_SLAVE_DATA
	N_IFLA_INFO
)

const IFLA_INFO_MAX = N_IFLA_INFO - 1

const (
	IF_LINK_MODE_DEFAULT uint8 = iota
	IF_LINK_MODE_DORMANT
)

var IfLinkModeByName = map[string]uint8{
	"default": IF_LINK_MODE_DEFAULT,
	"dormant": IF_LINK_MODE_DORMANT,
}

var IfLinkModeName = map[uint8]string{
	IF_LINK_MODE_DEFAULT: "default",
	IF_LINK_MODE_DORMANT: "dormant",
}

const (
	IF_OPER_UNKNOWN uint8 = iota
	IF_OPER_NOTPRESENT
	IF_OPER_DOWN
	IF_OPER_LOWERLAYERDOWN
	IF_OPER_TESTING
	IF_OPER_DORMANT
	IF_OPER_UP
)

var IfOperByName = map[string]uint8{
	"unknown":     IF_OPER_UNKNOWN,
	"not-present": IF_OPER_NOTPRESENT,
	"down":        IF_OPER_DOWN,
	"lower-down":  IF_OPER_LOWERLAYERDOWN,
	"testing":     IF_OPER_TESTING,
	"dormant":     IF_OPER_DORMANT,
	"up":          IF_OPER_UP,
}

var IfOperName = map[uint8]string{
	IF_OPER_UNKNOWN:        "unknown",
	IF_OPER_NOTPRESENT:     "not-present",
	IF_OPER_DOWN:           "down",
	IF_OPER_LOWERLAYERDOWN: "lower-down",
	IF_OPER_TESTING:        "testing",
	IF_OPER_DORMANT:        "dormant",
	IF_OPER_UP:             "up",
}

const (
	IFLA_INET6_UNSPEC uint16 = iota
	IFLA_INET6_FLAGS
	IFLA_INET6_CONF
	IFLA_INET6_STATS
	IFLA_INET6_MCAST
	IFLA_INET6_CACHEINFO
	IFLA_INET6_ICMP6STATS
	IFLA_INET6_TOKEN
	IFLA_INET6_ADDR_GEN_MODE
	N_IFLA_INET6
)

const IFLA_INET6_MAX = N_IFLA_INET6 - 1
