// Copyright © 2015-2023 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

package netlink

import "syscall"

const (
	RTM_NEWLINK = syscall.RTM_NEWLINK
	RTM_DELLINK = syscall.RTM_DELLINK
	RTM_GETLINK = syscall.RTM_GETLINK
	RTM_SETLINK = syscall.RTM_SETLINK

	RTM_NEWADDR = syscall.RTM_NEWADDR
	RTM_DELADDR = syscall.RTM_DELADDR
	RTM_GETADDR = syscall.RTM_GETADDR

	RTM_NEWROUTE = syscall.RTM_NEWROUTE
	RTM_DELROUTE = syscall.RTM_DELROUTE
	RTM_GETROUTE = syscall.RTM_GETROUTE

	RTM_NEWNEIGH = syscall.RTM_NEWNEIGH
	RTM_DELNEIGH = syscall.RTM_DELNEIGH
	RTM_GETNEIGH = syscall.RTM_GETNEIGH

	RTM_NEWRULE = syscall.RTM_NEWRULE
	RTM_DELRULE = syscall.RTM_DELRULE
	RTM_GETRULE = syscall.RTM_GETRULE

	RTM_NEWQDISC = syscall.RTM_NEWQDISC
	RTM_DELQDISC = syscall.RTM_DELQDISC
	RTM_GETQDISC = syscall.RTM_GETQDISC

	RTM_NEWTCLASS = syscall.RTM_NEWTCLASS
	RTM_DELTCLASS = syscall.RTM_DELTCLASS
	RTM_GETTCLASS = syscall.RTM_GETTCLASS

	RTM_NEWTFILTER = syscall.RTM_NEWTFILTER
	RTM_DELTFILTER = syscall.RTM_DELTFILTER
	RTM_GETTFILTER = syscall.RTM_GETTFILTER

	RTM_NEWACTION = syscall.RTM_NEWACTION
	RTM_DELACTION = syscall.RTM_DELACTION
	RTM_GETACTION = syscall.RTM_GETACTION

	RTM_NEWPREFIX = syscall.RTM_NEWPREFIX

	RTM_GETMULTICAST = syscall.RTM_GETMULTICAST

	RTM_GETANYCAST = syscall.RTM_GETANYCAST

	RTM_NEWNEIGHTBL = syscall.RTM_NEWNEIGHTBL
	RTM_GETNEIGHTBL = syscall.RTM_GETNEIGHTBL
	RTM_SETNEIGHTBL = syscall.RTM_SETNEIGHTBL

	RTM_NEWNDUSEROPT = syscall.RTM_NEWNDUSEROPT

	RTM_NEWADDRLABEL = syscall.RTM_NEWADDRLABEL
	RTM_DELADDRLABEL = syscall.RTM_DELADDRLABEL
	RTM_GETADDRLABEL = syscall.RTM_GETADDRLABEL

	RTM_GETDCB = syscall.RTM_GETDCB
	RTM_SETDCB = syscall.RTM_SETDCB

	RTM_NEWNETCONF = 80
	RTM_GETNETCONF = 82

	RTM_NEWMDB = 84
	RTM_DELMDB = 85
	RTM_GETMDB = 86

	RTM_NEWNSID = 88
	RTM_DELNSID = 89
	RTM_GETNSID = 90
)
