// Copyright © 2015-2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

// This package provides the commands required of all goes machines.
package required

import (
	"github.com/platinasystems/go/goes/required/apropos"
	"github.com/platinasystems/go/goes/required/bang"
	"github.com/platinasystems/go/goes/required/cat"
	"github.com/platinasystems/go/goes/required/cd"
	"github.com/platinasystems/go/goes/required/chmod"
	"github.com/platinasystems/go/goes/required/cli"
	"github.com/platinasystems/go/goes/required/cmdline"
	"github.com/platinasystems/go/goes/required/complete"
	"github.com/platinasystems/go/goes/required/cp"
	"github.com/platinasystems/go/goes/required/daemons"
	"github.com/platinasystems/go/goes/required/dmesg"
	"github.com/platinasystems/go/goes/required/echo"
	"github.com/platinasystems/go/goes/required/env"
	"github.com/platinasystems/go/goes/required/exec"
	"github.com/platinasystems/go/goes/required/exit"
	"github.com/platinasystems/go/goes/required/export"
	"github.com/platinasystems/go/goes/required/femtocom"
	"github.com/platinasystems/go/goes/required/get"
	"github.com/platinasystems/go/goes/required/hdel"
	"github.com/platinasystems/go/goes/required/hdelta"
	"github.com/platinasystems/go/goes/required/help"
	"github.com/platinasystems/go/goes/required/hexists"
	"github.com/platinasystems/go/goes/required/hget"
	"github.com/platinasystems/go/goes/required/hgetall"
	"github.com/platinasystems/go/goes/required/hkeys"
	"github.com/platinasystems/go/goes/required/hset"
	"github.com/platinasystems/go/goes/required/iminfo"
	"github.com/platinasystems/go/goes/required/insmod"
	"github.com/platinasystems/go/goes/required/install"
	"github.com/platinasystems/go/goes/required/kexec"
	"github.com/platinasystems/go/goes/required/keys"
	"github.com/platinasystems/go/goes/required/kill"
	"github.com/platinasystems/go/goes/required/license"
	"github.com/platinasystems/go/goes/required/ln"
	"github.com/platinasystems/go/goes/required/log"
	"github.com/platinasystems/go/goes/required/lrange"
	"github.com/platinasystems/go/goes/required/ls"
	"github.com/platinasystems/go/goes/required/lsmod"
	"github.com/platinasystems/go/goes/required/man"
	"github.com/platinasystems/go/goes/required/mkdir"
	"github.com/platinasystems/go/goes/required/mount"
	"github.com/platinasystems/go/goes/required/nld"
	"github.com/platinasystems/go/goes/required/nldump"
	"github.com/platinasystems/go/goes/required/nsid"
	"github.com/platinasystems/go/goes/required/patents"
	"github.com/platinasystems/go/goes/required/ping"
	"github.com/platinasystems/go/goes/required/ps"
	"github.com/platinasystems/go/goes/required/pwd"
	"github.com/platinasystems/go/goes/required/reboot"
	"github.com/platinasystems/go/goes/required/redisd"
	"github.com/platinasystems/go/goes/required/reload"
	"github.com/platinasystems/go/goes/required/resize"
	"github.com/platinasystems/go/goes/required/restart"
	"github.com/platinasystems/go/goes/required/rm"
	"github.com/platinasystems/go/goes/required/rmmod"
	"github.com/platinasystems/go/goes/required/set"
	"github.com/platinasystems/go/goes/required/show_commands"
	"github.com/platinasystems/go/goes/required/slashinit"
	"github.com/platinasystems/go/goes/required/sleep"
	"github.com/platinasystems/go/goes/required/source"
	"github.com/platinasystems/go/goes/required/start"
	"github.com/platinasystems/go/goes/required/stop"
	"github.com/platinasystems/go/goes/required/stty"
	"github.com/platinasystems/go/goes/required/subscribe"
	"github.com/platinasystems/go/goes/required/sync"
	"github.com/platinasystems/go/goes/required/umount"
	"github.com/platinasystems/go/goes/required/uninstall"
	"github.com/platinasystems/go/goes/required/uptimed"
	"github.com/platinasystems/go/goes/required/usage"
	"github.com/platinasystems/go/goes/required/version"
	"github.com/platinasystems/go/goes/required/wget"
)

func New() []interface{} {
	return []interface{}{
		apropos.New(),
		bang.New(),
		cat.New(),
		cd.New(),
		chmod.New(),
		cli.New(),
		cmdline.New(),
		complete.New(),
		cp.New(),
		daemons.New(),
		dmesg.New(),
		echo.New(),
		env.New(),
		exec.New(),
		exit.New(),
		export.New(),
		femtocom.New(),
		get.New(),
		hdel.New(),
		hdelta.New(),
		help.New(),
		hexists.New(),
		hget.New(),
		hgetall.New(),
		hkeys.New(),
		hset.New(),
		iminfo.New(),
		insmod.New(),
		install.New(),
		kexec.New(),
		keys.New(),
		kill.New(),
		license.New(),
		ln.New(),
		log.New(),
		lrange.New(),
		ls.New(),
		lsmod.New(),
		man.New(),
		mkdir.New(),
		mount.New(),
		nld.New(),
		nldump.New(),
		nsid.New(),
		patents.New(),
		ping.New(),
		ps.New(),
		pwd.New(),
		reboot.New(),
		redisd.New(),
		reload.New(),
		resize.New(),
		restart.New(),
		rm.New(),
		rmmod.New(),
		set.New(),
		show_commands.New(),
		slashinit.New(),
		sleep.New(),
		source.New(),
		start.New(),
		stop.New(),
		stty.New(),
		subscribe.New(),
		sync.New(),
		umount.New(),
		uninstall.New(),
		uptimed.New(),
		usage.New(),
		version.New(),
		wget.New(),
	}
}
