// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs -- if_utun_darwin.go

package nettun

const (
	IFNAMSIZ		= 0x10
	AF_SYS_CONTROL		= 0x2
	AF_SYSTEM		= 0x20
	PF_SYSTEM		= 0x20
	SYSPROTO_CONTROL	= 0x2
	CTLIOCGINFO		= 0xc0644e03
)

type CtlInfo struct {
	Id	uint32
	Name	[96]int8
}

const SizeofCtlInfo = 0x64

type SockaddrCtl struct {
	Sc_len		uint8
	Sc_family	uint8
	Ss_sysaddr	uint16
	Sc_id		uint32
	Sc_unit		uint32
	Sc_reserved	[5]uint32
}

const SizeofSockaddrCtl = 0x20

const UTUN_CONTROL_NAME = "com.apple.net.utun_control"

const (
	UTUN_OPT_FLAGS	= 0x1
	UTUN_OPT_IFNAME	= 0x2

	UTUN_OPT_EXT_IFDATA_STATS	= 0x3

	UTUN_OPT_INC_IFDATA_STATS_IN	= 0x4

	UTUN_OPT_INC_IFDATA_STATS_OUT	= 0x5

	UTUN_OPT_SET_DELEGATE_INTERFACE	= 0xf

	UTUN_OPT_MAX_PENDING_PACKETS	= 0x10
	UTUN_OPT_ENABLE_CHANNEL		= 0x11
	UTUN_OPT_GET_CHANNEL_UUID	= 0x12
	UTUN_OPT_ENABLE_FLOWSWITCH	= 0x13

	UTUN_OPT_ENABLE_NETIF	= 0x14

	UTUN_OPT_SLOT_SIZE	= 0x15

	UTUN_OPT_NETIF_RING_SIZE	= 0x16

	UTUN_OPT_TX_FSW_RING_SIZE	= 0x17

	UTUN_OPT_RX_FSW_RING_SIZE	= 0x18

	UTUN_OPT_KPIPE_TX_RING_SIZE	= 0x19

	UTUN_OPT_KPIPE_RX_RING_SIZE	= 0x1a

	UTUN_OPT_ATTACH_FLOWSWITCH	= 0x1b
)

const (
	UTUN_FLAGS_NO_OUTPUT		= 0x1
	UTUN_FLAGS_NO_INPUT		= 0x2
	UTUN_FLAGS_ENABLE_PROC_UUID	= 0x4
)

type UtunStatsParam struct {
	Packets	uint64
	Bytes	uint64
	Errors	uint64
}

const SizeofUtunStatsParam = 0x18
