// Copyright © 2024 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by the GPL-2 license described in the
// LICENSE file.

package named_conf

import "testing"

func TestDataGetToken(t *testing.T) {
	testdata(t, fnGetToken, expectGetToken)
}

const fnGetToken = "testdata/bind9/fuzz/isc_lex_gettoken.in/named.conf"

var expectGetToken = Conf{
	Statement{"options", Block{
		Statement{"additional-from-auth", "true"},
		Statement{"additional-from-cache", "false"},
		Statement{"version", "my version string"},
		Statement{"random-device", "/dev/random"},
		Statement{"directory", "/tmp"},
		Statement{"port", "666"},
		Statement{"sig-validity-interval", "33"},
		Statement{"named-xfer", "/usr/libexec/named-xfer"},
		Statement{"dump-file", "named_dump.db"},
		Statement{"pid-file", "/var/run/named.pid"},
		Statement{"statistics-file", "named.stats"},
		Statement{"memstatistics-file", "named.memstats"},
		Statement{"max-cache-ttl", "999"},
		Statement{"min-cache-ttl", "66"},
		Statement{"auth-nxdomain", "yes"},
		Statement{"deallocate-on-exit", "no"},
		Statement{"fake-iquery", "no"},
		Statement{"fetch-glue", "yes"},
		Statement{"has-old-clients", "yes"},
		Statement{"host-statistics", "no"},
		Statement{"multiple-cnames", "no"},
		Statement{"notify", "yes"},
		Statement{"recursion", "yes"},
		Statement{"rfc2308-type1", "no"},
		Statement{"use-id-pool", "yes"},
		Statement{"treat-cr-as-space", "yes"},
		Statement{"also-notify", Block{Statement{"10.0.2.3"}}},
		Statement{"forward", "first"},
		Statement{"forwarders", Block{
			Statement{"1.2.3.4"},
			Statement{"5.6.7.8"},
		}},
		Statement{"check-names", "primary", "fail"},
		Statement{"check-names", "secondary", "warn"},
		Statement{"check-names", "response", "ignore"},
		Statement{"allow-query", Block{Statement{"any"}}},
		Statement{"allow-transfer", Block{Statement{"any"}}},
		Statement{"allow-recursion", Block{Statement{"!any"}}},
		Statement{"blackhole", Block{
			Statement{"45", "/", "24"},
		}},
		Statement{"keep-response-order", Block{
			Statement{"46", "/", "24"},
		}},
		Statement{"listen-on", Block{
			Statement{"10", "/", "24"},
			Statement{"10.0.0.3"},
		}},
		Statement{"listen-on", "port", "53", Block{
			Statement{"any"},
		}},
		Statement{"listen-on", Block{Statement{"5.6.7.8"}}},
		Statement{"listen-on", "port", "1234", Block{
			Statement{"!1.2.3.4"},
			Statement{"1.2.3", "/", "24"},
		}},
		Statement{"listen-on-v6", Block{Statement{
			"1:1:1:1:1:1:1:1",
		}}},
		Statement{"listen-on-v6", "port", "777", Block{Statement{
			"2:2:2:2:2:2:2:2",
		}}},
		Statement{"query-source-v6",
			"address", "8:7:6:5:4:3:2:1",
			"port", "*",
		},
		Statement{"query-source",
			"port", "*",
			"address", "10.0.0.54",
		},
		Statement{"lame-ttl", "444"},
		Statement{"max-transfer-time-in", "300"},
		Statement{"max-transfer-time-out", "10"},
		Statement{"max-transfer-idle-in", "100"},
		Statement{"max-transfer-idle-out", "11"},
		Statement{"max-retry-time", "1234"},
		Statement{"min-retry-time", "1111"},
		Statement{"max-refresh-time", "888"},
		Statement{"min-refresh-time", "777"},
		Statement{"max-ncache-ttl", "333"},
		Statement{"min-ncache-ttl", "22"},
		Statement{"min-roots", "15"},
		Statement{"serial-queries", "34"},
		Statement{"transfer-format", "one-answer"},
		Statement{"transfers-in", "10"},
		Statement{"transfers-per-ns", "2"},
		Statement{"transfers-out", "0"},
		Statement{"transfer-source", "10.0.0.5"},
		Statement{"transfer-source-v6", "4:3:2:1:5:6:7:8"},
		Statement{"request-ixfr", "yes"},
		Statement{"provide-ixfr", "yes"},
		Statement{"max-ixfr-log-size", "20m"},
		Statement{"max-cache-size", "1m"},
		Statement{"interface-interval", "1002"},
		Statement{"statistics-interval", "1003"},
		Statement{"topology", Block{
			Statement{"10", "/", "8"},
			Statement{"!1.2.3", "/", "24"},
			Statement{Block{
				Statement{"1.2", "/", "16"},
				Statement{"3", "/", "8"},
			}},
		}},
		Statement{"sortlist", Block{
			Statement{"10", "/", "8"},
			Statement{"11", "/", "8"},
		}},
		Statement{"tkey-domain", "foo.com"},
		Statement{"tkey-dhkey", "xyz", "666"},
		Statement{"rrset-order", Block{
			Statement{
				"class", "IN",
				"type", "A",
				"name", "foo",
				"order", "random",
			},
			Statement{"order", "cyclic"},
		}},
	}},
	Statement{"controls", Block{
		Statement{
			"inet", "*",
			"port", "52",
			"allow", Block{Statement{"any"}},
			"keys", Block{Statement{"key2"}},
		},
		Statement{
			"unix", "/var/run/ndc",
			"perm", "0600",
			"owner", "0",
			"group", "0",
		},
		Statement{
			"inet", "10.0.0.1",
			"allow", Block{
				Statement{"any"},
				Statement{"key", "foo"},
			},
			"keys", Block{Statement{"key4"}},
		},
		Statement{
			"inet", "10.0.0.2",
			"allow", Block{Statement{"none"}},
			"keys", Block{
				Statement{"key-1"},
				Statement{"key-2"},
			},
		},
		Statement{
			"inet", "10.0.0.2",
			"allow", Block{Statement{"none"}},
		},
	}},
	Statement{"zone", "primary.demo.zone", Block{
		Statement{"type", "primaryr"},
		Statement{"database",
			"somedb -option1 -option2 arg1 arg2 arg3"},
		Statement{"file", "primary.demo.zone"},
		Statement{"check-names", "fail"},
		Statement{"allow-update", Block{Statement{"none"}}},
		Statement{"allow-update-forwarding", Block{
			Statement{"10.0.0.5"},
			Statement{"!any"},
		}},
		Statement{"allow-transfer", Block{Statement{"any"}}},
		Statement{"allow-query", Block{Statement{"any"}}},
		Statement{"sig-validity-interval", "990"},
		Statement{"notify", "explicit"},
		Statement{"also-notify", Block{
			Statement{"1.0.0.1"},
		}},
		Statement{"forward", "first"},
		Statement{"forwarders", Block{
			Statement{"10.0.0.3"},
			Statement{"1:2:3:4:5:6:7:8"},
		}},
	}},
	Statement{"zone", "secondary.demo.zone", Block{
		Statement{"type", "secondary"},
		Statement{"file", "secondary.demo.zone"},
		Statement{"ixfr-base", "secondary.demo.zone.ixfr"},
		Statement{"primaries", Block{
			Statement{"1.2.3.4", "port", "10", "key", "foo"},
			Statement{"5.6.7.8"},
			Statement{"6.7.8.9", "key", "zippo"},
		}},
		Statement{"transfer-source", "10.0.0.53"},
		Statement{"check-names", "warn"},
		Statement{"allow-update", Block{Statement{"none"}}},
		Statement{"allow-transfer", Block{Statement{"any"}}},
		Statement{"allow-update-forwarding", Block{Statement{"any"}}},
		Statement{"allow-query", Block{Statement{"any"}}},
		Statement{"max-transfer-time-in", "120"},
		Statement{"max-transfer-time-out", "1"},
		Statement{"max-transfer-idle-in", "2"},
		Statement{"max-transfer-idle-out", "3"},
		Statement{"also-notify", Block{Statement{"1.0.0.2"}}},
		Statement{"forward", "only"},
		Statement{"forwarders", Block{
			Statement{"10.45.45.45"},
			Statement{"10.0.0.3"},
			Statement{"1:2:3:4:5:6:7:8"},
		}},
	}},
	Statement{"key", "non-viewkey", Block{
		Statement{"secret", "YWFh"},
		Statement{"algorithm", "zzz"},
	}},
	Statement{"view", "test-view", "in", Block{
		Statement{"key", "viewkey", Block{
			Statement{"algorithm", "xxx"},
			Statement{"secret", "eXl5"},
		}},
		Statement{"also-notify", Block{Statement{"10.2.2.3"}}},
		Statement{"managed-keys", Block{Statement{
			"foo.com.static", "4", "3", "2",
			"abdefghijklmnopqrstuvwxyz",
		}}},
		Statement{"sig-validity-interval", "45"},
		Statement{"max-cache-size", "100000"},
		Statement{"allow-query", Block{Statement{"10.0.0.30"}}},
		Statement{"additional-from-cache", "false"},
		Statement{"additional-from-auth", "no"},
		Statement{"match-clients", Block{Statement{"10.0.0.1"}}},
		Statement{"check-names", "primary", "warn"},
		Statement{"check-names", "secondary", "ignore"},
		Statement{"check-names", "response", "fail"},
		Statement{"auth-nxdomain", "false"},
		Statement{"recursion", "true"},
		Statement{"provide-ixfr", "false"},
		Statement{"request-ixfr", "true"},
		Statement{"fetch-glue", "true"},
		Statement{"notify", "false"},
		Statement{"rfc2308-type1", "false"},
		Statement{"transfer-source", "10.0.0.55"},
		Statement{"transfer-source-v6", "4:3:8:1:5:6:7:8"},
		Statement{"query-source",
			"port", "*",
			"address", "10.0.0.54",
		},
		Statement{"query-source-v6",
			"address", "6:6:6:6:6:6:6:6",
			"port", "*",
		},
		Statement{"max-transfer-time-out", "45"},
		Statement{"max-transfer-idle-out", "55"},
		Statement{"min-roots", "3"},
		Statement{"lame-ttl", "477"},
		Statement{"max-ncache-ttl", "333"},
		Statement{"max-cache-ttl", "777"},
		Statement{"transfer-format", "many-answers"},
		Statement{"max-retry-time", "7"},
		Statement{"min-retry-time", "4"},
		Statement{"max-refresh-time", "999"},
		Statement{"min-refresh-time", "111"},
		Statement{"zone", "view-zone.com", Block{
			Statement{"type", "primary"},
			Statement{"allow-update-forwarding", Block{
				Statement{"10.0.0.34"},
			}},
			Statement{"file", "view-zone-primary"},
		}},
		Statement{"server", "5.6.7.8", Block{
			Statement{"keys", "viewkey"},
		}},
		Statement{"server", "10.9.8.7", Block{
			Statement{"keys", "non-viewkey"},
		}},
	}},
	Statement{"zone", "stub.demo.zone", Block{
		Statement{"type", "stub"},
		Statement{"file", "stub.demo.zone"},
		Statement{"primaries", Block{
			Statement{"1.2.3.4"},
			Statement{"5.6.7.8", "port", "999"},
		}},
		Statement{"check-names", "warn"},
		Statement{"allow-update", Block{Statement{"none"}}},
		Statement{"allow-transfer", Block{Statement{"any"}}},
		Statement{"allow-query", Block{Statement{"any"}}},
		Statement{"max-retry-time", "10"},
		Statement{"min-retry-time", "11"},
		Statement{"max-refresh-time", "12"},
		Statement{"min-refresh-time", "13"},
		Statement{"max-transfer-time-in", "120"},
		Statement{"pubkey", "257", "255", "1", "a useless key"},
		Statement{"pubkey", "257", "255", "1", "another useless key"},
	}},
	Statement{"zone", ".", Block{
		Statement{"type", "hint"},
		Statement{"file", "cache.db"},
	}},
	Statement{"managed-keys", Block{
		Statement{".", "static", "257", "255", "1",
			"AQP2fHpZ4VMpKo/jc9Fod821uyfY5p8j5h/Am0V/",
			"KpBTMZjdXmp9QJe6yFRoIIzkaNCgTIftASdpXGgCwFB2j2KXP",
			"/rick6gvEer5VcDEkLR5Q=="},
	}},
	Statement{"acl", "can_query", Block{
		Statement{"!1.2.3", "/", "24"},
		Statement{"any"},
	}},
	Statement{"acl", "can_axfr", Block{
		Statement{"1.2.3.4"},
		Statement{"can_query"},
	}},
	Statement{"zone", "disabled-zone.com", Block{
		Statement{"type", "primary"},
		Statement{"file", "bar"},
		Statement{"max-retry-time", "100"},
		Statement{"min-retry-time", "110"},
		Statement{"max-refresh-time", "120"},
		Statement{"min-refresh-time", "130"},
	}},
	Statement{"zone", "non-default-acl.demo.zone", Block{
		Statement{"type", "primary"},
		Statement{"file", "foo"},
		Statement{"allow-query", Block{Statement{"can_query"}}},
		Statement{"allow-transfer", Block{Statement{"can_axfr"}}},
		Statement{"allow-update", Block{
			Statement{"1.2.3.4"},
			Statement{"5.6.7.8"},
		}},
		Statement{"pubkey", "666", "665", "664", "key of the beast"},
		Statement{"update-policy", Block{
			Statement{"grant", "root.domain.subdomain",
				"host.domain.A", "MX", "CNAME"},
			Statement{"grant", "sub.root.domain.wildcard",
				"*.host.domain.A"},
			Statement{"grant", "root.domain.name", "host.domain.a",
				"ns", "md", "mf", "cname", "soa", "mb", "mg",
				"mr", "null", "wks", "ptr", "hinfo", "minfo",
				"mx", "txt", "rp", "afsdb", "x25", "isdn", "rt",
				"nsap", "sig", "key", "px", "gpos", "aaaa",
				"loc", "nxt", "srv", "naptr", "kx", "cert",
				"a6", "dname", "opt", "unspec", "uri",
				"tkey", "tsig"},
			Statement{"grant", "foo.bar.com.self", "foo.bar.com.a"},
		}},
	}},
	Statement{"key", "sample_key", Block{
		Statement{"algorithm", "hmac-md5"},
		Statement{"secret", "eW91ciBzZWNyZXQgaGVyZQ=="},
	}},
	Statement{"key", "key2", Block{
		Statement{"algorithm", "hmac-md5"},
		Statement{"secret", "ZXJlaCB0ZXJjZXMgcm91eQ=="},
	}},
	Statement{"acl", "key_acl", Block{
		Statement{"key", "sample_key"},
	}},
	Statement{"server", "1.2.3.4", Block{
		Statement{"request-ixfr", "no"},
		Statement{"provide-ixfr", "no"},
		Statement{"bogus", "no"},
		Statement{"transfer-format", "one-answer"},
		Statement{"transfers", "0"},
		Statement{"keys", Block{"sample_key"}},
	}},
	Statement{"logging", Block{
		Statement{"channel", "syslog_errors", Block{
			Statement{"syslog", "user"},
			Statement{"severity", "error"},
		}},
		Statement{"channel", "stderr_errors", Block{
			Statement{"stderr"},
		}},
		Statement{"category", "parser", Block{
			Statement{"syslog_errors"},
			Statement{"default_syslog"},
		}},
		Statement{"category", "lame-servers", Block{
			Statement{"null"},
		}},
		Statement{"channel", "moderate_debug", Block{
			Statement{"file", "foo"},
			Statement{"severity", "debug", "3"},
			Statement{"print-time", "yes"},
			Statement{"print-category", "yes"},
			Statement{"print-severity", "yes"},
		}},
		Statement{"channel", "another", Block{
			Statement{
				"file", "bar",
				"versions", "99",
				"size", "10M",
			},
			Statement{"severity", "info"},
		}},
		Statement{"channel", "third", Block{
			Statement{
				"file", "bar",
				"size", "100000",
				"versions", "unlimited",
			},
			Statement{"severity", "debug"},
		}},
		Statement{"channel", "no_info_messages", Block{
			Statement{"syslog"},
			Statement{"severity", "notice"},
		}},
		Statement{"category", "load", Block{
			Statement{"no_info_messages"},
		}},
		Statement{"category", "default", Block{
			Statement{"default_syslog"},
			Statement{"moderate_debug"},
		}},
	}},
}
