// autogenerated: do not edit!
// generated from gentemplate [gentemplate -d Package=ethernet -id inject_packet_disposition -d VecType=inject_packet_disposition_vec -d Type=inject_packet_disposition github.com/platinasystems/go/elib/vec.tmpl]

// Copyright 2016 Platina Systems, Inc. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package ethernet

import (
	"github.com/platinasystems/go/elib"
)

type inject_packet_disposition_vec []inject_packet_disposition

func (p *inject_packet_disposition_vec) Resize(n uint) {
	old_cap := uint(cap(*p))
	new_len := uint(len(*p)) + n
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]inject_packet_disposition, new_len, new_cap)
		copy(q, *p)
		*p = q
	}
	*p = (*p)[:new_len]
}

func (p *inject_packet_disposition_vec) validate(new_len uint, zero inject_packet_disposition) *inject_packet_disposition {
	old_cap := uint(cap(*p))
	old_len := uint(len(*p))
	if new_len <= old_cap {
		// Need to reslice to larger length?
		if new_len > old_len {
			*p = (*p)[:new_len]
			for i := old_len; i < new_len; i++ {
				(*p)[i] = zero
			}
		}
		return &(*p)[new_len-1]
	}
	return p.validateSlowPath(zero, old_cap, new_len, old_len)
}

func (p *inject_packet_disposition_vec) validateSlowPath(zero inject_packet_disposition, old_cap, new_len, old_len uint) *inject_packet_disposition {
	if new_len > old_cap {
		new_cap := elib.NextResizeCap(new_len)
		q := make([]inject_packet_disposition, new_cap, new_cap)
		copy(q, *p)
		for i := old_len; i < new_cap; i++ {
			q[i] = zero
		}
		*p = q[:new_len]
	}
	if new_len > old_len {
		*p = (*p)[:new_len]
	}
	return &(*p)[new_len-1]
}

func (p *inject_packet_disposition_vec) Validate(i uint) *inject_packet_disposition {
	var zero inject_packet_disposition
	return p.validate(i+1, zero)
}

func (p *inject_packet_disposition_vec) ValidateInit(i uint, zero inject_packet_disposition) *inject_packet_disposition {
	return p.validate(i+1, zero)
}

func (p *inject_packet_disposition_vec) ValidateLen(l uint) (v *inject_packet_disposition) {
	if l > 0 {
		var zero inject_packet_disposition
		v = p.validate(l, zero)
	}
	return
}

func (p *inject_packet_disposition_vec) ValidateLenInit(l uint, zero inject_packet_disposition) (v *inject_packet_disposition) {
	if l > 0 {
		v = p.validate(l, zero)
	}
	return
}

func (p *inject_packet_disposition_vec) ResetLen() {
	if *p != nil {
		*p = (*p)[:0]
	}
}

func (p inject_packet_disposition_vec) Len() uint { return uint(len(p)) }
